import { Feather } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useEffect, useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { apiFetch } from "@/lib/api";
import ScreenSafeArea from "@/components/ScreenSafeArea";
import { useColors } from "@/hooks/useColors";

const modules = [["zap", "AskV"], ["message-square", "Channels"], ["calendar", "Calendar"], ["folder", "Files & Notes"], ["check-square", "Tasks & Forms"], ["video", "Meetings"], ["search", "Search"], ["settings", "Settings & Connections"]] as const;
export default function WorkHubScreen() { const colors = useColors(); const [status, setStatus] = useState("Loading your workspace…"); useEffect(() => { apiFetch("/api/work-hub/home").then(() => setStatus("Your workspace is ready")).catch(() => setStatus("Work Hub is not enabled for this organization yet.")); }, []); return <ScreenSafeArea style={{ backgroundColor: colors.background }}><ScrollView contentContainerStyle={{ padding: 20, gap: 16 }}><View><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "700", letterSpacing: 2 }}>WORK HUB</Text><Text accessibilityRole="header" style={{ color: colors.text, fontSize: 30, fontWeight: "700", marginTop: 5 }}>One place for the work around the work.</Text><Text accessibilityLiveRegion="polite" style={{ color: colors.mutedForeground, marginTop: 8 }}>{status}</Text></View><View style={{ gap: 12 }}>{modules.map(([icon, label]) => <Pressable key={label} accessibilityRole="button" accessibilityLabel={`Open ${label}`} onPress={() => router.push({ pathname: "/work-hub/[module]", params: { module: label.toLowerCase().replace(/ & /g, "-").replace(/ /g, "-") } } as never)} style={({ pressed }) => ({ minHeight: 68, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 16, flexDirection: "row", alignItems: "center", gap: 14, opacity: pressed ? .7 : 1, backgroundColor: colors.card })}><Feather name={icon} size={22} color={colors.primary}/><Text style={{ color: colors.text, fontSize: 17, fontWeight: "600" }}>{label}</Text></Pressable>)}</View></ScrollView></ScreenSafeArea>; }
