/** Explicit server-read adapters. A new registry tool is not exposed automatically. */
export const CHATGPT_READ_CAPABILITIES = {
  "fleet:read": { label: "Explicitly authorized Fleet company, runs, stops, loads, inspection reports and dispatch context", tools: ["query_fleet_review_packet","query_fleet_equipment_replacements","query_fleet_cargo_transfers","query_fleet_evidence","query_fleet_run_eta","query_fleet_support","query_fleet_site_activity","query_fleet_gate_observations","query_fleet_report","query_fleet_saved_views","query_fleet_maintenance", "query_fleet_settings", "query_fleet_capabilities", "query_fleet_briefing", "query_fleet_runs", "query_fleet_run_detail", "query_fleet_resources"] },
  "invitations:read": { label: "Vendor administrator invitation enrollment and delivery status", tools: ["query_account_invitations", "prepare_account_invitations_action"] },
  "workforce:read": { label: "Authorized staffing coverage, field roster and assignment status", tools: ["query_workforce_coverage", "prepare_workforce_coverage_action", "query_ticket_assignment_candidates"] },
  "tickets:read": { label: "Assigned tickets, work details, and proof", tools: ["lookup_open_tickets", "query_tickets", "query_ticket_detail", "query_ticket_proof_packet", "query_ticket_crew", "query_ticket_labor", "query_ticket_notes", "query_work_type_history", "query_flagged_tickets", "query_ticket_logged_miles", "query_ticket_mileage_audit"] },
  "sites:read": { label: "Authorized sites and operational status", tools: ["query_site_locations", "lookup_site_detail", "lookup_site_operational_status"] },
  "crew:read": { label: "Authorized crew locations, routes, GPS trails, and ETA", tools: ["query_field_trips", "query_field_trip_eta", "prepare_field_trips_action", "query_live_crew", "lookup_crew_member_status", "query_crew_eta", "query_crew_route_summary", "query_gps_trail", "query_ticket_route_eta", "lookup_map_origin", "estimate_driving_route"] },
  "finance:read": { label: "Authorized invoices, payment status, accounting status, and reports", tools: ["lookup_open_invoices", "query_invoice_summary", "query_invoices", "query_invoice_lines", "query_ar_aging", "query_revenue_summary", "query_crew_cost", "lookup_ticket_payment_status", "lookup_accounting_connection", "query_sales_tax_by_state", "query_nec1099_summary", "query_1099_k_summary", "query_1099_misc_summary"] },
  "catalog:read": { label: "Catalog, Hotlist, approvals, certifications, and company contacts", tools: ["query_hotlist_jobs", "query_hotlist_bids", "query_vendor_catalog", "query_partner_approvals", "query_certifications", "lookup_org_contacts"] },
  "safety:read": { label: "Authorized safety events, safety metrics, and dictated drafts", tools: ["query_safety_events", "lookup_safety_metrics", "query_incident_response", "prepare_incident_response_action", "draft_safety_report"] },
  "onboarding:read": { label: "Your permitted onboarding progress", tools: ["lookup_user_progress"] },
  "operations:read": { label: "Authorized notifications, attention items, assets, subscriptions, and operating metrics", tools: ["get_stock_quote", "get_crude_oil_price", "deep_link_to", "query_notifications", "query_attention_briefing", "query_vendor_performance", "query_field_metrics", "query_asset_custody", "query_asset_identifier_claims", "query_asset_identifier_review_queue", "prepare_asset_custody_action", "query_worker_subscriptions", "prepare_worker_subscriptions_action", "query_operations_displays", "prepare_operations_displays_action"] },
} as const;
export type ChatGptReadCapabilityScope = keyof typeof CHATGPT_READ_CAPABILITIES;
