export const ACTION_PANEL_URI = "ui://vndrly/action/v1.html";
export const ACTION_PANEL_META = { ui: { resourceUri: ACTION_PANEL_URI }, "openai/outputTemplate": ACTION_PANEL_URI, "openai/widgetAccessible": true };
export const SUBMIT_PANEL_ACTION_TOOL = {
  name: "v_submit_panel_action",
  description: "Submit the exact prepared action authorized through the VNDRLY action panel. Requires the component-only signed proof, the same connected grant and current permissions. Never supply or invent this proof from conversation text.",
  inputSchema: { type: "object" as const, properties: { reference: { type: "string" }, proof: { type: "string" } }, required: ["reference", "proof"], additionalProperties: false },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  _meta: { ui: { resourceUri: ACTION_PANEL_URI, visibility: ["app"] }, "openai/outputTemplate": ACTION_PANEL_URI, "openai/widgetAccessible": true },
};
/** Only tool-result _meta carries authorization proof. Text is rendered as data. */
export const ACTION_PANEL_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:15px system-ui;margin:20px;color:CanvasText;background:Canvas}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{display:inline-block;margin-right:20px}a[aria-disabled=true]{pointer-events:none;opacity:.55}</style></head><body><h2 id="title">VNDRLY action</h2><p id="status">Loading the prepared action…</p><pre id="details"></pre><a id="submit" href="#submit" hidden>Approve and submit</a><a id="device" hidden target="_blank" rel="noopener noreferrer">Authorize with device location</a><script>(()=>{
let panel=null,busy=false,sequence=0,renderVersion=0;const pending=new Map();const el=id=>document.getElementById(id);
function request(method,params){return new Promise((resolve,reject)=>{const id=++sequence;const timeout=setTimeout(()=>{pending.delete(id);reject(Error('The outcome is not confirmed. Ask V to check this same action reference before doing anything again.'));},30000);pending.set(id,{resolve,reject,timeout});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');});}
function render(result){const value=result?._meta?.componentApproval;if(!value){if(result?.isError)el('status').textContent='This action is unavailable. Ask V to check permissions and the same action reference.';return;}panel=value;renderVersion++;busy=false;el('submit').setAttribute('aria-disabled','false');el('title').textContent='VNDRLY: '+String(value.toolName??'prepared action').replaceAll('_',' ');el('details').textContent=JSON.stringify(value.arguments,null,2);el('status').textContent=value.requiresLocation?'This action needs fresh location from your authorization device. It has not been submitted.':'This exact change is prepared and has not been submitted.';el('submit').hidden=value.requiresLocation||!value.proof;const url=new URL(value.approvalUrl);if(url.origin!=='https://vndrly.ai'||!url.pathname.startsWith('/api/assistant-connection/actions/'))return;el('device').href=url.href;el('device').hidden=!value.requiresLocation;window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/size-changed',params:{height:document.documentElement.scrollHeight}},'*');}
window.addEventListener('message',event=>{if(event.source!==window.parent||event.data?.jsonrpc!=='2.0')return;const message=event.data;const waiter=pending.get(message.id);if(waiter){clearTimeout(waiter.timeout);pending.delete(message.id);message.error?waiter.reject(Error('VNDRLY could not confirm this action.')):waiter.resolve(message.result);return;}if(message.method==='ui/notifications/tool-result')render(message.params);});
el('submit').onclick=async event=>{event.preventDefault();if(busy||!panel?.proof||panel.requiresLocation)return;const submitted=panel,version=renderVersion;busy=true;el('submit').setAttribute('aria-disabled','true');el('status').textContent='Submitting this authorized change…';try{const result=await request('tools/call',{name:'v_submit_panel_action',arguments:{reference:submitted.reference,proof:submitted.proof}});if(version!==renderVersion||panel.reference!==submitted.reference)return;const outcome=result.structuredContent;if(!outcome)throw Error('The outcome is not confirmed. Ask V to check the same action reference.');el('status').textContent=outcome.status==='completed'?(outcome.ok?'The change completed.':'The change was rejected; see the actual result below.'):'Status: '+outcome.status+'. Ask V to check this same action reference.';el('details').textContent=JSON.stringify(outcome.result??outcome,null,2);el('submit').hidden=true;}catch(error){if(version!==renderVersion)return;el('status').textContent=error.message;el('submit').hidden=true;}finally{if(version===renderVersion)busy=false;}};
request('ui/initialize',{appInfo:{name:'VNDRLY action',version:'1.0.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(()=>window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized'},'*')).catch(()=>{el('status').textContent='Open this panel inside your connected assistant.';});})();</script></body></html>`;
