import { describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import express from "express";
import cookieParser from "cookie-parser";
import request from "supertest";
import { db, vendorsTable, partnersTable, siteLocationsTable, workTypesTable, ticketsTable, vendorPeopleTable, usersTable, safetyEventsTable, safetyIncidentResponsesTable, workHubShiftsTable, workHubShiftAssignmentsTable, workforceCoverageRecordsTable } from "@workspace/db";
import safetyRouter from "../routes/implementationASafety";
import workforceRouter from "../routes/implementationAWorkforce";
import { buildTestCookie } from "../test-utils/session";
import { assertFreshLocalTestDatabaseEnvironment } from "../../../../scripts/fresh-test-database.mjs";
import { runOpsDataTool } from "./data-tools-ops";
import { runTool } from "../routes/assistant";

describe.skipIf(process.env.VNDRLY_TEST_DB_MODE !== "fresh-local")("assistant read authorization against isolated records", () => {
  it("preserves simultaneous approved onboarding field updates", async () => {
    assertFreshLocalTestDatabaseEnvironment(process.env);
    const suffix = randomUUID();
    const [vendor] = await db.insert(vendorsTable).values({ name: `onboarding-lock-${suffix}`, contactName: "Synthetic", contactEmail: `${suffix}@example.invalid` }).returning();
    const [user] = await db.insert(usersTable).values({ username: `onboarding-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Synthetic admin", role: "vendor" }).returning();
    const session = { userId: user.id, role: "vendor", vendorId: vendor.id, membershipRole: "admin" };
    await runTool("start_onboarding", {}, session, "");
    const results = await Promise.all(["federalTaxId", "stateTaxId", "physicalAddress", "billingAddress"].map(path => runTool("set_onboarding_field", { path: `taxIds.${path}`, value: `synthetic-${path}` }, session, "")));
    expect(results.map(result => JSON.parse(result).ok)).toEqual([true, true, true, true]);
    const progress = JSON.parse(await runTool("lookup_user_progress", {}, session, ""));
    expect(progress.progress.payload.taxIds).toEqual({ federalTaxId: "synthetic-federalTaxId", stateTaxId: "synthetic-stateTaxId", physicalAddress: "synthetic-physicalAddress", billingAddress: "synthetic-billingAddress" });
  });
  it("blocks foreign payment data, limits worker tickets, and refuses member onboarding reads", async () => {
    assertFreshLocalTestDatabaseEnvironment(process.env);
    const suffix = randomUUID();
    const [user] = await db.insert(usersTable).values({ username: `read-scope-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Isolated read fixture", role: "field_employee" }).returning();
    const vendors = await db.insert(vendorsTable).values([1, 2].map(n => ({ name: `scope-vendor-${n}-${suffix}`, contactName: "Isolated fixture", contactEmail: `v${n}-${suffix}@example.invalid` }))).returning();
    const partners = await db.insert(partnersTable).values([1, 2].map(n => ({ name: `scope-partner-${n}-${suffix}`, contactName: "Isolated fixture", contactEmail: `p${n}-${suffix}@example.invalid` }))).returning();
    const sites = await db.insert(siteLocationsTable).values(partners.map((partner, i) => ({ partnerId: partner.id, name: "Isolated site", address: "Synthetic", latitude: 0, longitude: 0, siteCode: `S${i}-${suffix}` }))).returning();
    const [workType] = await db.insert(workTypesTable).values({ name: `Scope fixture ${suffix}`, category: "service" }).returning();
    const [worker] = await db.insert(vendorPeopleTable).values({ vendorId: vendors[0].id, firstName: "Synthetic", lastName: "Worker", email: `${suffix}@example.invalid` }).returning();
    const tickets = await db.insert(ticketsTable).values(vendors.map((vendor, i) => ({ vendorId: vendor.id, siteLocationId: sites[i].id, workTypeId: workType.id, fieldEmployeeId: i === 0 ? worker.id : null, paymentReference: `private-payment-${i}-${suffix}` }))).returning();
    await db.insert(vendorPeopleTable).values([1, 2].map(n => ({ vendorId: vendors[1].id, firstName: "Foreign", lastName: `Crew ${n}`, email: `foreign-${n}-${suffix}@example.invalid` })));
    const foreignSchedule = await runTool("schedule_ticket_crew", { ticketId: tickets[1].id, crewMemberName: "Foreign", scheduledStartAt: "2026-10-10T12:00:00.000Z", confirmed: true }, { userId: user.id, role: "vendor", vendorId: vendors[0].id }, "");
    expect(JSON.parse(foreignSchedule)).toHaveProperty("error");
    expect(JSON.parse(foreignSchedule)).not.toHaveProperty("matches");
    expect(foreignSchedule).not.toContain("@example.invalid");
    for (const session of [{ userId: user.id, role: "vendor", vendorId: vendors[0].id }, { userId: user.id, role: "partner", partnerId: partners[0].id }]) {
      expect(JSON.parse(await runOpsDataTool("lookup_ticket_payment_status", { ticketId: tickets[0].id }, session))).toMatchObject({ id: tickets[0].id });
      const refused = await runOpsDataTool("lookup_ticket_payment_status", { ticketId: tickets[1].id }, session);
      expect(JSON.parse(refused)).toHaveProperty("error");
      expect(refused).not.toContain(tickets[1].paymentReference!);
    }
    const employee = { userId: user.id, role: "field_employee", vendorPeopleId: worker.id, vendorId: vendors[0].id };
    const app = express().use(express.json()).use(cookieParser()).use(safetyRouter).use(workforceRouter);
    const [otherUser] = await db.insert(usersTable).values({ username: `other-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Other worker", role: "field_employee" }).returning();
    const events = await db.insert(safetyEventsTable).values([0, 1, 2].map(n => ({ eventNumber: `E${n}-${suffix}`, eventType: "unsafe_condition", title: "Synthetic safety event", siteLocationId: sites[n === 2 ? 1 : 0].id, partnerId: partners[n === 2 ? 1 : 0].id, vendorId: vendors[n === 2 ? 1 : 0].id, reportedByUserId: n === 0 ? user.id : otherUser.id }))).returning();
    await db.insert(safetyIncidentResponsesTable).values(events.map(event => ({ eventId: event.id, originalReport: "private synthetic report" })));
    const incidents = await request(app).get("/implementation-a/safety/incidents").set("Cookie", buildTestCookie(employee)).expect(200);
    expect(incidents.body.incidents.map((row: { eventId: number }) => row.eventId)).toEqual([events[0].id]);
    expect(JSON.stringify(incidents.body)).not.toContain("private synthetic report");
    await request(app).get(`/implementation-a/safety/incidents/${events[1].id}`).set("Cookie", buildTestCookie(employee)).expect(404);
    const vendorIncidents = await request(app).get("/implementation-a/safety/incidents").set("Cookie", buildTestCookie({ ...employee, role: "vendor" })).expect(200);
    expect(vendorIncidents.body.incidents).toHaveLength(2);
    await request(app).get(`/implementation-a/safety/incidents/${events[2].id}`).set("Cookie", buildTestCookie({ ...employee, role: "vendor" })).expect(404);
    const shifts = await db.insert(workHubShiftsTable).values([0, 1, 2].map(n => ({ ownerOrgType: "vendor", ownerOrgId: vendors[n === 2 ? 1 : 0].id, title: "Synthetic shift", startsAt: new Date(), endsAt: new Date(Date.now() + 3600000), timezone: "America/Chicago", createdById: user.id }))).returning();
    await db.insert(workHubShiftAssignmentsTable).values({ shiftId: shifts[0].id, userId: user.id });
    await db.insert(workforceCoverageRecordsTable).values(shifts.map(shift => ({ shiftId: shift.id, vacancyOrigin: "synthetic" })));
    const ownCoverage = await request(app).get("/implementation-a/workforce/coverage").set("Cookie", buildTestCookie(employee)).expect(200);
    expect(ownCoverage.body.coverage.map((row: { shiftId: string }) => row.shiftId)).toEqual([shifts[0].id]);
    const adminCoverage = await request(app).get("/implementation-a/workforce/coverage").set("Cookie", buildTestCookie({ ...employee, role: "vendor", membershipRole: "admin" })).expect(200);
    expect(adminCoverage.body.coverage).toHaveLength(2);
    expect(adminCoverage.body.coverage.some((row: { shiftId: string }) => row.shiftId === shifts[2].id)).toBe(false);
    await db.insert(ticketsTable).values(["cancelled", "denied", "funds_dispersed", "completed", "submitted", "approved", "awaiting_payment"].map(status => ({ vendorId: vendors[0].id, siteLocationId: sites[0].id, workTypeId: workType.id, fieldEmployeeId: worker.id, status, createdAt: new Date(Date.now() + 1000) })));
    const visible = JSON.parse(await runTool("lookup_open_tickets", {}, employee, ""));
    expect(visible.tickets.map((ticket: { id: number }) => ticket.id)).toEqual([tickets[0].id]);
    expect(JSON.parse(await runTool("lookup_open_tickets", {}, { userId: user.id, role: "field_employee", vendorId: vendors[0].id }, ""))).toHaveProperty("error");
    expect(JSON.parse(await runTool("lookup_user_progress", {}, { userId: user.id, role: "vendor", vendorId: vendors[0].id, membershipRole: "member" }, ""))).toHaveProperty("error");
  });
});
