/** Raster Mapbox tiles need no cross-origin worker in the assistant iframe. */
export const FLEET_MAP_CLIENT = `
let fleetMap=null,fleetViewport=null;
function renderFleetMap(output,parent){if(!output.fleetMap)return;const section=add(parent,'section','','attention');add(section,'h2','Fleet locations');const points=output.fleetMap.points;const status=add(section,'p','Green: recent. Amber: stale. Gray: paused. Select a marker for its recorded update.');if(!points.length){status.textContent='No authorized reliable positions returned. The trip list remains available.';return;}if(!output.fleetMap.publicToken?.startsWith('pk.')){status.textContent='Map configuration unavailable. The trip list remains available.';return;}
const project=(lat,lng,z)=>{const scale=256*Math.pow(2,z),s=Math.sin(Math.max(-85.05112878,Math.min(85.05112878,lat))*Math.PI/180);return {x:(lng+180)/360*scale,y:(0.5-Math.log((1+s)/(1-s))/(4*Math.PI))*scale};};
const controls=add(section,'p','');const zoomIn=add(controls,'a','Zoom in');zoomIn.href='#zoom-in';add(controls,'span',' · ');const zoomOut=add(controls,'a','Zoom out');zoomOut.href='#zoom-out';add(controls,'span',' · Drag to pan');const container=add(section,'div','');container.style.cssText='height:360px;width:100%;position:relative;overflow:hidden;touch-action:none;background:#e2e8f0;';container.setAttribute('aria-label','Map of authorized recorded fleet locations');
const initial={latitude:points.reduce((n,p)=>n+p.latitude,0)/points.length,longitude:points.reduce((n,p)=>n+p.longitude,0)/points.length,zoom:12};const width=container.clientWidth||600;for(let z=12;z>=1;z--){const positions=points.map(p=>project(p.latitude,p.longitude,z));initial.zoom=z;if(Math.max(...positions.map(p=>p.x))-Math.min(...positions.map(p=>p.x))<width-80&&Math.max(...positions.map(p=>p.y))-Math.min(...positions.map(p=>p.y))<280)break;}if(!fleetViewport)fleetViewport=initial;
function draw(){if(!container.isConnected)return;container.replaceChildren();const w=container.clientWidth||600,h=360,z=fleetViewport.zoom,center=project(fleetViewport.latitude,fleetViewport.longitude,z),left=center.x-w/2,top=center.y-h/2,tiles=Math.pow(2,z);for(let x=Math.floor(left/256);x<=Math.floor((left+w)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+h)/256);y++){if(y<0||y>=tiles)continue;const img=document.createElement('img');img.alt='';img.draggable=false;img.style.cssText='position:absolute;width:256px;height:256px;';img.style.left=(x*256-left)+'px';img.style.top=(y*256-top)+'px';img.src='https://api.mapbox.com/styles/v1/mapbox/streets-v12/tiles/256/'+z+'/'+((x%tiles+tiles)%tiles)+'/'+y+'?access_token='+encodeURIComponent(output.fleetMap.publicToken);img.onerror=()=>{status.textContent='Some map tiles could not load. Use the recorded trip list.';};container.append(img);}points.forEach(point=>{const p=project(point.latitude,point.longitude,z);let dx=p.x-left;const world=tiles*256;while(dx<0)dx+=world;while(dx>w&&dx-world>=0)dx-=world;const dy=p.y-top;if(dx<0||dx>w||dy<0||dy>h)return;const marker=add(container,'a','●');marker.href='#location';marker.title=point.label+' · '+point.freshness+' · '+new Date(point.recordedAt).toLocaleString();marker.style.cssText='position:absolute;font-size:26px;text-decoration:none;transform:translate(-50%,-50%);';marker.style.left=dx+'px';marker.style.top=dy+'px';marker.style.color=point.freshness==='recent'?'#15803D':point.freshness==='stale'?'#F59E0B':'#64748b';marker.onpointerdown=e=>e.stopPropagation();marker.onclick=e=>{e.preventDefault();status.textContent=marker.title;};});const attribution=add(container,'div','');attribution.style.cssText='position:absolute;bottom:0;right:0;background:white;color:#222;padding:2px 5px;font-size:11px;';const mapbox=add(attribution,'a','© Mapbox');mapbox.href='https://www.mapbox.com/about/maps/';mapbox.target='_blank';mapbox.rel='noopener noreferrer';add(attribution,'span',' · ');const osm=add(attribution,'a','© OpenStreetMap');osm.href='https://www.openstreetmap.org/copyright';osm.target='_blank';osm.rel='noopener noreferrer';}
function zoom(delta){fleetViewport.zoom=Math.max(1,Math.min(18,fleetViewport.zoom+delta));draw();}zoomIn.onclick=e=>{e.preventDefault();zoom(1);};zoomOut.onclick=e=>{e.preventDefault();zoom(-1);};let drag=null;container.onpointerdown=e=>{if(e.target.closest('a'))return;const c=project(fleetViewport.latitude,fleetViewport.longitude,fleetViewport.zoom);drag={x:e.clientX,y:e.clientY,c};container.setPointerCapture(e.pointerId);};container.onpointermove=e=>{if(!drag)return;const scale=256*Math.pow(2,fleetViewport.zoom),x=drag.c.x-(e.clientX-drag.x),y=drag.c.y-(e.clientY-drag.y);fleetViewport.longitude=((x/scale*360-180+540)%360)-180;fleetViewport.latitude=Math.atan(Math.sinh(Math.PI*(1-2*y/scale)))*180/Math.PI;draw();};container.onpointerup=()=>{drag=null;};container.onpointercancel=()=>{drag=null;};fleetMap={remove:()=>{drag=null;}};draw();}
setInterval(()=>{if(current?.view==='fleet'&&selectedView==='fleet'&&!navigationPending&&!document.hidden)load('fleet',true);},60000);
`;
