import { describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import express from "express";
import cookieParser from "cookie-parser";
import request from "supertest";
import { db, vendorsTable, partnersTable, siteLocationsTable, workTypesTable, ticketsTable, vendorPeopleTable, usersTable, safetyEventsTable, safetyIncidentResponsesTable, workHubShiftsTable, workHubShiftAssignmentsTable, workforceCoverageRecordsTable, assetsTable, partnerVendorRelationshipsTable, siteWorkAssignmentsTable } from "@workspace/db";
import safetyRouter from "../routes/implementationASafety";
import safetyReportsRouter from "../routes/safety";
import workforceRouter from "../routes/implementationAWorkforce";
import tripsRouter from "../routes/implementationATrips";
import ticketsRouter from "../routes/tickets";
import { attachTestErrorMiddleware, expectStatus } from "../test-utils/route-app";
import { buildTestCookie } from "../test-utils/session";
import { assertFreshLocalTestDatabaseEnvironment } from "../../../../scripts/fresh-test-database.mjs";
import { runOpsDataTool } from "./data-tools-ops";
import { runTool } from "../routes/assistant";

describe.skipIf(process.env.VNDRLY_TEST_DB_MODE !== "fresh-local")("assistant read authorization against isolated records", () => {
  it("persists submission then owning-partner approval and preserves its timestamp on replay", async () => {
    assertFreshLocalTestDatabaseEnvironment(process.env);
    const suffix = randomUUID();
    const [vendor] = await db.insert(vendorsTable).values({ name: `approval-vendor-${suffix}`, contactName: "Synthetic", contactEmail: `v-${suffix}@example.invalid` }).returning();
    const partners = await db.insert(partnersTable).values([1, 2].map(n => ({ name: `approval-partner-${n}-${suffix}`, contactName: "Synthetic", contactEmail: `p${n}-${suffix}@example.invalid` }))).returning();
    const [user] = await db.insert(usersTable).values({ username: `approval-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Synthetic approver", role: "partner" }).returning();
    const [site] = await db.insert(siteLocationsTable).values({ partnerId: partners[0].id, name: "Synthetic approval site", address: "Synthetic", latitude: 0, longitude: 0, siteCode: `AP-${suffix}` }).returning();
    const [workType] = await db.insert(workTypesTable).values({ name: `Approval fixture ${suffix}`, category: "service" }).returning();
    const [ticket] = await db.insert(ticketsTable).values({ vendorId: vendor.id, siteLocationId: site.id, workTypeId: workType.id, status: "completed", lifecycleState: "off_site" }).returning();
    const app = express().use(express.json()).use(cookieParser()).use(ticketsRouter);
    attachTestErrorMiddleware(app);
    const [submitter] = await db.insert(usersTable).values({ username: `submitter-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Synthetic vendor", role: "vendor" }).returning();
    expectStatus(await request(app).post(`/tickets/${ticket.id}/submit`).set("Cookie", buildTestCookie({ userId: submitter.id, role: "vendor", vendorId: vendor.id })).send({}), 200);
    const [submitted] = await db.select().from(ticketsTable).where(eq(ticketsTable.id, ticket.id));
    expect(submitted).toMatchObject({ status: "submitted", lifecycleState: "off_site" });
    await request(app).post(`/tickets/${ticket.id}/approve`).set("Cookie", buildTestCookie({ userId: user.id, role: "partner", partnerId: partners[1].id })).send({}).expect(403);
    const [unchanged] = await db.select().from(ticketsTable).where(eq(ticketsTable.id, ticket.id));
    expect(unchanged.status).toBe("submitted");
    const cookie = buildTestCookie({ userId: user.id, role: "partner", partnerId: partners[0].id });
    expectStatus(await request(app).post(`/tickets/${ticket.id}/approve`).set("Cookie", cookie).send({}), 200);
    const [approved] = await db.select().from(ticketsTable).where(eq(ticketsTable.id, ticket.id));
    expect(approved).toMatchObject({ status: "approved", lifecycleState: "off_site" });
    expect(approved.approvedAt).not.toBeNull();
    expectStatus(await request(app).post(`/tickets/${ticket.id}/approve`).set("Cookie", cookie).send({}), 200);
    const [replayed] = await db.select().from(ticketsTable).where(eq(ticketsTable.id, ticket.id));
    expect(replayed.approvedAt).toEqual(approved.approvedAt);
  });
  it("preserves managed site grants while allowing a resolved legacy worker to report on a stopped assigned site", async () => {
    assertFreshLocalTestDatabaseEnvironment(process.env);
    const suffix = randomUUID();
    const [vendor] = await db.insert(vendorsTable).values({ name: `report-vendor-${suffix}`, contactName: "Synthetic", contactEmail: `v-${suffix}@example.invalid` }).returning();
    const [partner] = await db.insert(partnersTable).values({ name: `report-partner-${suffix}`, contactName: "Synthetic", contactEmail: `p-${suffix}@example.invalid` }).returning();
    const [user] = await db.insert(usersTable).values({ username: `reporter-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Synthetic reporter", role: "field_employee" }).returning();
    const [worker] = await db.insert(vendorPeopleTable).values({ vendorId: vendor.id, userId: user.id, firstName: "Synthetic", lastName: "Reporter", email: `w-${suffix}@example.invalid` }).returning();
    const [site] = await db.insert(siteLocationsTable).values({ partnerId: partner.id, name: "Stopped synthetic site", address: "Synthetic", latitude: 0, longitude: 0, siteCode: `SR-${suffix}`, isActive: false, status: "inactive" }).returning();
    const [workType] = await db.insert(workTypesTable).values({ name: `Reporting ${suffix}`, category: "service" }).returning();
    await db.insert(partnerVendorRelationshipsTable).values({ partnerId: partner.id, vendorId: vendor.id, status: "approved" });
    await db.insert(siteWorkAssignmentsTable).values({ siteLocationId: site.id, vendorId: vendor.id, workTypeId: workType.id });
    await db.insert(ticketsTable).values({ vendorId: vendor.id, siteLocationId: site.id, workTypeId: workType.id, fieldEmployeeId: worker.id, status: "in_progress", lifecycleState: "on_site" });
    const app = express().use(express.json()).use(cookieParser()).use(safetyReportsRouter);
    const reporter = { userId: user.id, role: "field_employee", vendorId: vendor.id };
    const input = { siteLocationId: site.id, title: "Synthetic follow-up", eventType: "observation" };
    await request(app).post("/safety/events").set("Cookie", buildTestCookie({ ...reporter, vendorPeopleId: worker.id, managedSubcontractor: { siteGrants: [] } })).send({ ...input, isStopWork: true }).expect(403);
    const [unassignedTicket] = await db.insert(ticketsTable).values({ vendorId: vendor.id, siteLocationId: site.id, workTypeId: workType.id, status: "initiated" }).returning();
    const deniedTicket = await request(app).post("/safety/events").set("Cookie", buildTestCookie({ ...reporter, vendorPeopleId: worker.id })).send({ ...input, ticketId: unassignedTicket.id }).expect(403);
    expect(deniedTicket.body.code).toBe("safety.forbidden_ticket");
    await request(app).post("/safety/events").set("Cookie", buildTestCookie(reporter)).send(input).expect(201);
    await db.update(siteLocationsTable).set({ hidden: true }).where(eq(siteLocationsTable.id, site.id));
    await request(app).post("/safety/events").set("Cookie", buildTestCookie(reporter)).send(input).expect(403);
  });
  it("preserves simultaneous approved onboarding field updates", async () => {
    assertFreshLocalTestDatabaseEnvironment(process.env);
    const suffix = randomUUID();
    const [vendor] = await db.insert(vendorsTable).values({ name: `onboarding-lock-${suffix}`, contactName: "Synthetic", contactEmail: `${suffix}@example.invalid` }).returning();
    const [user] = await db.insert(usersTable).values({ username: `onboarding-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Synthetic admin", role: "vendor" }).returning();
    const session = { userId: user.id, role: "vendor", vendorId: vendor.id, membershipRole: "admin" };
    await runTool("start_onboarding", {}, session, "");
    const results = await Promise.all(["federalTaxId", "stateTaxId", "physicalAddress", "billingAddress"].map(path => runTool("set_onboarding_field", { path: `taxIds.${path}`, value: `synthetic-${path}` }, session, "")));
    expect(results.map(result => JSON.parse(result).ok)).toEqual([true, true, true, true]);
    const progress = JSON.parse(await runTool("lookup_user_progress", {}, session, ""));
    expect(progress.progress.payload.taxIds).toEqual({ federalTaxId: "synthetic-federalTaxId", stateTaxId: "synthetic-stateTaxId", physicalAddress: "synthetic-physicalAddress", billingAddress: "synthetic-billingAddress" });
  });
  it("blocks foreign payment data, limits worker tickets, and refuses member onboarding reads", async () => {
    assertFreshLocalTestDatabaseEnvironment(process.env);
    const suffix = randomUUID();
    const [user] = await db.insert(usersTable).values({ username: `read-scope-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Isolated read fixture", role: "field_employee" }).returning();
    const vendors = await db.insert(vendorsTable).values([1, 2].map(n => ({ name: `scope-vendor-${n}-${suffix}`, contactName: "Isolated fixture", contactEmail: `v${n}-${suffix}@example.invalid` }))).returning();
    const partners = await db.insert(partnersTable).values([1, 2].map(n => ({ name: `scope-partner-${n}-${suffix}`, contactName: "Isolated fixture", contactEmail: `p${n}-${suffix}@example.invalid` }))).returning();
    const sites = await db.insert(siteLocationsTable).values(partners.map((partner, i) => ({ partnerId: partner.id, name: "Isolated site", address: "Synthetic", latitude: 0, longitude: 0, siteCode: `S${i}-${suffix}` }))).returning();
    const [workType] = await db.insert(workTypesTable).values({ name: `Scope fixture ${suffix}`, category: "service" }).returning();
    const [worker] = await db.insert(vendorPeopleTable).values({ vendorId: vendors[0].id, userId: user.id, firstName: "Synthetic", lastName: "Worker", email: `${suffix}@example.invalid` }).returning();
    const tickets = await db.insert(ticketsTable).values(vendors.map((vendor, i) => ({ vendorId: vendor.id, siteLocationId: sites[i].id, workTypeId: workType.id, fieldEmployeeId: i === 0 ? worker.id : null, paymentReference: `private-payment-${i}-${suffix}` }))).returning();
    await db.insert(vendorPeopleTable).values([1, 2].map(n => ({ vendorId: vendors[1].id, firstName: "Foreign", lastName: `Crew ${n}`, email: `foreign-${n}-${suffix}@example.invalid` })));
    const foreignSchedule = await runTool("schedule_ticket_crew", { ticketId: tickets[1].id, crewMemberName: "Foreign", scheduledStartAt: "2026-10-10T12:00:00.000Z", confirmed: true }, { userId: user.id, role: "vendor", vendorId: vendors[0].id }, "");
    expect(JSON.parse(foreignSchedule)).toHaveProperty("error");
    expect(JSON.parse(foreignSchedule)).not.toHaveProperty("matches");
    expect(foreignSchedule).not.toContain("@example.invalid");
    for (const session of [{ userId: user.id, role: "vendor", vendorId: vendors[0].id }, { userId: user.id, role: "partner", partnerId: partners[0].id }]) {
      expect(JSON.parse(await runOpsDataTool("lookup_ticket_payment_status", { ticketId: tickets[0].id }, session))).toMatchObject({ id: tickets[0].id });
      const refused = await runOpsDataTool("lookup_ticket_payment_status", { ticketId: tickets[1].id }, session);
      expect(JSON.parse(refused)).toHaveProperty("error");
      expect(refused).not.toContain(tickets[1].paymentReference!);
    }
    const employee = { userId: user.id, role: "field_employee", vendorPeopleId: worker.id, vendorId: vendors[0].id };
    const app = express().use(express.json()).use(cookieParser()).use(safetyRouter).use(safetyReportsRouter).use(workforceRouter).use(tripsRouter);
    const reportInput = { eventType: "unsafe_condition", title: "Synthetic scope regression", siteLocationId: sites[1].id, isStopWork: true };
    await request(app).post("/safety/events").set("Cookie", buildTestCookie(employee)).send(reportInput).expect(403);
    const [foreignSite] = await db.select().from(siteLocationsTable).where(eq(siteLocationsTable.id, sites[1].id));
    expect(foreignSite.isActive).toBe(true);
    const ownerCookie = buildTestCookie({ userId: user.id, role: "partner", partnerId: partners[0].id });
    await request(app).post("/safety/events").set("Cookie", ownerCookie).send({ ...reportInput, siteLocationId: sites[0].id, vendorId: vendors[1].id }).expect(403);
    await request(app).post("/safety/events").set("Cookie", ownerCookie).send({ ...reportInput, siteLocationId: sites[0].id, ticketId: tickets[1].id }).expect(403);
    const [otherUser] = await db.insert(usersTable).values({ username: `other-${suffix}`, passwordHash: "unused-isolated-fixture", displayName: "Other worker", role: "field_employee" }).returning();
    await db.insert(vendorPeopleTable).values({ vendorId: vendors[1].id, userId: otherUser.id, firstName: "Foreign", lastName: "Worker", email: `other-${suffix}@example.invalid` });
    const events = await db.insert(safetyEventsTable).values([0, 1, 2].map(n => ({ eventNumber: `E${n}-${suffix}`, eventType: "unsafe_condition", title: "Synthetic safety event", siteLocationId: sites[n === 2 ? 1 : 0].id, partnerId: partners[n === 2 ? 1 : 0].id, vendorId: vendors[n === 2 ? 1 : 0].id, reportedByUserId: n === 0 ? user.id : otherUser.id }))).returning();
    await db.insert(safetyIncidentResponsesTable).values(events.map(event => ({ eventId: event.id, originalReport: "private synthetic report" })));
    await request(app).post(`/implementation-a/safety/incidents/${events[0].id}/acknowledge`).set("Cookie", buildTestCookie(employee)).expect(403);
    await request(app).post(`/implementation-a/safety/incidents/${events[0].id}/close`).set("Cookie", buildTestCookie(employee)).send({ resolution: "Synthetic resolution" }).expect(403);
    await db.update(safetyIncidentResponsesTable).set({ safetyChainSnapshot: [user.id] }).where(eq(safetyIncidentResponsesTable.eventId, events[0].id));
    await request(app).post(`/implementation-a/safety/incidents/${events[0].id}/acknowledge`).set("Cookie", buildTestCookie(employee)).expect(200);
    await db.update(safetyIncidentResponsesTable).set({ closedAt: new Date(), responseStatus: "closed" }).where(eq(safetyIncidentResponsesTable.eventId, events[0].id));
    await request(app).post(`/implementation-a/safety/incidents/${events[0].id}/acknowledge`).set("Cookie", buildTestCookie(employee)).expect(409);
    const [closedResponse] = await db.select().from(safetyIncidentResponsesTable).where(eq(safetyIncidentResponsesTable.eventId, events[0].id));
    expect(closedResponse.responseStatus).toBe("closed");
    const incidents = await request(app).get("/implementation-a/safety/incidents").set("Cookie", buildTestCookie(employee)).expect(200);
    expect(incidents.body.incidents.map((row: { eventId: number }) => row.eventId)).toEqual([events[0].id]);
    expect(JSON.stringify(incidents.body)).not.toContain("private synthetic report");
    await request(app).get(`/implementation-a/safety/incidents/${events[1].id}`).set("Cookie", buildTestCookie(employee)).expect(404);
    const vendorIncidents = await request(app).get("/implementation-a/safety/incidents").set("Cookie", buildTestCookie({ ...employee, role: "vendor" })).expect(200);
    expect(vendorIncidents.body.incidents).toHaveLength(2);
    await request(app).get(`/implementation-a/safety/incidents/${events[2].id}`).set("Cookie", buildTestCookie({ ...employee, role: "vendor" })).expect(404);
    const shifts = await db.insert(workHubShiftsTable).values([0, 1, 2].map(n => ({ ownerOrgType: "vendor", ownerOrgId: vendors[n === 2 ? 1 : 0].id, title: "Synthetic shift", startsAt: new Date(), endsAt: new Date(Date.now() + 3600000), timezone: "America/Chicago", createdById: user.id }))).returning();
    await db.insert(workHubShiftAssignmentsTable).values({ shiftId: shifts[0].id, userId: user.id });
    await db.insert(workforceCoverageRecordsTable).values(shifts.map(shift => ({ shiftId: shift.id, vacancyOrigin: "synthetic" })));
    const ownCoverage = await request(app).get("/implementation-a/workforce/coverage").set("Cookie", buildTestCookie(employee)).expect(200);
    expect(ownCoverage.body.coverage.map((row: { shiftId: string }) => row.shiftId)).toEqual([shifts[0].id]);
    const adminCoverage = await request(app).get("/implementation-a/workforce/coverage").set("Cookie", buildTestCookie({ ...employee, role: "vendor", membershipRole: "admin" })).expect(200);
    expect(adminCoverage.body.coverage).toHaveLength(2);
    expect(adminCoverage.body.coverage.some((row: { shiftId: string }) => row.shiftId === shifts[2].id)).toBe(false);
    const adminCookie = buildTestCookie({ ...employee, role: "vendor", membershipRole: "admin" });
    const [foreignCoverage] = await db.select().from(workforceCoverageRecordsTable).where(eq(workforceCoverageRecordsTable.shiftId, shifts[2].id));
    await request(app).post(`/implementation-a/workforce/coverage/${foreignCoverage.id}/evaluate`).set("Cookie", adminCookie).send({ shiftId: shifts[0].id, assignedCount: 0, requiredCount: 1, expectedVersion: 1 }).expect(404);
    await request(app).post("/implementation-a/workforce/assignments").set("Cookie", adminCookie).send({ shiftId: shifts[0].id, workerUserId: otherUser.id, operationId: randomUUID(), expectedVersion: 0 }).expect(404);
    const tripInput = { operationId: randomUUID(), owner: { type: "vendor", id: vendors[0].id }, driverUserId: otherUser.id, siteLocationId: sites[0].id, destinationSource: "confirmed" };
    await request(app).post("/implementation-a/trips").set("Cookie", adminCookie).send(tripInput).expect(403);
    const [foreignAsset] = await db.insert(assetsTable).values({ name: "Foreign synthetic truck", category: "fleet", legalOwnerName: "Synthetic", responsibleOrgType: "vendor", responsibleOrgId: vendors[1].id }).returning();
    await request(app).post("/implementation-a/trips").set("Cookie", adminCookie).send({ ...tripInput, driverUserId: user.id, vehicleAssetId: foreignAsset.id }).expect(403);
    await db.insert(ticketsTable).values(["cancelled", "denied", "funds_dispersed", "completed", "submitted", "approved", "awaiting_payment"].map(status => ({ vendorId: vendors[0].id, siteLocationId: sites[0].id, workTypeId: workType.id, fieldEmployeeId: worker.id, status, createdAt: new Date(Date.now() + 1000) })));
    const visible = JSON.parse(await runTool("lookup_open_tickets", {}, employee, ""));
    expect(visible.tickets.map((ticket: { id: number }) => ticket.id)).toEqual([tickets[0].id]);
    expect(JSON.parse(await runTool("lookup_open_tickets", {}, { userId: user.id, role: "field_employee", vendorId: vendors[0].id }, ""))).toHaveProperty("error");
    expect(JSON.parse(await runTool("lookup_user_progress", {}, { userId: user.id, role: "vendor", vendorId: vendors[0].id, membershipRole: "member" }, ""))).toHaveProperty("error");
    await db.update(siteLocationsTable).set({ isActive: false, status: "inactive" }).where(eq(siteLocationsTable.id, sites[0].id));
    await request(app).post("/safety/events").set("Cookie", ownerCookie).send({ eventType: "observation", title: "Synthetic stopped-site follow-up", siteLocationId: sites[0].id }).expect(201);
    await db.update(siteLocationsTable).set({ isActive: true, status: "active" }).where(eq(siteLocationsTable.id, sites[0].id));
  });
});
