import { createHash } from 'node:crypto';
import { z } from 'zod/v4';
import { proposeCalendarPlan, type CalendarCommitment } from './plan-execution-calendar-policy';
import type { PlanExecutionAuthorization } from './plan-execution';
import type { currentPlanExecutionAuthority } from './plan-execution-authorization';
import type { SessionPayload } from '../lib/session';
type Authority=Awaited<ReturnType<typeof currentPlanExecutionAuthority>>;
type ReadName='get_work_hub_calendar'|'get_work_hub_calendar_item'|'get_work_hub_meeting_catchup'|'find_work_hub_meeting_times';
type Dependencies={authorize:(authorization:PlanExecutionAuthorization)=>Promise<Authority>;execute:(name:ReadName,args:Record<string,unknown>,session:SessionPayload)=>Promise<unknown>;checkRead:(authority:Authority,name:ReadName)=>void|Promise<void>;now:()=>number};
const uuid=z.uuid(),utc=z.iso.datetime(),ids=z.array(uuid).max(20);
export const CalendarPlannerPreferencesSchema=z.object({planningTimezone:z.string().min(1).max(100),closeOfBusiness:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),moveOccurrenceIds:ids.min(1),mustKeepIds:ids,priorities:z.record(uuid,z.number().finite()),travelMinutes:z.record(uuid,z.number().int().min(0).max(1440)),dependencies:z.record(uuid,ids)}).strict();
const meetingSchema=z.object({id:uuid,title:z.string().min(1).max(500),agenda:z.string().nullable(),createdById:z.number().int().positive(),ownerOrgType:z.enum(['vendor','partner']),ownerOrgId:z.number().int().positive(),timezone:z.string().min(1).max(100)});
const occurrenceSchema=z.object({id:uuid,meetingId:uuid,startsAt:utc,endsAt:utc.nullable(),status:z.string()});
const itemSchema=z.object({meeting:meetingSchema,occurrence:occurrenceSchema});
const wrapperSchema=z.object({source:z.literal('vndrly'),authority:z.literal('work_hub_meeting'),item:itemSchema});
const shiftSchema=z.object({id:uuid,title:z.string().min(1).max(500),startsAt:utc,endsAt:utc,timezone:z.string().min(1).max(100),milestoneStatus:z.string(),version:z.number().int().positive(),ownerOrgType:z.enum(['vendor','partner']),ownerOrgId:z.number().int().positive()});
const catchupSchema=z.object({meeting:meetingSchema,occurrence:occurrenceSchema,userId:z.number().int().positive(),canManage:z.boolean(),participants:z.array(z.object({userId:z.number().int().positive(),removedAt:utc.nullable()})).min(1).max(100)});
const object=z.record(z.string(),z.unknown());
function fingerprint(value:unknown):string{return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
function boundary(now:number,timezone:string,clock:string){
 const formatter=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
 const parts=(at:number)=>Object.fromEntries(formatter.formatToParts(at).map(p=>[p.type,p.value]));const p=parts(now),date=new Date(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day)+1)).toISOString().slice(0,10),center=Date.parse(`${date}T${clock}:00Z`),found:number[]=[];
 for(let offset=-840;offset<=840;offset++){const at=center+offset*60000,q=parts(at);if(`${q.year}-${q.month}-${q.day}`===date&&`${q.hour}:${q.minute}`===clock)found.push(at);}if(found.length!==1)throw Error('Unambiguous local close-of-business deadline required');return new Date(found[0]!).toISOString();
}
/** Read-only planner. Fixed canonical tools supply all records/participants. No writes,
 * notification sends, RSVP interpretation, external calendar authority or manufactured CAS. */
export function createCanonicalCalendarPlanner(overrides:Partial<Dependencies>={}){
 const deps:Dependencies={authorize:async a=>(await import('./plan-execution-authorization')).currentPlanExecutionAuthority(a),execute:async(name,args,session)=>{const {runTool}=await import('../routes/assistant');return JSON.parse(await runTool(name,args,session,'',false,false));},checkRead:async(authority,name)=>{const {requireChatGptReadableTool}=await import('./chatgpt-tool-access');requireChatGptReadableTool(authority.session,authority.scopes,name);},now:Date.now,...overrides};
 return async(authorization:PlanExecutionAuthorization,supplied:unknown)=>{
  const prefs=CalendarPlannerPreferencesSchema.parse(supplied),now=deps.now(),start=new Date(now).toISOString(),end=boundary(now,prefs.planningTimezone,prefs.closeOfBusiness);
  const owner=/^(vendor|partner):([1-9]\d*)$/.exec(authorization.requester.organizationKey);if(!owner)throw Error('Operational company context required');
  const exactOwner=(meeting:z.infer<typeof meetingSchema>)=>{if(meeting.ownerOrgType!==owner[1]||meeting.ownerOrgId!==Number(owner[2]))throw Error('Calendar record belongs to another company');};
  async function read(name:ReadName,args:Record<string,unknown>){const authority=await deps.authorize(authorization);if(authority.session.role==='admin'||!authority.current.availableTools.includes(name))throw Error('Current scoped calendar read unavailable');await deps.checkRead(authority,name);const raw=await deps.execute(name,args,authority.session);const fresh=await deps.authorize(authorization);if(!fresh.current.availableTools.includes(name))throw Error('Calendar permission changed');await deps.checkRead(fresh,name);const result=object.parse(raw);if(result.error||result.ok===false)throw Error('Canonical calendar read failed');return result;}
  const calendar=await read('get_work_hub_calendar',{start,end});
  const meetings=z.array(wrapperSchema).max(20).parse(calendar.meetings),shifts=z.array(z.object({source:z.literal('vndrly'),authority:z.literal('work_hub_shift'),item:shiftSchema})).max(20).parse(calendar.shifts);
  z.array(z.unknown()).parse(calendar.tasks);const external=z.array(z.unknown()).parse(calendar.external);if(external.length)throw Error('External commitments require a supported canonical projection');
  if(meetings.some(w=>!['cancelled','ended','completed'].includes(w.item.occurrence.status)&&!w.item.occurrence.endsAt))throw Error('A current saved meeting has no bounded end time');
  const active=meetings.filter(w=>!['cancelled','ended','completed'].includes(w.item.occurrence.status)&&w.item.occurrence.endsAt&&Date.parse(w.item.occurrence.endsAt)>now),activeShifts=shifts.filter(w=>!['cancelled','completed'].includes(w.item.milestoneStatus)&&Date.parse(w.item.endsAt)>now);
  const visible=new Set([...active.map(w=>w.item.occurrence.id),...activeShifts.map(w=>w.item.id)]);
  const moved=new Set(prefs.moveOccurrenceIds),kept=new Set(prefs.mustKeepIds);
  if(moved.size!==prefs.moveOccurrenceIds.length||kept.size!==prefs.mustKeepIds.length||[...moved].some(id=>kept.has(id)||!active.some(w=>w.item.occurrence.id===id&&w.item.occurrence.status==='scheduled'))||[...kept].some(id=>!visible.has(id))||Object.keys(prefs.priorities).some(id=>!moved.has(id))||Object.keys(prefs.travelMinutes).some(id=>!visible.has(id))||Object.keys(prefs.dependencies).some(id=>!visible.has(id)))throw Error('Preferences must reference exact current saved scheduled occurrences');
  const commitments:CalendarCommitment[]=[],evidence:{kind:'meeting'|'shift';id:string;version:number|null;fingerprint:string;participantUserIds:number[]}[]=[],saved=new Map<string,z.infer<typeof itemSchema>>();
  for(const w of active){const occurrenceId=w.item.occurrence.id;exactOwner(w.item.meeting);if(w.item.occurrence.meetingId!==w.item.meeting.id)throw Error('Occurrence/meeting identity differs');
   const current=wrapperSchema.parse(await read('get_work_hub_calendar_item',{kind:'meeting',itemId:occurrenceId}));exactOwner(current.item.meeting);if(fingerprint(current.item)!==fingerprint(w.item))throw Error('Saved calendar changed during planning');
   const c:CalendarCommitment={occurrenceId,startsAt:current.item.occurrence.startsAt,endsAt:current.item.occurrence.endsAt!,timezone:current.item.meeting.timezone,mustKeep:!moved.has(occurrenceId),priority:moved.has(occurrenceId)?prefs.priorities[occurrenceId]??null:null,travelMinutes:prefs.travelMinutes[occurrenceId]??null,participantUserIds:[],dependencies:prefs.dependencies[occurrenceId]??[]};
   if(!c.mustKeep){const catchup=catchupSchema.parse(await read('get_work_hub_meeting_catchup',{occurrenceId}));exactOwner(catchup.meeting);if(catchup.userId!==authorization.requester.userId||!catchup.canManage||fingerprint(catchup.meeting)!==fingerprint(current.item.meeting)||fingerprint(catchup.occurrence)!==fingerprint(current.item.occurrence))throw Error('Current host authority or occurrence differs');
    c.participantUserIds=[...new Set(catchup.participants.filter(p=>p.removedAt===null).map(p=>p.userId))].sort((a,b)=>a-b);if(!c.participantUserIds.includes(authorization.requester.userId))throw Error('Current requester participant missing');
    const durationMinutes=(Date.parse(c.endsAt)-Date.parse(c.startsAt))/60000;if(!Number.isInteger(durationMinutes)||durationMinutes<5||durationMinutes>480)throw Error('Saved meeting duration unsupported');
    const slots=z.object({suggestions:z.array(z.object({startsAt:utc,endsAt:utc})).max(10),durationMinutes:z.literal(durationMinutes),timezone:z.literal(prefs.planningTimezone)}).parse(await read('find_work_hub_meeting_times',{participantUserIds:c.participantUserIds,searchStart:start,searchEnd:end,durationMinutes,timezone:prefs.planningTimezone,limit:10}));c.openings={source:'find_work_hub_meeting_times',participantUserIds:c.participantUserIds,slots:slots.suggestions};
   }commitments.push(c);saved.set(occurrenceId,current.item);evidence.push({kind:'meeting',id:occurrenceId,version:null,fingerprint:fingerprint({item:current.item,participantUserIds:c.participantUserIds}),participantUserIds:[...c.participantUserIds]});
  }
  for(const w of activeShifts){const i=w.item;if(i.ownerOrgType!==owner[1]||i.ownerOrgId!==Number(owner[2]))throw Error('Shift belongs to another context');commitments.push({occurrenceId:i.id,startsAt:i.startsAt,endsAt:i.endsAt,timezone:i.timezone,mustKeep:true,priority:null,travelMinutes:prefs.travelMinutes[i.id]??null,participantUserIds:[],dependencies:prefs.dependencies[i.id]??[]});evidence.push({kind:'shift',id:i.id,version:i.version,fingerprint:fingerprint(i),participantUserIds:[]});}
  const result=proposeCalendarPlan({now:start,planningTimezone:prefs.planningTimezone,closeOfBusiness:prefs.closeOfBusiness,commitments});
  for(const [occurrenceId,item] of saved){const current=wrapperSchema.parse(await read('get_work_hub_calendar_item',{kind:'meeting',itemId:occurrenceId}));if(fingerprint(current.item)!==fingerprint(item))throw Error('Calendar changed before returning proposals');if(moved.has(occurrenceId)){const fresh=catchupSchema.parse(await read('get_work_hub_meeting_catchup',{occurrenceId}));const participants=[...new Set(fresh.participants.filter(p=>p.removedAt===null).map(p=>p.userId))].sort((a,b)=>a-b);if(!fresh.canManage||fresh.userId!==authorization.requester.userId||fingerprint(fresh.meeting)!==fingerprint(item.meeting)||fingerprint(fresh.occurrence)!==fingerprint(item.occurrence)||JSON.stringify(participants)!==JSON.stringify(commitments.find(c=>c.occurrenceId===occurrenceId)!.participantUserIds))throw Error('Host authority or saved participants changed');}}
  for(const w of activeShifts){const current=z.object({source:z.literal('vndrly'),authority:z.literal('work_hub_shift'),item:shiftSchema}).parse(await read('get_work_hub_calendar_item',{kind:'shift',itemId:w.item.id}));if(fingerprint(current.item)!==fingerprint(w.item))throw Error('Immutable shift changed before returning proposals');}
  const authority=await deps.authorize(authorization);if(result.proposals.length&&!authority.current.availableTools.includes('manage_work_hub_meeting'))throw Error('Calendar preparation unavailable');
  return{...result,evidence,observedAt:start,limitations:[result.limitation,'Current recorded Work Hub meetings and shifts only; task due dates are not timed commitments. External calendars/travel facts are not discovered. No messages sent or invitation acceptance inferred. Meeting revisions do not exist; exact observation fingerprints require fresh preparation-time comparison.']};
 };
}
