import { describe, expect, it } from 'vitest';
import { proposeCalendarPlan, type CalendarPolicyInput } from './plan-execution-calendar-policy';
const id='11111111-1111-4111-8111-111111111111';
const base=():CalendarPolicyInput=>({now:'2026-10-07T14:00:00Z',planningTimezone:'America/Chicago',closeOfBusiness:'17:00',commitments:[{occurrenceId:id,startsAt:'2026-10-07T16:00:00Z',endsAt:'2026-10-07T17:00:00Z',timezone:'America/New_York',mustKeep:false,priority:1,travelMinutes:30,participantUserIds:[17,22],dependencies:[],openings:{source:'find_work_hub_meeting_times',participantUserIds:[17,22],slots:[{startsAt:'2026-10-08T16:00:00Z',endsAt:'2026-10-08T17:00:00Z'}]},contact:{channelId:id,body:'Can you confirm this proposed time?',invitationSaved:false,reply:'unknown',startsAt:'2026-10-08T16:00:00Z',endsAt:'2026-10-08T17:00:00Z'}}]});
describe('bounded calendar proposals',()=>{
 it('uses canonical openings, original timezone and occurrence ID without executing',()=>{const r=proposeCalendarPlan(base());expect(r.state).toBe('proposed');expect(r.deadline).toBe('2026-10-08T22:00:00.000Z');expect(r.executionStarted).toBe(false);expect(r.proposals[0]).toEqual({toolName:'manage_work_hub_meeting',arguments:{action:'reschedule',occurrenceId:id,payload:{startsAt:'2026-10-08T16:00:00Z',endsAt:'2026-10-08T17:00:00Z',timezone:'America/New_York'}}});expect(r.contacts[0]?.state).toBe('proposal');});
 it('preserves must-keep commitments and rejects overlapping travel buffers',()=>{const x=base();x.commitments.push({...x.commitments[0]!,occurrenceId:'22222222-2222-4222-8222-222222222222',mustKeep:true,startsAt:'2026-10-08T17:15:00Z',endsAt:'2026-10-08T18:00:00Z'});expect(proposeCalendarPlan(x).state).toBe('priority_order_no_slot');});
 it.each(['planningTimezone','closeOfBusiness'] as const)('requires explicit %s',key=>{const x=base();x[key]=null;expect(proposeCalendarPlan(x).state).toBe('needs_info');});
 it.each(['priority','travelMinutes'] as const)('requires explicit %s rather than guessing',key=>{const x=base();x.commitments[0]![key]=null;expect(proposeCalendarPlan(x).state).toBe('needs_info');});
 it('rejects slots for different participants and invalid dependency graphs',()=>{const x=base();x.commitments[0]!.openings!.participantUserIds=[17];expect(proposeCalendarPlan(x).state).toBe('needs_info');x.commitments[0]!.openings!.participantUserIds=[17,22];x.commitments[0]!.dependencies=[id];expect(proposeCalendarPlan(x).state).toBe('needs_info');});
 it('does not equate a saved invitation or message with acceptance',()=>{const x=base();x.commitments[0]!.contact!.invitationSaved=true;expect(proposeCalendarPlan(x).contacts[0]?.state).toBe('invitation_sent');x.commitments[0]!.contact!.reply='unanswered';expect(proposeCalendarPlan(x).contacts[0]?.state).toBe('unanswered');x.commitments[0]!.contact!.reply='accepted';expect(proposeCalendarPlan(x).contacts[0]?.state).toBe('accepted');});
 it('does not invent contact destinations and refuses after-deadline slots',()=>{const x=base();delete x.commitments[0]!.contact;expect(proposeCalendarPlan(x).proposals).toHaveLength(1);x.commitments[0]!.openings!.slots=[{startsAt:'2026-10-08T22:00:00Z',endsAt:'2026-10-08T23:00:00Z'}];expect(proposeCalendarPlan(x).state).toBe('priority_order_no_slot');});
 it('does not reuse acceptance of the old time for a proposed new time',()=>{const x=base();x.commitments[0]!.contact!.reply='accepted';x.commitments[0]!.contact!.startsAt=x.commitments[0]!.startsAt;expect(proposeCalendarPlan(x).contacts[0]?.state).toBe('proposal');expect(proposeCalendarPlan(x).proposals).toHaveLength(1);});
 it('uses tomorrow in the explicit local timezone across DST',()=>{const x=base();x.now='2026-10-31T23:00:00Z';x.commitments[0]!.openings!.slots=[{startsAt:'2026-11-01T16:00:00Z',endsAt:'2026-11-01T17:00:00Z'}];expect(proposeCalendarPlan(x).deadline).toBe('2026-11-01T23:00:00.000Z');});
 it('does not resend a saved invitation or unanswered request',()=>{const x=base();x.commitments[0]!.contact!.invitationSaved=true;for(const reply of ['unknown','unanswered','declined'] as const){x.commitments[0]!.contact!.reply=reply;expect(proposeCalendarPlan(x).proposals).toHaveLength(1);}});
 it('refuses malformed runtime contacts and overlapping immutable commitments',()=>{const x=base();x.commitments[0]!.contact!.invitationSaved='yes' as unknown as boolean;expect(proposeCalendarPlan(x).state).toBe('needs_info');const y=base();y.commitments[0]!.mustKeep=true;y.commitments.push({...y.commitments[0]!,occurrenceId:'22222222-2222-4222-8222-222222222222'});expect(proposeCalendarPlan(y).issues[0]).toContain('Overlapping immutable');});
 it('rejects unknown runtime shapes without crashing or proposing effects',()=>{for(const value of [null,{}, {now:'bad'}, {...base(),execute:true}]){const r=proposeCalendarPlan(value);expect(r.state).toBe('needs_info');expect(r.proposals).toEqual([]);}});
 it('orders a dependency before a higher priority dependent and honors travel',()=>{const x=base();const second={...x.commitments[0]!,occurrenceId:'22222222-2222-4222-8222-222222222222',priority:0,dependencies:[id],contact:undefined,openings:{...x.commitments[0]!.openings!,slots:[{startsAt:'2026-10-08T17:30:00Z',endsAt:'2026-10-08T18:30:00Z'}]}};x.commitments.push(second);const r=proposeCalendarPlan(x);expect(r.state).toBe('proposed');expect(r.proposals.filter(p=>p.toolName==='manage_work_hub_meeting').map(p=>p.arguments.occurrenceId)).toEqual([id,second.occurrenceId]);});
});
