import { expect, it, vi } from "vitest";
import { createPlanCalendarConfirmation } from "./plan-execution-calendar-confirmation";
import { calendarSnapshotFingerprint } from "../services/calendar-reschedule";
import type { PlanExecutionAuthorization } from "./plan-execution";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
function fixture(){
 const snapshot={occurrenceId:id(1),meetingId:id(2),ownerType:"vendor" as const,ownerId:4,title:"Meeting",agenda:null,timezone:"UTC",createdById:9,startsAt:"2026-10-07T10:00:00Z",endsAt:"2026-10-07T11:00:00Z",status:"scheduled",participantUserIds:[9,10]};
 const fingerprint=calendarSnapshotFingerprint(snapshot);
 const step={id:"confirm",adapter:"calendar_confirmation" as const,toolName:"query_work_hub_meeting_responses",operationId:id(3),dependsOn:[],arguments:{occurrenceId:id(1),expectedFingerprint:fingerprint,deadlineAt:"2026-10-07T09:10:00Z"}};
 const authorization:PlanExecutionAuthorization={id:id(4),requester:{userId:9,organizationKey:"vendor:4",membershipId:5,sessionVersion:1},grantReference:"private",taskId:id(5),taskVersion:1,planId:id(6),planVersion:1,planFingerprint:"a".repeat(64),approvedAt:Date.parse("2026-10-07T09:00:00Z"),expiresAt:Date.parse("2026-10-07T09:15:00Z"),maxAttempts:3,steps:[step],notificationOperationId:id(7)};
 const output={snapshot,fingerprint,actorUserId:9,canManage:true,responses:[9,10].map(userId=>({userId,response:"pending",recordedResponse:"pending",scheduleResponseVerified:false,recordedAt:null})),source:"saved_work_hub_participant_response",physicalAttendanceVerified:false,externalAttendeeAcceptanceVerified:false};
 const authorize=vi.fn(async()=>({session:{userId:9,role:"vendor",vendorId:4,activeMembershipId:5,sv:1},scopes:["work_hub:read"],current:{...authorization.requester,grantReference:"private",grantRevoked:false,taskId:id(5),taskVersion:1,planId:id(6),planVersion:1,planFingerprint:authorization.planFingerprint,availableTools:[step.toolName]}}));
 const request=vi.fn(async():Promise<unknown>=>output);let now=authorization.approvedAt;
 return {snapshot,step,authorization,output,authorize,request,advance:(v:number)=>{now=v;},run:createPlanCalendarConfirmation({authorize,request,now:()=>now})};
}
it("waits for current saved responses without accepting or sending anything",async()=>{const f=fixture();expect(await f.run(f.authorization,f.step,1)).toEqual({state:"waiting",retryAt:f.authorization.approvedAt+60_000});expect(f.request).toHaveBeenCalledWith(`/work-hub/calendar-response/${id(1)}/snapshot`,"GET",{},expect.anything());});
it("completes only actual verified same-schedule accepted responses",async()=>{const f=fixture();f.request.mockResolvedValue({...f.output,responses:f.output.responses.map(r=>({...r,response:"accepted",recordedResponse:"accepted",scheduleResponseVerified:true,recordedAt:"2026-10-07T09:01:00Z"}))});const r=await f.run(f.authorization,f.step,1);expect(r.state).toBe("completed");if(r.state==="completed")expect(JSON.parse(r.result.summary)).toMatchObject({outcome:"accepted",physicalAttendanceVerified:false,deliveryVerified:false});});
it("distinguishes declined, deadline and attempt exhaustion from confirmation",async()=>{for(const reason of ["declined","deadline_reached","attempts_exhausted"]){const f=fixture();if(reason==="declined")f.request.mockResolvedValue({...f.output,responses:f.output.responses.map(r=>({...r,response:"declined",recordedResponse:"declined",scheduleResponseVerified:true,recordedAt:"2026-10-07T09:01:00Z"}))});if(reason==="deadline_reached")f.advance(Date.parse(f.step.arguments.deadlineAt));const r=await f.run(f.authorization,f.step,reason==="attempts_exhausted"?3:1);expect(r.state).toBe("completed");if(r.state==="completed")expect(JSON.parse(r.result.summary).outcome).toBe(reason);}});
it("refuses schedule/participant changes, nonhost and postread scope removal",async()=>{const f=fixture();for(const result of [{...f.output,fingerprint:"b".repeat(64)},{...f.output,snapshot:{...f.snapshot,participantUserIds:[9]}},{...f.output,canManage:false}]){f.request.mockResolvedValueOnce(result);await expect(f.run(f.authorization,f.step,1)).rejects.toThrow();}const current=await f.authorize();f.authorize.mockResolvedValueOnce(current).mockResolvedValueOnce({...current,scopes:[]});await expect(f.run(f.authorization,f.step,1)).rejects.toThrow();});
it("refuses altered approved intent and legacy unverified acceptance stays waiting",async()=>{const f=fixture();await expect(f.run(f.authorization,{...f.step,arguments:{...f.step.arguments,expectedFingerprint:"b".repeat(64)}},1)).rejects.toThrow();f.request.mockResolvedValue({...f.output,responses:f.output.responses.map(r=>({...r,response:"unknown",recordedResponse:"accepted"}))});expect((await f.run(f.authorization,f.step,1)).state).toBe("waiting");});
it("refuses revoked originating grant after reading and deadline outside delegation",async()=>{const f=fixture(),current=await f.authorize();f.authorize.mockResolvedValueOnce(current).mockRejectedValueOnce(Error("Originating grant revoked"));await expect(f.run(f.authorization,f.step,1)).rejects.toThrow("revoked");const step={...f.step,arguments:{...f.step.arguments,deadlineAt:new Date(f.authorization.expiresAt+1).toISOString()}};await expect(f.run({...f.authorization,steps:[step]},step,1)).rejects.toThrow("bounds");});
