import { afterEach, expect, it, vi } from 'vitest';
import { createCanonicalPlanExecutionWorker, createPlanExecutionWorker } from './plan-execution-worker';
const wired=vi.hoisted(()=>({runOne:vi.fn(async()=>false),authorize:vi.fn(async()=>({current:{userId:17}})),api:{kind:'canonical'},notify:vi.fn(),repository:{kind:'durable'},adapters:{kind:'bounded'},createExecutor:vi.fn(),createAdapters:vi.fn(),createRepository:vi.fn(),createApi:vi.fn(),createNotifier:vi.fn()}));
vi.mock('./plan-execution',()=>({createPlanExecutor:wired.createExecutor}));
vi.mock('./plan-execution-adapters',()=>({createPlanExecutionAdapters:wired.createAdapters}));
vi.mock('./plan-execution-repository',()=>({createPrivatePlanExecutionRepository:wired.createRepository}));
vi.mock('./plan-execution-authorization',()=>({currentPlanExecutionAuthority:wired.authorize}));
vi.mock('./plan-execution-canonical',()=>({createPlanExecutionCanonicalApi:wired.createApi,createPlanExecutionSelfNotifier:wired.createNotifier}));
afterEach(()=>vi.unstubAllEnvs());

function fixture(){
 const ticks:Array<()=>void>=[];const cancels:Array<ReturnType<typeof vi.fn>>=[];
 const enabled=vi.fn(async()=>true),runOne=vi.fn(async()=>false),onError=vi.fn();
 const schedule=vi.fn((tick:()=>void,_ms:number)=>{ticks.push(tick);const cancel=vi.fn();cancels.push(cancel);return cancel;});
 const worker=createPlanExecutionWorker({enabled,runOne,onError,schedule});
 return {worker,enabled,runOne,onError,schedule,ticks,cancels};
}
it('does no work before explicit start and start creates only one timer',async()=>{const f=fixture();await f.worker.poll();expect(f.runOne).not.toHaveBeenCalled();f.worker.start();f.worker.start();await f.worker.poll();expect(f.schedule).toHaveBeenCalledTimes(1);expect(f.schedule.mock.calls[0][1]).toBe(5000);await f.worker.stop();expect(f.cancels[0]).toHaveBeenCalledTimes(1);});
it('does not overlap slow enabled checks or executor claims',async()=>{const f=fixture();let release!:()=>void;f.runOne.mockImplementationOnce(()=>new Promise(resolve=>{release=()=>resolve(false);}));f.worker.start();await vi.waitFor(()=>expect(f.runOne).toHaveBeenCalledTimes(1));f.ticks[0]();f.ticks[0]();await f.worker.poll();expect(f.runOne).toHaveBeenCalledTimes(1);release();await f.worker.stop();});
it('stops new claims and awaits the in-flight claim without inventing cancellation',async()=>{const f=fixture();let release!:()=>void;f.runOne.mockImplementationOnce(()=>new Promise(resolve=>{release=()=>resolve(true);}));f.worker.start();await vi.waitFor(()=>expect(f.runOne).toHaveBeenCalledTimes(1));const stopped=f.worker.stop();f.ticks[0]();let settled=false;void stopped.then(()=>{settled=true;});await Promise.resolve();expect(settled).toBe(false);release();await stopped;expect(f.runOne).toHaveBeenCalledTimes(1);await f.worker.poll();expect(f.runOne).toHaveBeenCalledTimes(1);});
it('fences queued callbacks from a prior generation after restart',async()=>{const f=fixture();f.worker.start();await f.worker.stop();const old=f.ticks[0];f.worker.start();await vi.waitFor(()=>expect(f.runOne).toHaveBeenCalledTimes(1));await f.worker.poll();const count=f.runOne.mock.calls.length;old();await Promise.resolve();expect(f.runOne).toHaveBeenCalledTimes(count);await f.worker.stop();});
it('fails closed on disabled or failed enablement without exposing private error text',async()=>{const f=fixture();f.enabled.mockResolvedValue(false);f.worker.start();await vi.waitFor(()=>expect(f.enabled).toHaveBeenCalled());await f.worker.poll();expect(f.runOne).not.toHaveBeenCalled();f.enabled.mockRejectedValue(Error('private credentials and grant data'));await f.worker.poll();expect(f.runOne).not.toHaveBeenCalled();expect(f.onError).toHaveBeenLastCalledWith({code:'plan_execution_worker_failed',stage:'enabled'});expect(JSON.stringify(f.onError.mock.calls)).not.toContain('private');await f.worker.stop();});
it('logs a safe bounded executor failure and can poll again',async()=>{const f=fixture();f.runOne.mockRejectedValueOnce(Error('private body'));f.worker.start();await vi.waitFor(()=>expect(f.onError).toHaveBeenCalled());expect(f.onError).toHaveBeenCalledWith({code:'plan_execution_worker_failed',stage:'run'});await f.worker.poll();expect(f.runOne).toHaveBeenCalledTimes(2);await f.worker.stop();});
it('limits draining per tick and rechecks enablement between claims',async()=>{const f=fixture();const worker=createPlanExecutionWorker({...f,enabled:f.enabled,runOne:f.runOne,onError:f.onError,schedule:f.schedule,maxRunsPerPoll:2});f.runOne.mockResolvedValue(true);worker.start();await vi.waitFor(()=>expect(f.runOne).toHaveBeenCalledTimes(2));await worker.stop();expect(f.enabled).toHaveBeenCalledTimes(2);});
it('rejects unbounded polling parameters and keeps logger failures contained',async()=>{for(const pollIntervalMs of [0,999,60001,Infinity])expect(()=>createPlanExecutionWorker({enabled:async()=>true,runOne:async()=>false,pollIntervalMs})).toThrow();for(const maxRunsPerPoll of [0,6,1.5])expect(()=>createPlanExecutionWorker({enabled:async()=>true,runOne:async()=>false,maxRunsPerPoll})).toThrow();const f=fixture();f.onError.mockImplementation(()=>{throw Error('logger unavailable');});f.enabled.mockRejectedValue(Error('deny'));f.worker.start();await f.worker.poll();await expect(f.worker.stop()).resolves.toBeUndefined();});
it('rechecks disabled state between bounded claims and refuses a late enablement result after stop',async()=>{const f=fixture();f.enabled.mockResolvedValueOnce(true).mockResolvedValue(false);f.runOne.mockResolvedValue(true);const worker=createPlanExecutionWorker({enabled:f.enabled,runOne:f.runOne,schedule:f.schedule,maxRunsPerPoll:5});worker.start();await vi.waitFor(()=>expect(f.enabled).toHaveBeenCalledTimes(2));expect(f.runOne).toHaveBeenCalledTimes(1);await worker.stop();const late=fixture();let release!:(v:boolean)=>void;late.enabled.mockImplementationOnce(()=>new Promise(resolve=>{release=resolve;}));late.worker.start();const done=late.worker.stop();release(true);await done;expect(late.runOne).not.toHaveBeenCalled();});
it('builds actual canonical dependencies lazily and stays disabled until explicit rollout',async()=>{
 wired.createExecutor.mockReturnValue({runOne:wired.runOne});wired.createAdapters.mockReturnValue(wired.adapters);wired.createRepository.mockReturnValue(wired.repository);wired.createApi.mockReturnValue(wired.api);wired.createNotifier.mockReturnValue(wired.notify);wired.runOne.mockClear();
 vi.stubEnv('ASSISTANT_PLAN_EXECUTION_ENABLED','0');const f=fixture();const worker=await createCanonicalPlanExecutionWorker({schedule:f.schedule});expect(wired.runOne).not.toHaveBeenCalled();const deps=wired.createExecutor.mock.calls.at(-1)![0];expect(deps.repository).toBe(wired.repository);expect(deps.adapters).toBe(wired.adapters);expect(deps.notify).toBe(wired.notify);expect(wired.createAdapters).toHaveBeenCalledWith(wired.api);expect(await deps.authorize({id:'approved'})).toEqual({userId:17});
 worker.start();await worker.stop();expect(wired.runOne).not.toHaveBeenCalled();vi.stubEnv('ASSISTANT_PLAN_EXECUTION_ENABLED','1');worker.start();await vi.waitFor(()=>expect(wired.runOne).toHaveBeenCalledTimes(1));await worker.stop();
});
