import { expect, it, vi } from 'vitest';
import { createPlanExecution, createPlanExecutor, type PlanExecutionRun, type PlanExecutionRepository } from './plan-execution';

const uuid = (n:number) => `00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const approved = () => ({ id:uuid(1), requester:{userId:17,organizationKey:'vendor:4',membershipId:12,sessionVersion:1}, grantReference:'private-grant-1', taskId:uuid(2),taskVersion:3,planId:uuid(3),planVersion:2,planFingerprint:'a'.repeat(64),approvedAt:1000,expiresAt:10000,maxAttempts:3,steps:[{id:'read',adapter:'authorized_read' as const,toolName:'query_asset_custody',arguments:{condition:'issued'},dependsOn:[],operationId:uuid(4)},{id:'draft',adapter:'personal_draft' as const,toolName:'manage_work_hub_task',arguments:{title:'Custody review'},dependsOn:['read'],operationId:uuid(5)}],notificationOperationId:uuid(6) });
function harness(){
 let now=2000, run=createPlanExecution(approved()), lease=0, held=false;
 const repository:PlanExecutionRepository={async claimNext(_now,until){if(held||['completed','blocked','cancelled'].includes(run.state))return null;held=true;lease++;return {run:structuredClone(run),fence:lease,leaseUntil:until};},async commit(claim,revision,next,time){if(claim.fence!==lease||time>=claim.leaseUntil||run.revision!==revision||run.cancelRequested)return false;run=structuredClone(next);return true;},async release(claim){if(claim.fence===lease)held=false;}};
 let current={...approved().requester,grantReference:approved().grantReference,grantRevoked:false,taskId:approved().taskId,taskVersion:3,planId:approved().planId,planVersion:2,planFingerprint:approved().planFingerprint,availableTools:['query_asset_custody','manage_work_hub_task']};
 const execute=vi.fn(async (_context:any,step:any)=>({operationId:step.operationId,sourceReferences:[step.id==='read'?'asset:21':'task:'+uuid(7)],summary:step.id==='read'?'One issued asset.':'Personal draft saved.'}));
 const reconcile=vi.fn(async()=>({state:'not_found' as const}));
 const notify=vi.fn(async(_authorization:any,_operationId:string,_brief:string)=>({saved:true as const,operationId:uuid(6)}));
 const deps={repository,now:()=>now,authorize:async()=>current,adapters:{authorized_read:{execute,reconcile},personal_draft:{execute,reconcile}},notify};
 return {deps,execute,reconcile,notify,get run(){return run;},set run(v:PlanExecutionRun){run=v;},current,advance:(n:number)=>{now=n;},restart:()=>{held=false;},cancel:()=>{run.cancelRequested=true;}};
}
it('executes exact dependent read/draft, persists source receipts and sends one deduplicated brief',async()=>{const h=harness();await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('completed');expect(h.execute).toHaveBeenCalledTimes(2);expect(h.notify).toHaveBeenCalledTimes(1);expect(h.run.steps.every(s=>s.state==='completed')).toBe(true);await createPlanExecutor(h.deps).runOne();expect(h.notify).toHaveBeenCalledTimes(1);});
it('reconciles a dropped committed write after restart without executing it again',async()=>{const h=harness();h.execute.mockImplementationOnce(async()=>({operationId:uuid(4),sourceReferences:['asset:21'],summary:'read'})).mockImplementationOnce(async()=>{throw Error('response dropped');});await createPlanExecutor(h.deps).runOne();expect(h.run.steps[1].state).toBe('outcome_unknown');h.reconcile.mockResolvedValue({state:'completed',result:{operationId:uuid(5),sourceReferences:['task:'+uuid(7)],summary:'saved'}} as any);h.restart();await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('completed');expect(h.execute).toHaveBeenCalledTimes(2);});
it.each(['grantRevoked','membershipId','sessionVersion','taskVersion','planFingerprint'])('stops on current %s change before execution',async field=>{const h=harness();(h.current as any)[field]=field==='grantRevoked'?true:field==='planFingerprint'?'b'.repeat(64):99;await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('blocked');expect(h.execute).not.toHaveBeenCalled();expect(h.notify).not.toHaveBeenCalled();});
it('refuses expired approval and explicit cancellation',async()=>{const h=harness();h.advance(10001);await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('blocked');expect(h.execute).not.toHaveBeenCalled();const c=harness();c.cancel();await createPlanExecutor(c.deps).runOne();expect(c.execute).not.toHaveBeenCalled();});
it('does not execute twice under concurrent worker claims',async()=>{const h=harness();await Promise.all([createPlanExecutor(h.deps).runOne(),createPlanExecutor(h.deps).runOne()]);expect(h.execute).toHaveBeenCalledTimes(2);});
it('refuses duplicate operations, cycles and unsupported money/device adapters',()=>{const a=approved();expect(()=>createPlanExecution({...a,steps:[a.steps[0],{...a.steps[1],operationId:a.steps[0].operationId}]})).toThrow();expect(()=>createPlanExecution({...a,steps:[{...a.steps[0],dependsOn:['draft']},a.steps[1]]})).toThrow();expect(()=>createPlanExecution({...a,steps:[{...a.steps[0],adapter:'money_transfer'}]})).toThrow();});
it('does not send brief twice after notification response is lost',async()=>{const h=harness();const saved=new Set<string>();h.notify.mockImplementation(async(_a:any,operation:any)=>{saved.add(operation);if(h.notify.mock.calls.length===1)throw Error('response dropped');return {saved:true as const,operationId:operation};});await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('outcome_unknown');h.restart();await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('completed');expect(saved.size).toBe(1);expect(h.notify.mock.calls[0][2]).toBe(h.notify.mock.calls[1][2]);expect(h.execute).toHaveBeenCalledTimes(2);});
it('halts dependent writes when revocation or cancellation happens after a read',async()=>{for(const cancellation of [false,true]){const h=harness();h.execute.mockImplementationOnce(async()=>{if(cancellation)h.cancel();else h.current.grantRevoked=true;return {operationId:uuid(4),sourceReferences:['asset:21'],summary:'read'};});await createPlanExecutor(h.deps).runOne();expect(h.execute).toHaveBeenCalledTimes(1);expect(h.notify).not.toHaveBeenCalled();expect(h.run.steps[1].state).toBe('pending');}});
it('does not publish a completion after lease expiration',async()=>{const h=harness();h.execute.mockImplementationOnce(async()=>{h.advance(70000);return {operationId:uuid(4),sourceReferences:['asset:21'],summary:'read'};});await createPlanExecutor(h.deps).runOne();expect(h.run.steps[0].state).toBe('running');expect(h.notify).not.toHaveBeenCalled();});
it('keeps a transient reconciliation error recoverable without resending the command',async()=>{const h=harness();h.execute.mockRejectedValueOnce(Error('dropped'));await createPlanExecutor(h.deps).runOne();h.reconcile.mockRejectedValueOnce(Error('read unavailable'));h.restart();await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('outcome_unknown');expect(h.execute).toHaveBeenCalledTimes(1);});
it('reconciles durable running state after crash and refuses unknown or exhausted retries',async()=>{const h=harness();h.run.steps[0].state='running';h.run.steps[0].attempts=1;h.reconcile.mockResolvedValueOnce({state:'unknown'} as any);await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('outcome_unknown');expect(h.execute).not.toHaveBeenCalled();h.run.steps[0].attempts=3;h.reconcile.mockResolvedValueOnce({state:'not_found'});h.restart();await createPlanExecutor(h.deps).runOne();expect(h.run.state).toBe('blocked');expect(h.execute).not.toHaveBeenCalled();});
it('refuses mutated private authorization instead of treating persisted tool names as approval',async()=>{const h=harness();h.run.authorization.steps[0].arguments={condition:'all'};await createPlanExecutor(h.deps).runOne();expect(h.execute).not.toHaveBeenCalled();expect(h.notify).not.toHaveBeenCalled();});
it('bounds repeated unknown reconciliation and notification attempts',async()=>{const h=harness();h.execute.mockRejectedValueOnce(Error('dropped'));await createPlanExecutor(h.deps).runOne();h.reconcile.mockResolvedValue({state:'unknown'} as any);for(let i=0;i<4;i++){h.restart();await createPlanExecutor(h.deps).runOne();}expect(h.reconcile).toHaveBeenCalledTimes(3);expect(h.run.state).toBe('blocked');expect(h.run.steps[0].state).toBe('outcome_unknown');const n=harness();n.notify.mockRejectedValue(Error('unknown'));for(let i=0;i<4;i++){n.restart();await createPlanExecutor(n.deps).runOne();}expect(n.notify).toHaveBeenCalledTimes(3);expect(n.run.state).toBe('blocked');});
