import {expect,it,vi} from "vitest";
import {createPlanAwayRead} from "./plan-execution-away-reads";
import type {PlanExecutionAuthorization,PlanExecutionStep} from "./plan-execution";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const step:PlanExecutionStep={id:"away",adapter:"authorized_read",toolName:"query_work_hub_away_channels",operationId:id(3),dependsOn:[],arguments:{}};
const authorization:PlanExecutionAuthorization={id:id(4),requester:{userId:9,organizationKey:"vendor:4",membershipId:5,sessionVersion:1},grantReference:"private",taskId:id(5),taskVersion:1,planId:id(6),planVersion:1,planFingerprint:"a".repeat(64),approvedAt:1,expiresAt:90000,maxAttempts:1,steps:[step],notificationOperationId:id(7)};
function fixture(){const authorize=vi.fn(async()=>({session:{userId:9,role:"vendor",vendorId:4,activeMembershipId:5,sv:1},scopes:["work_hub:read"],current:{...authorization.requester,grantReference:"private",grantRevoked:false,taskId:id(5),taskVersion:1,planId:id(6),planVersion:1,planFingerprint:authorization.planFingerprint,availableTools:[step.toolName]}}));const request=vi.fn(async():Promise<unknown>=>({channels:Array.from({length:21},(_,n)=>({id:id(100+n),name:`Channel ${n}`})),truncated:false,source:"joined_writable_channels"}));return{authorize,request,run:createPlanAwayRead({authorize,request})};}
it("retains actual bounded joined choices with explicit summary truncation and no message effect",async()=>{const f=fixture(),result=await f.run(authorization,step),summary=JSON.parse(result.summary);expect(summary.channels).toHaveLength(20);expect(summary.totalReturnedChannels).toBe(21);expect(summary.truncated).toBe(true);expect(f.authorize).toHaveBeenCalledTimes(2);expect(f.request).toHaveBeenCalledWith("/work-hub/away-responder/channels","GET",{},expect.objectContaining({userId:9}));});
it("bounds long channel labels without changing exact selected channel identities",async()=>{const f=fixture();f.request.mockResolvedValue({channels:Array.from({length:20},(_,n)=>({id:id(100+n),name:"x".repeat(10000)})),truncated:false,source:"joined_writable_channels"});const result=await f.run(authorization,step),summary=JSON.parse(result.summary);expect(result.summary.length).toBeLessThan(8000);expect(summary.channels[0]).toEqual({id:id(100),name:"x".repeat(40),nameTruncated:true});expect(summary.channels).toHaveLength(20);});
it("refuses read scope or tool removal after source retrieval",async()=>{for(const remove of ["scope","tool"]){const f=fixture(),current=await f.authorize();f.authorize.mockResolvedValueOnce(current).mockResolvedValueOnce(remove==="scope"?{...current,scopes:[]}:{...current,current:{...current.current,availableTools:[]}});await expect(f.run(authorization,step)).rejects.toThrow("unavailable");expect(f.request).toHaveBeenCalledTimes(1);}});
it("refuses altered approval, removed read consent and post-read revocation",async()=>{const f=fixture();await expect(f.run(authorization,{...step,arguments:{companyId:99}})).rejects.toThrow();const current=await f.authorize();f.authorize.mockResolvedValueOnce({...current,scopes:[]});await expect(f.run(authorization,step)).rejects.toThrow("unavailable");expect(f.request).not.toHaveBeenCalled();f.authorize.mockResolvedValueOnce(current).mockRejectedValueOnce(Error("revoked"));await expect(f.run(authorization,step)).rejects.toThrow("revoked");});
it("retains no-rule saved revision and refuses foreign rule identity",async()=>{const settings={...step,toolName:"query_work_hub_away_responder"},auth={...authorization,steps:[settings]},f=fixture(),current=await f.authorize();f.authorize.mockResolvedValue({...current,current:{...current.current,availableTools:[settings.toolName]}});f.request.mockResolvedValueOnce({rule:null,version:2,providerDeliveryVerified:false});expect(JSON.parse((await f.run(auth,settings)).summary)).toMatchObject({rule:null,version:2,providerDeliveryVerified:false});f.request.mockResolvedValueOnce({rule:{id:id(9),version:1,userId:99,owner:{type:"vendor",id:4},status:"active",startsAt:"2026-10-08T10:00:00Z",endsAt:"2026-10-09T10:00:00Z",replyText:"Away",channelIds:[id(10)],configuredAt:"2026-10-07T10:00:00Z",updatedAt:"2026-10-07T10:00:00Z"},version:1,providerDeliveryVerified:false});await expect(f.run(auth,settings)).rejects.toThrow("scope");});
