import { expect,it,vi } from 'vitest';
import { createCanonicalCalendarPlanner } from './plan-execution-calendar-planner';
const id='11111111-1111-4111-8111-111111111111',meetingId='22222222-2222-4222-8222-222222222222';
const authorization={requester:{userId:17,organizationKey:'vendor:609'}} as any;
const prefs={planningTimezone:'America/Chicago',closeOfBusiness:'17:00',moveOccurrenceIds:[id],mustKeepIds:[],priorities:{[id]:1},travelMinutes:{[id]:0},dependencies:{[id]:[]}};
function fixture(){const row={source:'vndrly',authority:'work_hub_meeting',item:{meeting:{id:meetingId,title:'Saved meeting',agenda:null,createdById:17,ownerOrgType:'vendor',ownerOrgId:609,timezone:'America/New_York'},occurrence:{id,meetingId,startsAt:'2026-10-07T16:00:00Z',endsAt:'2026-10-07T17:00:00Z',status:'scheduled'}}};const authorize=vi.fn(async()=>({session:{userId:17,role:'vendor',vendorId:609},scopes:['work_hub:read'],current:{availableTools:['get_work_hub_calendar','get_work_hub_calendar_item','get_work_hub_meeting_catchup','find_work_hub_meeting_times','manage_work_hub_meeting']}}));const execute=vi.fn<(name:string,args?:Record<string,unknown>,session?:unknown)=>Promise<any>>(async(name:string)=>name==='get_work_hub_calendar'?{shifts:[],tasks:[],meetings:[row],external:[]}:name==='get_work_hub_calendar_item'?row:name==='get_work_hub_meeting_catchup'?{...row.item,userId:17,canManage:true,participants:[{userId:17,removedAt:null},{userId:22,removedAt:null}]}:{suggestions:[{startsAt:'2026-10-08T16:00:00Z',endsAt:'2026-10-08T17:00:00Z'}],durationMinutes:60,timezone:'America/Chicago'});return{row,authorize,execute,planner:createCanonicalCalendarPlanner({authorize:authorize as any,execute,checkRead:()=>{},now:()=>Date.parse('2026-10-07T14:00:00Z')})};}
it('uses actual canonical participant reads and produces proposals without executing writes',async()=>{const f=fixture(),r=await f.planner(authorization,prefs);expect(r.state).toBe('proposed');expect(r.executionStarted).toBe(false);expect(f.execute.mock.calls.map(x=>x[0])).toEqual(['get_work_hub_calendar','get_work_hub_calendar_item','get_work_hub_meeting_catchup','find_work_hub_meeting_times','get_work_hub_calendar_item','get_work_hub_meeting_catchup']);expect((f.execute.mock.calls[3] as any)[1].participantUserIds).toEqual([17,22]);expect(r.evidence[0]?.version).toBe(null);expect(r.evidence[0]?.fingerprint).toMatch(/^[a-f0-9]{64}$/);expect(r.proposals[0]?.arguments.payload).toEqual({startsAt:'2026-10-08T16:00:00Z',endsAt:'2026-10-08T17:00:00Z',timezone:'America/New_York'});expect(f.authorize.mock.calls.length).toBeGreaterThanOrEqual(10);});
it('refuses invented caller participants or contacts',async()=>{const f=fixture();await expect(f.planner(authorization,{...prefs,participants:[99]})).rejects.toThrow();expect(f.execute).not.toHaveBeenCalled();});
it('refuses foreign context and parent meeting IDs',async()=>{const f=fixture();f.row.item.meeting.ownerOrgId=999;await expect(f.planner(authorization,prefs)).rejects.toThrow();const g=fixture();await expect(g.planner(authorization,{...prefs,moveOccurrenceIds:[meetingId]})).rejects.toThrow();});
it('refuses lost authority after reads and unavailable read tools',async()=>{const f=fixture();f.authorize.mockRejectedValueOnce(Error('revoked'));await expect(f.planner(authorization,prefs)).rejects.toThrow('revoked');expect(f.execute).not.toHaveBeenCalled();const g=fixture();g.authorize.mockImplementation(async()=>({session:{userId:17,role:'vendor',vendorId:609},scopes:[],current:{availableTools:[]}}));await expect(g.planner(authorization,prefs)).rejects.toThrow();});
it('refuses changed saved occurrence readback and nonhost calendar changes',async()=>{const f=fixture();let count=0;const original=f.execute.getMockImplementation()!;f.execute.mockImplementation(async name=>{const r=await original(name);if(name==='get_work_hub_calendar_item'&&++count===2)return{...f.row,item:{...f.row.item,occurrence:{...f.row.item.occurrence,status:'cancelled'}}};return r;});await expect(f.planner(authorization,prefs)).rejects.toThrow();const g=fixture();g.execute.mockImplementation(async name=>name==='get_work_hub_meeting_catchup'?{...g.row.item,userId:17,canManage:false,participants:[{userId:17,removedAt:null}]}:original(name));await expect(g.planner(authorization,prefs)).rejects.toThrow();});
it('rejects missing saved end times and changed participants without sending messages',async()=>{const f=fixture();f.row.item.occurrence.endsAt=null as any;await expect(f.planner(authorization,prefs)).rejects.toThrow('end time');const g=fixture(),original=g.execute.getMockImplementation()!;let reads=0;g.execute.mockImplementation(async name=>{const r=await original(name);if(name==='get_work_hub_meeting_catchup'&&++reads===2)return{...g.row.item,userId:17,canManage:true,participants:[{userId:17,removedAt:null}]};return r;});await expect(g.planner(authorization,prefs)).rejects.toThrow('participants changed');});
it('reads real immutable shift version/timezone and refuses changed shift readback',async()=>{const f=fixture(),original=f.execute.getMockImplementation()!,shift={id:meetingId,title:'Saved shift',startsAt:'2026-10-08T18:00:00Z',endsAt:'2026-10-08T19:00:00Z',timezone:'America/Denver',milestoneStatus:'upcoming',version:3,ownerOrgType:'vendor',ownerOrgId:609};f.execute.mockImplementation(async(name,...args:any[])=>{if(name==='get_work_hub_calendar')return{...await original(name),shifts:[{source:'vndrly',authority:'work_hub_shift',item:shift}]};if(name==='get_work_hub_calendar_item'&&args[0]?.kind==='shift')return{source:'vndrly',authority:'work_hub_shift',item:shift};return original(name);});const p={...prefs,travelMinutes:{...prefs.travelMinutes,[meetingId]:0}};expect((await f.planner(authorization,p)).evidence.find(e=>e.kind==='shift')?.version).toBe(3);f.execute.mockImplementation(async(name,...args:any[])=>name==='get_work_hub_calendar'?{...await original(name),shifts:[{source:'vndrly',authority:'work_hub_shift',item:shift}]}:name==='get_work_hub_calendar_item'&&args[0]?.kind==='shift'?{source:'vndrly',authority:'work_hub_shift',item:{...shift,version:4}}:original(name));await expect(f.planner(authorization,p)).rejects.toThrow('shift changed');});
