import {expect,it,vi} from "vitest";
import {createPlanAwayCommand} from "./plan-execution-away-command";
import {planExecutionAuthorizationSchema,type PlanExecutionAuthorization,type PlanExecutionStep} from "./plan-execution";
import {awayResponderCommandFingerprint} from "../services/work-hub-away-responder";
import {awayResponderRequest} from "./away-responder-tools";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const step:PlanExecutionStep={id:"away",adapter:"away_responder",toolName:"manage_work_hub_away_responder",operationId:id(3),dependsOn:[],arguments:{action:"configure",expectedVersion:0,startsAt:"2026-10-08T10:00:00Z",endsAt:"2026-10-09T10:00:00Z",replyText:"I am away.",channelIds:[id(9)]}};
const authorization:PlanExecutionAuthorization={id:id(4),requester:{userId:9,organizationKey:"vendor:4",membershipId:5,sessionVersion:1},grantReference:"private",taskId:id(5),taskVersion:1,planId:id(6),planVersion:1,planFingerprint:"a".repeat(64),approvedAt:1,expiresAt:90000,maxAttempts:1,steps:[step],notificationOperationId:id(7)};
function fixture(){const command=awayResponderRequest(step.arguments,step.operationId).body,actor={userId:9,owner:{type:"vendor" as const,id:4},membershipId:5,sessionVersion:1};const rule={id:id(8),version:1,userId:9,owner:actor.owner,status:"active",startsAt:step.arguments.startsAt,endsAt:step.arguments.endsAt,replyText:step.arguments.replyText,channelIds:[id(9)],configuredAt:"2026-10-07T10:00:00Z",updatedAt:"2026-10-07T10:00:00Z"};const receipt={operationId:step.operationId,fingerprint:awayResponderCommandFingerprint(command,actor),status:"configured",rule,savedAt:"2026-10-07T10:00:00Z",providerDeliveryVerified:false};const authorize=vi.fn(async()=>({session:{userId:9,role:"vendor",vendorId:4,activeMembershipId:5,sv:1},scopes:["work_hub:write"],current:{...authorization.requester,grantReference:"private",grantRevoked:false,taskId:id(5),taskVersion:1,planId:id(6),planVersion:1,planFingerprint:authorization.planFingerprint,availableTools:[step.toolName]}}));const request=vi.fn(async():Promise<unknown>=>receipt);return{receipt,authorize,request,run:createPlanAwayCommand({authorize,request})};}
it("executes exact approved rule and reconciles lost response via GET without another command",async()=>{const f=fixture();expect(planExecutionAuthorizationSchema.safeParse(authorization).success).toBe(true);f.request.mockRejectedValueOnce(Error("lost"));await expect(f.run(authorization,step,false)).rejects.toThrow("lost");f.request.mockResolvedValueOnce({receipt:f.receipt});expect((await f.run(authorization,step,true)).state).toBe("completed");expect(f.request.mock.calls.map(call=>call.slice(0,2))).toEqual([["/work-hub/away-responder","POST"],[`/work-hub/away-responder/operations/${step.operationId}`,"GET"]]);});
it("only explicit absent receipt permits retry and mismatched saved command stays unknown",async()=>{const f=fixture();f.request.mockResolvedValueOnce({receipt:null});expect(await f.run(authorization,step,true)).toEqual({state:"not_found"});f.request.mockResolvedValueOnce({...f.receipt,rule:{...f.receipt.rule,version:2}});expect(await f.run(authorization,step,false)).toEqual({state:"unknown"});});
it("executes only the exact approved pause or revoke revision and recovers its matching receipt",async()=>{for(const action of ["pause","revoke"] as const){const f=fixture(),control={...step,arguments:{action,expectedVersion:1,ruleId:id(8)}},auth={...authorization,steps:[control]},command=awayResponderRequest(control.arguments,control.operationId).body,status=action==="pause"?"paused":"revoked",receipt={...f.receipt,fingerprint:awayResponderCommandFingerprint(command,{userId:9,owner:{type:"vendor",id:4},membershipId:5,sessionVersion:1}),status,rule:{...f.receipt.rule,version:2,status}};f.request.mockResolvedValueOnce(receipt).mockResolvedValueOnce({receipt});expect((await f.run(auth,control,false)).state).toBe("completed");expect((await f.run(auth,control,true)).state).toBe("completed");}});
it("refuses altered approved input, model operation IDs and authority removed before or after",async()=>{const f=fixture();await expect(f.run(authorization,{...step,arguments:{...step.arguments,replyText:"Altered"}},false)).rejects.toThrow("not approved");expect(planExecutionAuthorizationSchema.safeParse({...authorization,steps:[{...step,arguments:{...step.arguments,operationId:id(99)}}]}).success).toBe(false);const current=await f.authorize();f.authorize.mockResolvedValueOnce({...current,scopes:[]});await expect(f.run(authorization,step,false)).rejects.toThrow("unavailable");expect(f.request).not.toHaveBeenCalled();f.authorize.mockResolvedValueOnce(current).mockResolvedValueOnce({...current,current:{...current.current,availableTools:[]}});await expect(f.run(authorization,step,false)).rejects.toThrow("unavailable");});
