import {expect,it,vi} from 'vitest';
import {createPlanExecutionCalendarHandler,PLAN_EXECUTION_CALENDAR_TOOL} from './plan-execution-calendar-chatgpt';
const id='11111111-1111-4111-8111-111111111111';
const input={reference:id,preferences:{planningTimezone:'America/Chicago',closeOfBusiness:'17:00',moveOccurrenceIds:[id],mustKeepIds:[],priorities:{[id]:1},travelMinutes:{[id]:0},dependencies:{[id]:[]}}};
const session={userId:17,role:'vendor',vendorId:609,activeMembershipId:12,sv:1} as any;
function fixture(){const authorization={id,requester:{userId:17,organizationKey:'vendor:609',membershipId:12,sessionVersion:1},grantReference:'private-grant'} as any;const status=vi.fn(async()=>({authorization} as any)),plan=vi.fn(async()=>({state:'proposed' as const,executionStarted:false as const,proposals:[],evidence:[],issues:[],deadline:null,limitation:'Bounded priority proposal',contacts:[],observedAt:'2026-10-07T14:00:00Z',limitations:[]})),available=vi.fn(()=>['list_work_hub_tasks','get_work_hub_calendar','get_work_hub_calendar_item','get_work_hub_meeting_catchup','find_work_hub_meeting_times','manage_work_hub_meeting']);return{authorization,status,plan,available,handle:createPlanExecutionCalendarHandler({enabled:()=>true,status,plan,available})};}
it('plans only exact current owner/grant stored authorization and returns no private binding',async()=>{const f=fixture();const r=await f.handle(input,session,['work_hub:read'],'private-grant');expect(f.plan).toHaveBeenCalledWith(f.authorization,input.preferences);expect(JSON.stringify(r)).not.toContain('private-grant');expect(r.calendarChangesSaved).toBe(false);expect(r.executionStarted).toBe(false);expect(PLAN_EXECUTION_CALENDAR_TOOL.annotations.readOnlyHint).toBe(true);});
it('fails closed when disabled, missing tools or changed grant without planner execution',async()=>{const f=fixture();f.available.mockReturnValue(['list_work_hub_tasks']);await expect(f.handle(input,session,[],'private-grant')).rejects.toThrow();expect(f.plan).not.toHaveBeenCalled();const g=fixture();await expect(g.handle(input,session,[],'other-grant')).rejects.toThrow();expect(g.plan).not.toHaveBeenCalled();const disabled=createPlanExecutionCalendarHandler({enabled:()=>false,status:g.status,plan:g.plan,available:g.available});await expect(disabled(input,session,[],'private-grant')).rejects.toThrow();expect(g.status).toHaveBeenCalledTimes(1);});
it('refuses stale membership/session/company and never falls back to metadata',async()=>{for(const change of [{userId:19},{vendorId:610},{activeMembershipId:13},{sv:2}]){const f=fixture();await expect(f.handle(input,{...session,...change},[],'private-grant')).rejects.toThrow();expect(f.plan).not.toHaveBeenCalled();}const f=fixture();f.status.mockRejectedValue(Error('current plan denied'));await expect(f.handle(input,session,[],'private-grant')).rejects.toThrow('current plan denied');});
it('rejects arbitrary contacts/preferences before status reads',async()=>{const f=fixture();await expect(f.handle({...input,preferences:{...input.preferences,contacts:[17]}},session,[],'private-grant')).rejects.toThrow();expect(f.status).not.toHaveBeenCalled();});
it('refuses cancelled delegation planning and rejects private fields in planner output',async()=>{const f=fixture();f.status.mockResolvedValue({authorization:f.authorization,cancelRequested:true,state:'cancelled'} as any);await expect(f.handle(input,session,[],'private-grant')).rejects.toThrow('no longer');expect(f.plan).not.toHaveBeenCalled();const g=fixture(),output=await g.plan();g.plan.mockResolvedValue({...output,grantReference:'private-grant'} as any);await expect(g.handle(input,session,[],'private-grant')).rejects.toThrow();});
