import {expect,it,vi} from 'vitest';
import {createQualifiedHotlistRead,qualifiedHotlistAvailable,QualifiedHotlistOutputSchema,type QualifiedHotlistSnapshot} from './qualified-hotlist-read';
const session={userId:17,role:'vendor',vendorId:609,activeMembershipId:12,membershipRole:'admin',sv:1} as any;
function snapshot():QualifiedHotlistSnapshot{return{vendor:{id:609,latitude:35,longitude:-97,operatingRadiusMiles:100,currentCatalogVersionId:2,coiDocumentUrl:'private',insuranceExpirationDate:'2027-01-01',federalTaxId:'private',wcExpirationDate:null,wcDocumentUrl:null,glExpirationDate:null,glDocumentUrl:null,autoLiabilityExpirationDate:null,autoLiabilityDocumentUrl:null,w9DocumentUrl:null},catalog:[{workTypeId:7}],hasQualifiedEmployee:true,jobs:[{id:10,partnerId:392,workTypeId:7,title:'Recorded service',latitude:35,longitude:-97,deadline:'2026-10-08',status:'open'}],relationships:[{partnerId:392,status:'approved',approvedCatalogVersionId:2}],eulaPartnerIds:[392]};}
function harness(s=snapshot()){const authorize=vi.fn(async()=>session),load=vi.fn(async()=>s),checkRead=vi.fn();return{authorize,load,read:createQualifiedHotlistRead({authorize,load,checkRead,now:()=>new Date('2026-10-07T12:00:00Z')})};}
it('matches exact service IDs and separates recorded checks from capacity and physical ability',async()=>{const h=harness(),r=await h.read({},session,['hotlist:read']);expect(r.opportunities[0]).toMatchObject({jobId:10,workTypeId:7,serviceMatch:'exact_vendor_catalog_work_type',eligibleRecordedOpportunity:true,capacity:'unknown',bidReady:false});expect(JSON.stringify(r)).not.toContain('private');expect(h.authorize).toHaveBeenCalledTimes(2);});
it('empty catalog and matching text never qualify unknown or different service IDs',async()=>{const s=snapshot();s.jobs[0]!.workTypeId=8;s.jobs[0]!.title='Exact catalog name';expect((await harness(s).read({},session,[])).opportunities).toEqual([]);s.catalog=[];s.jobs[0]!.workTypeId=7;expect((await harness(s).read({},session,[])).catalogState).toBe('empty');});
it('marks revoked relationships, expired compliance and out-of-radius matches as blocked',async()=>{for(const alter of [(s:QualifiedHotlistSnapshot)=>{s.relationships[0]!.status='revoked';},(s:QualifiedHotlistSnapshot)=>{s.vendor!.insuranceExpirationDate='2020-01-01';},(s:QualifiedHotlistSnapshot)=>{s.jobs[0]!.latitude=40;}]){const s=snapshot();alter(s);expect((await harness(s).read({},session,[])).opportunities[0]?.eligibleRecordedOpportunity).toBe(false);}});
it('keeps missing operating area and staff readiness explicit without invented GPS',async()=>{const s=snapshot();s.vendor!.latitude=null;s.hasQualifiedEmployee=false;const r=await harness(s).read({},session,[]);expect(r.opportunities[0]).toMatchObject({geography:'unknown',distanceMiles:null,eligibleRecordedOpportunity:false,capacity:'unknown'});});
it('refuses foreign account overrides, admin bypass and authority revoked during snapshot read',async()=>{const h=harness();await expect(h.read({vendorId:610},session,[])).rejects.toThrow();expect(h.load).not.toHaveBeenCalled();await expect(h.read({}, {...session,role:'admin'},[])).rejects.toThrow();const g=harness();g.authorize.mockRejectedValueOnce(Error('revoked'));await expect(g.read({},session,[])).rejects.toThrow('revoked');expect(g.load).not.toHaveBeenCalled();const k=harness();k.authorize.mockResolvedValueOnce(session).mockRejectedValueOnce(Error('revoked'));await expect(k.read({},session,[])).rejects.toThrow('revoked');});
it('pages actual scanned jobs and makes incomplete search explicit',async()=>{const s=snapshot();s.jobs.push({...s.jobs[0]!,id:11});const r=await harness(s).read({limit:1},session,[]);expect(r).toMatchObject({scannedJobCount:1,partial:true,nextCursor:10});expect(r.opportunities).toHaveLength(1);});

 it('normalizes legacy preferred approval while preserving lapse checks and unknown deadline refusal',async()=>{const s=snapshot();s.relationships[0]!.status='preferred';expect((await harness(s).read({},session,[])).opportunities[0]).toMatchObject({relationshipStatus:'preferred',derivedRelationshipStatus:'approved',eligibleRecordedOpportunity:true});s.hasQualifiedEmployee=false;expect((await harness(s).read({},session,[])).opportunities[0]?.eligibleRecordedOpportunity).toBe(false);s.hasQualifiedEmployee=true;s.jobs[0]!.deadline=null;expect((await harness(s).read({},session,[])).opportunities[0]).toMatchObject({deadlineState:'unknown',eligibleRecordedOpportunity:false});});

 it('requires actual Hotlist and catalog read consent and rejects private output extensions',async()=>{expect(qualifiedHotlistAvailable(session,[])).toBe(false);expect(qualifiedHotlistAvailable(session,['catalog:read'])).toBe(true);expect(qualifiedHotlistAvailable({...session,role:'admin'},['catalog:read','hotlist:read'])).toBe(false);const r=await harness().read({},session,[]);expect(()=>QualifiedHotlistOutputSchema.parse({...r,coiDocumentUrl:'private'})).toThrow();const load=vi.fn();await expect(createQualifiedHotlistRead({load})({},session,[])).rejects.toThrow();expect(load).not.toHaveBeenCalled();});
