import {z} from 'zod/v4';
import type {SessionPayload} from '../lib/session';
import {requireChatGptReadableTool} from './chatgpt-tool-access';
import {checkComplianceFloor} from '../lib/vendor-tier';
import {deriveStatus} from '../lib/approval-derivation';
import type {PartnerVendorRelationshipStatus} from '@workspace/db';
const positive=z.number().int().positive(),nullableText=z.string().nullable();
export const QualifiedHotlistInputSchema=z.object({limit:z.number().int().min(1).max(25).default(25),afterJobId:z.number().int().nonnegative().default(0)}).strict();
const vendorSchema=z.object({id:positive,latitude:z.number().min(-90).max(90).nullable(),longitude:z.number().min(-180).max(180).nullable(),operatingRadiusMiles:z.number().int().min(0).max(5000).nullable(),currentCatalogVersionId:positive.nullable(),coiDocumentUrl:nullableText,insuranceExpirationDate:nullableText,federalTaxId:nullableText,wcExpirationDate:nullableText,wcDocumentUrl:nullableText,glExpirationDate:nullableText,glDocumentUrl:nullableText,autoLiabilityExpirationDate:nullableText,autoLiabilityDocumentUrl:nullableText,w9DocumentUrl:nullableText});
const jobSchema=z.object({id:positive,partnerId:positive,workTypeId:positive.nullable(),title:z.string().max(500),latitude:z.number().min(-90).max(90).nullable(),longitude:z.number().min(-180).max(180).nullable(),deadline:nullableText,status:z.literal('open')});
const snapshotSchema=z.object({vendor:vendorSchema.nullable(),catalog:z.array(z.object({workTypeId:positive})),hasQualifiedEmployee:z.boolean(),jobs:z.array(jobSchema).max(26),relationships:z.array(z.object({partnerId:positive,status:z.enum(['preferred','approved','pending_review','auto_unapproved','revoked','unapproved']),approvedCatalogVersionId:positive.nullable()})),eulaPartnerIds:z.array(positive)});
export const QualifiedHotlistOutputSchema=z.object({vendorId:positive,observedAt:z.iso.datetime(),catalogState:z.enum(['recorded','empty']),catalogWorkTypeCount:z.number().int().nonnegative(),scannedJobCount:z.number().int().min(0).max(25),opportunities:z.array(z.object({jobId:positive,partnerId:positive,workTypeId:positive,title:z.string().max(500),serviceMatch:z.literal('exact_vendor_catalog_work_type'),relationshipStatus:z.enum(['preferred','approved','pending_review','auto_unapproved','revoked','unapproved','not_recorded']),derivedRelationshipStatus:z.enum(['approved','pending_review','auto_unapproved','revoked','unapproved','not_recorded']),relationshipBlocker:z.string().max(500).nullable(),complianceFloor:z.enum(['passed','blocked']),complianceBlocker:z.string().max(1000).nullable(),geography:z.enum(['unknown','within_radius','outside_radius']),distanceMiles:z.number().nonnegative().nullable(),deadline:nullableText,deadlineState:z.enum(['unknown','past','recorded_future_or_today']),currentCatalogEulaRecorded:z.boolean(),approvedCatalogMatchesCurrent:z.boolean(),eligibleRecordedOpportunity:z.boolean(),capacity:z.literal('unknown'),workerQualifications:z.literal('unknown'),bidReady:z.literal(false)}).strict()).max(25),partial:z.boolean(),nextCursor:positive.nullable(),bidPlaced:z.literal(false),physicalAbilityVerified:z.literal(false),limitations:z.array(z.string().max(1000)).max(10)}).strict();
export const QUALIFIED_HOTLIST_OUTPUT_SCHEMA={...z.toJSONSchema(QualifiedHotlistOutputSchema),type:'object' as const};
export function qualifiedHotlistAvailable(session:SessionPayload,scopes:string[]){try{if(session.role!=='vendor'||!session.vendorId||!session.userId||!session.activeMembershipId||!session.sv||!scopes.includes('catalog:read'))return false;requireChatGptReadableTool(session,scopes,'query_hotlist_jobs');return true;}catch{return false;}}
export type QualifiedHotlistSnapshot=z.infer<typeof snapshotSchema>;
type Input=z.infer<typeof QualifiedHotlistInputSchema>;
type Dependencies={authorize:(session:SessionPayload)=>Promise<SessionPayload>;checkRead:(session:SessionPayload,scopes:string[])=>void;load:(vendorId:number,input:Input)=>Promise<QualifiedHotlistSnapshot>;now:()=>Date};
async function loadSnapshot(vendorId:number,input:Input):Promise<QualifiedHotlistSnapshot>{
 const [{db,vendorsTable:v,vendorWorkTypesTable:c,hotlistJobsTable:j,partnerVendorRelationshipsTable:r,partnerEulaAcceptancesTable:e,vendorPeopleTable:p},{and,eq,gt,inArray,isNull,asc},{qualifiedVendorStaffCondition}]=await Promise.all([import('@workspace/db'),import('drizzle-orm'),import('../lib/vendor-qualified-staff')]);
 return db.transaction(async tx=>{
  const [vendor]=await tx.select({id:v.id,latitude:v.latitude,longitude:v.longitude,operatingRadiusMiles:v.operatingRadiusMiles,currentCatalogVersionId:v.currentCatalogVersionId,coiDocumentUrl:v.coiDocumentUrl,insuranceExpirationDate:v.insuranceExpirationDate,federalTaxId:v.federalTaxId,wcExpirationDate:v.wcExpirationDate,wcDocumentUrl:v.wcDocumentUrl,glExpirationDate:v.glExpirationDate,glDocumentUrl:v.glDocumentUrl,autoLiabilityExpirationDate:v.autoLiabilityExpirationDate,autoLiabilityDocumentUrl:v.autoLiabilityDocumentUrl,w9DocumentUrl:v.w9DocumentUrl}).from(v).where(eq(v.id,vendorId)).limit(1);
  if(!vendor)return{vendor:null,catalog:[],hasQualifiedEmployee:false,jobs:[],relationships:[],eulaPartnerIds:[]};
  const catalog=await tx.select({workTypeId:c.workTypeId}).from(c).where(eq(c.vendorId,vendorId));
  const staff=await tx.select({id:p.id}).from(p).where(qualifiedVendorStaffCondition(vendorId)).limit(1);
  const jobs=await tx.select({id:j.id,partnerId:j.partnerId,workTypeId:j.workTypeId,title:j.title,latitude:j.latitude,longitude:j.longitude,deadline:j.deadline,status:j.status}).from(j).where(and(eq(j.status,'open'),isNull(j.deletedAt),gt(j.id,input.afterJobId))).orderBy(asc(j.id)).limit(input.limit+1);
  const partnerIds=[...new Set(jobs.map(job=>job.partnerId))];
  const relationships=partnerIds.length?await tx.select({partnerId:r.partnerId,status:r.status,approvedCatalogVersionId:r.approvedCatalogVersionId}).from(r).where(and(eq(r.vendorId,vendorId),inArray(r.partnerId,partnerIds))):[];
  const accepted=partnerIds.length&&vendor.currentCatalogVersionId?await tx.selectDistinct({partnerId:e.partnerId}).from(e).where(and(eq(e.vendorId,vendorId),inArray(e.partnerId,partnerIds),eq(e.vendorCatalogVersionId,vendor.currentCatalogVersionId))):[];
  return snapshotSchema.parse({vendor,catalog,hasQualifiedEmployee:staff.length>0,jobs,relationships,eulaPartnerIds:accepted.map(row=>row.partnerId)});
 },{isolationLevel:'repeatable read',accessMode:'read only'});
}
function distanceMiles(a:number,b:number,c:number,d:number){const rad=(n:number)=>n*Math.PI/180,x=Math.sin(rad(c-a)/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(rad(d-b)/2)**2;return 2*3958.8*Math.asin(Math.sqrt(Math.min(1,x)));}
/** Scoped current vendor opportunity observations only. No bid, approval,
 * acceptance, compliance recompute, document disclosure or physical readiness claim. */
export function createQualifiedHotlistRead(overrides:Partial<Dependencies>={}){
 const deps:Dependencies={authorize:async session=>(await import('./chatgpt-grant-store')).validateAssistantSession(session),checkRead:asyncGuard,load:loadSnapshot,now:()=>new Date(),...overrides};
 return async(raw:unknown,session:SessionPayload,scopes:string[])=>{
  const input=QualifiedHotlistInputSchema.parse(raw);if(session.role!=='vendor'||!session.vendorId||!session.userId||!session.activeMembershipId||!session.sv)throw Error('Current operational vendor context required');deps.checkRead(session,scopes);
  const current=await deps.authorize(session);if(current.role!=='vendor'||current.vendorId!==session.vendorId||current.userId!==session.userId||current.activeMembershipId!==session.activeMembershipId||current.sv!==session.sv)throw Error('Vendor context changed');deps.checkRead(current,scopes);
  const snapshot=snapshotSchema.parse(await deps.load(current.vendorId!,input)),fresh=await deps.authorize(session);if(fresh.role!==current.role||fresh.vendorId!==current.vendorId||fresh.userId!==current.userId||fresh.activeMembershipId!==current.activeMembershipId||fresh.sv!==current.sv)throw Error('Vendor authority changed');deps.checkRead(fresh,scopes);
  const now=deps.now();if(!Number.isFinite(now.getTime()))throw Error('Invalid observation time');const vendor=snapshot.vendor;if(!vendor||vendor.id!==current.vendorId)throw Error('Current vendor record unavailable');
  const jobs=snapshot.jobs.slice(0,input.limit);if(jobs.some((j,index)=>j.id<=input.afterJobId||index>0&&j.id<=jobs[index-1]!.id))throw Error('Invalid canonical page ordering');
  const catalog=new Set(snapshot.catalog.map(row=>row.workTypeId)),floor=checkComplianceFloor(vendor,now),area=vendor.latitude!==null&&vendor.longitude!==null&&vendor.operatingRadiusMiles!==null;
  const opportunities=jobs.filter(job=>job.workTypeId!==null&&catalog.has(job.workTypeId)).map(job=>{
   const rel=snapshot.relationships.find(row=>row.partnerId===job.partnerId),derived=rel?deriveStatus({currentStatus:(rel.status==='preferred'?'approved':rel.status) as PartnerVendorRelationshipStatus,approvedCatalogVersionId:rel.approvedCatalogVersionId,vendorCurrentCatalogVersionId:vendor.currentCatalogVersionId,hasCurrentEulaAcceptance:snapshot.eulaPartnerIds.includes(job.partnerId),hasQualifiedEmployee:snapshot.hasQualifiedEmployee,compliance:{coiExpirationDate:vendor.insuranceExpirationDate,coiDocumentUrl:vendor.coiDocumentUrl,wcExpirationDate:vendor.wcExpirationDate,wcDocumentUrl:vendor.wcDocumentUrl,glExpirationDate:vendor.glExpirationDate,glDocumentUrl:vendor.glDocumentUrl,autoLiabilityExpirationDate:vendor.autoLiabilityExpirationDate,autoLiabilityDocumentUrl:vendor.autoLiabilityDocumentUrl,w9DocumentUrl:vendor.w9DocumentUrl},now}):null;
   const approved=derived?.status==='approved',distance=area&&job.latitude!==null&&job.longitude!==null?distanceMiles(vendor.latitude!,vendor.longitude!,job.latitude,job.longitude):null,geography=distance===null?'unknown':distance<=vendor.operatingRadiusMiles!?'within_radius':'outside_radius';
   const deadlineKnown=job.deadline!==null&&/^\d{4}-\d{2}-\d{2}$/.test(job.deadline)&&Number.isFinite(Date.parse(job.deadline))&&new Date(job.deadline).toISOString().slice(0,10)===job.deadline,deadlineState=!deadlineKnown?'unknown':Date.parse(`${job.deadline}T23:59:59.999Z`)<now.getTime()?'past':'recorded_future_or_today';
   return{jobId:job.id,partnerId:job.partnerId,workTypeId:job.workTypeId!,title:job.title,serviceMatch:'exact_vendor_catalog_work_type' as const,relationshipStatus:rel?.status??'not_recorded',derivedRelationshipStatus:derived?.status??'not_recorded',relationshipBlocker:derived?.reason??null,complianceFloor:floor.eligible?'passed':'blocked',complianceBlocker:floor.eligible?null:floor.reason,geography,distanceMiles:distance===null?null:Math.round(distance*10)/10,deadline:job.deadline,deadlineState,currentCatalogEulaRecorded:snapshot.eulaPartnerIds.includes(job.partnerId),approvedCatalogMatchesCurrent:vendor.currentCatalogVersionId!==null&&rel?.approvedCatalogVersionId===vendor.currentCatalogVersionId,eligibleRecordedOpportunity:approved&&floor.eligible&&geography==='within_radius'&&deadlineState==='recorded_future_or_today',capacity:'unknown' as const,workerQualifications:'unknown' as const,bidReady:false as const};
  });
  return QualifiedHotlistOutputSchema.parse({vendorId:vendor.id,observedAt:now.toISOString(),catalogState:catalog.size?'recorded':'empty',catalogWorkTypeCount:catalog.size,scannedJobCount:jobs.length,opportunities,partial:snapshot.jobs.length>input.limit,nextCursor:snapshot.jobs.length>input.limit?jobs.at(-1)!.id:null,bidPlaced:false as const,physicalAbilityVerified:false as const,limitations:['Only this page of open canonical marketplace jobs was checked. Empty catalog matches none; textual names never establish an exact service match.','Recorded relationship, compliance floor and radius checks do not establish capacity, worker qualifications, price agreement or physical ability. eligibleRecordedOpportunity is not bid-ready or approval to bid.','Catalog/EULA fields are observations only, not acceptance or a new approval. Current canonical bid and award endpoints retain their own checks; no bid, award or notification was created.','Job deadlines are date-only records; their timezone and operational flexibility are unverified.']});
 };
}
function asyncGuard(session:SessionPayload,scopes:string[]){if(!qualifiedHotlistAvailable(session,scopes))throw Error('Current vendor Hotlist and catalog read consent required');}
