import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { PngPillButton } from "@/components/png-pill-rollover";
import { nativeOperationErrorMessage, nativeOperationsRequest, nativeRequestEvidence, nativeRequestLabel, type NativeOperationRequest } from "@/lib/native-operations-client";

type Technical = { vendorId:number; contentIncluded:false; devices:Array<{id:string;deviceClass:string;revokedAt:string|null;updatedAt:string}>; diagnostics:Array<{payload:Record<string,unknown>;recordedAt:string}>; requests:Array<{id:string;kind:string;state:string;createdAt:string;expiresAt:string}> };
export default function NativeSupportConsole({identity}:{identity:string}) {
 const {i18n}=useTranslation(),language=i18n.language.startsWith("es")?"es":"en",c=(en:string,es:string)=>language==="es"?es:en;
 const [vendor,setVendor]=useState(""),[content,setContent]=useState<{request:NativeOperationRequest;grant:{purpose:string;expiresAt:string}}|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const revision=useRef(0);
 useEffect(()=>()=>{revision.current++;},[]);
 useEffect(()=>{if(!content)return;const expires=setTimeout(()=>setContent(null),Math.max(0,Date.parse(content.grant.expiresAt)-Date.now()));const current=revision.current;const timer=setInterval(()=>{void nativeOperationsRequest<{request:NativeOperationRequest;grant:{purpose:string;expiresAt:string}}>(`/support/vendors/${vendor}/requests/${content.request.id}`).then(value=>{if(revision.current===current)setContent(value);}).catch(()=>{if(revision.current===current)setContent(null);});},30000);return()=>{clearTimeout(expires);clearInterval(timer);};},[content,vendor]);
 const companies=useQuery({queryKey:["native-support-companies",identity],queryFn:async({signal})=>{const r=await fetch("/api/vendors",{credentials:"include",signal});if(!r.ok)throw Error(c("Companies unavailable","Empresas no disponibles"));const value=await r.json();if(!Array.isArray(value))throw Error(c("Companies unavailable","Empresas no disponibles"));return value as Array<{id:number;name:string}>;},retry:false});
 const technical=useQuery({queryKey:["native-support",identity,vendor],queryFn:({signal})=>nativeOperationsRequest<Technical>(`/support/vendors/${vendor}`,{signal}),enabled:!!vendor,retry:false});
 async function readContent(id:string){const current=++revision.current;setBusy(true);setError("");setContent(null);try{const result=await nativeOperationsRequest<{request:NativeOperationRequest;grant:{purpose:string;expiresAt:string}}>(`/support/vendors/${vendor}/requests/${id}`);if(revision.current===current)setContent(result);}catch(cause){if(revision.current===current)setError(nativeOperationErrorMessage(cause, language));}finally{if(revision.current===current)setBusy(false);}}
 return <section className="space-y-4 rounded-lg border p-4"><h2 className="text-lg font-semibold">{c("Native work support","Soporte de trabajo nativo")}</h2><p>{c("Technical status is available here. Work content requires a current company grant with a named purpose; each access is recorded.","Aquí está disponible el estado técnico. El contenido requiere autorización vigente de la empresa con un motivo; cada acceso queda registrado.")}</p>
 <label className="grid gap-2">{c("Company","Empresa")}<select className="rounded border bg-background p-2" value={vendor} onChange={event=>{revision.current++;setVendor(event.target.value);setContent(null);setError("");setBusy(false);}}><option value="">{c("Choose company","Elija empresa")}</option>{companies.data?.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
 {(error||technical.error||companies.error)&&<p role="alert">{error||nativeOperationErrorMessage(technical.error??companies.error, language)}</p>}
 {technical.data&&<><h3>{c("Devices","Dispositivos")}</h3><ul>{technical.data.devices.map(row=><li key={row.id}>{row.deviceClass} · {row.revokedAt?c("Revoked","Revocado"):c("Registered","Registrado")} · {new Date(row.updatedAt).toLocaleString()}</li>)}</ul><details><summary>{c("Permission and connection diagnostics","Diagnósticos de permisos y conexión")}</summary>{technical.data.diagnostics.map((row,index)=><pre className="overflow-auto whitespace-pre-wrap text-sm" key={index}>{JSON.stringify({recordedAt:row.recordedAt,...row.payload},null,2)}</pre>)}</details><h3>{c("Requests","Solicitudes")}</h3><ul>{technical.data.requests.map(row=><li className="flex flex-wrap items-center gap-3 border-b py-2" key={row.id}><span>{row.kind} · {nativeRequestLabel(row.state,language)} · {new Date(row.createdAt).toLocaleString()}</span><PngPillButton disabled={busy} onClick={()=>void readContent(row.id)}>{c("Read with company grant","Leer con autorización")}</PngPillButton></li>)}</ul><PngPillButton onClick={()=>{revision.current++;setContent(null);setBusy(false);void technical.refetch();}}>{c("Refresh","Actualizar")}</PngPillButton></>}
 {content&&Date.parse(content.grant.expiresAt)>Date.now()&&<section className="space-y-2 rounded border p-3"><p>{content.grant.purpose} · {c("Access ends","Acceso vence")}: {new Date(content.grant.expiresAt).toLocaleString()}</p><p>{content.request.purpose}</p>{nativeRequestEvidence(content.request,language).map((line,index)=><p key={index}>{line}</p>)}</section>}
 </section>;
}
