listening-port=3478
realm=vndrly.ai
server-name=rtc.vndrly.ai
fingerprint
lt-cred-mech
user=vndrly:__VNDRLY_TURN_SECRET__
min-port=49160
max-port=49200
no-cli
no-multicast-peers
stale-nonce=600
total-quota=1200
bps-capacity=0
log-file=stdout
simple-log
