CREATE TABLE IF NOT EXISTS "work_hub_meeting_replay_manifests" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "occurrence_id" uuid NOT NULL REFERENCES "work_hub_meeting_occurrences"("id"), "owner_org_type" text NOT NULL, "owner_org_id" integer NOT NULL, "recording_owner_user_id" integer NOT NULL REFERENCES "users"("id"), "recording_lease_generation" integer NOT NULL DEFAULT 0, "recording_lease_token_hash" varchar(64), "recording_lease_holder_user_id" integer REFERENCES "users"("id"), "recording_lease_issued_at" timestamptz, "recording_lease_expires_at" timestamptz, "meeting_started_at" timestamptz NOT NULL, "meeting_ended_at" timestamptz, "status" text NOT NULL DEFAULT 'recording', "schema_version" integer NOT NULL DEFAULT 2, "renderer_version" integer NOT NULL DEFAULT 1, "duration_ms" integer, "gap_markers" jsonb NOT NULL DEFAULT '[]'::jsonb, "audio_byte_count" bigint NOT NULL DEFAULT 0, "audio_chunk_count" integer NOT NULL DEFAULT 0, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "work_hub_meeting_replay_manifest_status_check" CHECK ("status" IN ('recording','finalized')), CONSTRAINT "work_hub_meeting_replay_manifest_values_check" CHECK ("schema_version" > 0 AND "renderer_version" > 0 AND "recording_lease_generation" >= 0 AND ("duration_ms" IS NULL OR "duration_ms" > 0) AND "audio_byte_count" >= 0 AND "audio_chunk_count" >= 0)
);
ALTER TABLE work_hub_meeting_replay_manifests ADD COLUMN IF NOT EXISTS "recording_lease_generation" integer NOT NULL DEFAULT 0;
ALTER TABLE work_hub_meeting_replay_manifests ADD COLUMN IF NOT EXISTS "recording_lease_token_hash" varchar(64);
ALTER TABLE work_hub_meeting_replay_manifests ADD COLUMN IF NOT EXISTS "recording_lease_holder_user_id" integer REFERENCES "users"("id");
ALTER TABLE work_hub_meeting_replay_manifests ADD COLUMN IF NOT EXISTS "recording_lease_issued_at" timestamptz;
ALTER TABLE work_hub_meeting_replay_manifests ADD COLUMN IF NOT EXISTS "recording_lease_expires_at" timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS "work_hub_meeting_replay_manifest_occurrence_unique" ON "work_hub_meeting_replay_manifests" ("occurrence_id");
CREATE INDEX IF NOT EXISTS "work_hub_meeting_replay_manifest_owner_idx" ON "work_hub_meeting_replay_manifests" ("owner_org_type", "owner_org_id", "created_at", "id");
CREATE TABLE IF NOT EXISTS "work_hub_meeting_replay_audio_chunks" (
  "id" uuid PRIMARY KEY, "manifest_id" uuid NOT NULL REFERENCES "work_hub_meeting_replay_manifests"("id"), "occurrence_id" uuid NOT NULL REFERENCES "work_hub_meeting_occurrences"("id"), "operation_id" uuid NOT NULL, "lease_generation" integer NOT NULL, "sequence" integer NOT NULL, "starts_at_ms" integer NOT NULL, "ends_at_ms" integer NOT NULL, "duration_ms" integer NOT NULL, "sample_rate" integer NOT NULL, "channel_count" integer NOT NULL, "bits_per_sample" integer NOT NULL, "sample_count" integer NOT NULL, "content_type" varchar(80) NOT NULL, "byte_size" integer NOT NULL, "sha256" varchar(64) NOT NULL, "storage_key" text NOT NULL, "state" text NOT NULL DEFAULT 'pending', "created_by_id" integer NOT NULL REFERENCES "users"("id"), "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "work_hub_meeting_replay_chunk_state_check" CHECK ("state" IN ('pending','ready','failed')), CONSTRAINT "work_hub_meeting_replay_chunk_values_check" CHECK ("sequence" >= 0 AND "starts_at_ms" >= 0 AND "ends_at_ms" > "starts_at_ms" AND "duration_ms" = "ends_at_ms" - "starts_at_ms" AND "sample_rate" >= 8000 AND "sample_rate" <= 48000 AND "channel_count" = 1 AND "bits_per_sample" = 16 AND "sample_count" > 0 AND "byte_size" > 0 AND "byte_size" <= 5242880 AND char_length("sha256") = 64)
);
ALTER TABLE work_hub_meeting_replay_audio_chunks ADD COLUMN IF NOT EXISTS "duration_ms" integer NOT NULL DEFAULT 1;
ALTER TABLE work_hub_meeting_replay_audio_chunks ADD COLUMN IF NOT EXISTS "sample_rate" integer NOT NULL DEFAULT 16000;
ALTER TABLE work_hub_meeting_replay_audio_chunks ADD COLUMN IF NOT EXISTS "channel_count" integer NOT NULL DEFAULT 1;
ALTER TABLE work_hub_meeting_replay_audio_chunks ADD COLUMN IF NOT EXISTS "bits_per_sample" integer NOT NULL DEFAULT 16;
ALTER TABLE work_hub_meeting_replay_audio_chunks ADD COLUMN IF NOT EXISTS "sample_count" integer NOT NULL DEFAULT 1;
ALTER TABLE work_hub_meeting_replay_audio_chunks ADD COLUMN IF NOT EXISTS "lease_generation" integer NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS "work_hub_meeting_replay_chunk_operation_unique" ON "work_hub_meeting_replay_audio_chunks" ("manifest_id", "operation_id");
CREATE UNIQUE INDEX IF NOT EXISTS "work_hub_meeting_replay_chunk_sequence_unique" ON "work_hub_meeting_replay_audio_chunks" ("manifest_id", "sequence");
CREATE INDEX IF NOT EXISTS "work_hub_meeting_replay_chunk_timeline_idx" ON "work_hub_meeting_replay_audio_chunks" ("manifest_id", "starts_at_ms", "id");
CREATE TABLE IF NOT EXISTS "work_hub_meeting_replay_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "manifest_id" uuid NOT NULL REFERENCES "work_hub_meeting_replay_manifests"("id"), "occurrence_id" uuid NOT NULL REFERENCES "work_hub_meeting_occurrences"("id"), "operation_id" uuid NOT NULL, "lease_generation" integer NOT NULL, "event_key" varchar(160) NOT NULL, "event_type" text NOT NULL, "offset_ms" integer NOT NULL, "end_offset_ms" integer, "source_id" uuid, "actor_user_id" integer REFERENCES "users"("id"), "payload" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_by_id" integer NOT NULL REFERENCES "users"("id"), "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "work_hub_meeting_replay_event_type_check" CHECK ("event_type" IN ('transcript','message','file','askv_answer','speaker','activity','gap')), CONSTRAINT "work_hub_meeting_replay_event_values_check" CHECK ("offset_ms" >= 0 AND ("end_offset_ms" IS NULL OR "end_offset_ms" >= "offset_ms"))
);
ALTER TABLE work_hub_meeting_replay_events ADD COLUMN IF NOT EXISTS "lease_generation" integer NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS "work_hub_meeting_replay_event_operation_unique" ON "work_hub_meeting_replay_events" ("manifest_id", "operation_id");
CREATE UNIQUE INDEX IF NOT EXISTS "work_hub_meeting_replay_event_key_unique" ON "work_hub_meeting_replay_events" ("manifest_id", "event_key");
CREATE INDEX IF NOT EXISTS "work_hub_meeting_replay_event_timeline_idx" ON "work_hub_meeting_replay_events" ("manifest_id", "offset_ms", "id");
CREATE TABLE IF NOT EXISTS "work_hub_meeting_replay_assignments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "occurrence_id" uuid NOT NULL REFERENCES "work_hub_meeting_occurrences"("id"), "assignee_user_id" integer NOT NULL REFERENCES "users"("id"), "assigned_by_id" integer NOT NULL REFERENCES "users"("id"), "requirement" text NOT NULL DEFAULT 'optional', "due_at" timestamptz, "status" text NOT NULL DEFAULT 'not_started', "watched_intervals" jsonb NOT NULL DEFAULT '[]'::jsonb, "watched_ms" integer NOT NULL DEFAULT 0, "last_position_ms" integer NOT NULL DEFAULT 0, "viewer_generation" integer NOT NULL DEFAULT 0, "viewer_token_hash" varchar(64), "viewer_issued_at" timestamptz, "viewer_expires_at" timestamptz, "viewer_observed_at" timestamptz, "completed_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "work_hub_meeting_replay_assignment_requirement_check" CHECK ("requirement" IN ('optional','required')), CONSTRAINT "work_hub_meeting_replay_assignment_status_check" CHECK ("status" IN ('not_started','in_progress','completed')), CONSTRAINT "work_hub_meeting_replay_assignment_values_check" CHECK ("watched_ms" >= 0 AND "last_position_ms" >= 0 AND "viewer_generation" >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS "work_hub_meeting_replay_assignment_unique" ON "work_hub_meeting_replay_assignments" ("occurrence_id", "assignee_user_id");
CREATE INDEX IF NOT EXISTS "work_hub_meeting_replay_assignment_assignee_idx" ON "work_hub_meeting_replay_assignments" ("assignee_user_id", "status", "due_at", "id");
