ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS calendar_type text NOT NULL DEFAULT 'company';
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS project_name text;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS milestone_status text NOT NULL DEFAULT 'upcoming';
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS percent_complete integer NOT NULL DEFAULT 0;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS shared_with_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS instructions text;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS dependency_title text;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS blockers text;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS owner_user_id integer REFERENCES users(id);
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS afe_code text;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS ticket_number text;
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS budget_amount numeric(14,2);
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS budget_used_amount numeric(14,2);
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS invoiced_amount numeric(14,2);
ALTER TABLE work_hub_shifts ADD COLUMN IF NOT EXISTS invoice_reference text;
