import {expect,it,vi} from "vitest";
import {createCalendarResponse,calendarResponseInputSchema,calendarResponseReceiptSchema} from "./calendar-response";
import {calendarSnapshotFingerprint,type CalendarSnapshot} from "./calendar-reschedule";
const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const saved:CalendarSnapshot={occurrenceId:uuid(1),meetingId:uuid(2),ownerType:"vendor",ownerId:4,title:"Meeting",agenda:null,timezone:"UTC",createdById:9,startsAt:"2026-10-07T10:00:00Z",endsAt:"2026-10-07T11:00:00Z",status:"scheduled",participantUserIds:[9,10]};
const input={operationId:uuid(3),occurrenceId:uuid(1),expectedFingerprint:calendarSnapshotFingerprint(saved),response:"accepted" as const};
function fixture(){let prior:unknown=null,snapshot=structuredClone(saved);const responses:{userId:number;response:"pending"|"accepted"|"declined"}[]=[{userId:9,response:"pending"},{userId:10,response:"declined"}];const authorize=vi.fn(async()=>({canManage:false})),save=vi.fn(async(receipt:unknown)=>{prior=receipt;responses[0].response=calendarResponseReceiptSchema.parse(receipt).response;});const service=createCalendarResponse({now:()=>new Date("2026-10-07T09:00:00Z"),transaction:async(_input,_actor,run)=>run({snapshot,prior,authorize,save,responses,responseReceipts:prior?[prior]:[]})});return{service,authorize,save,setSnapshot:(next:CalendarSnapshot)=>{snapshot=next;}};}
it("records only the authenticated actor and replays exact saved response without recording consent",async()=>{const f=fixture(),first=await f.service.execute(input,9);expect(first.receipt).toMatchObject({actorUserId:9,response:"accepted",recordingConsentGranted:false,physicalAttendanceVerified:false,externalAttendeeAcceptanceVerified:false});expect((await f.service.execute(input,9)).receipt).toEqual(first.receipt);expect((await f.service.readback(input,9)).receipt).toEqual(first.receipt);expect(f.save).toHaveBeenCalledTimes(1);await expect(f.service.execute({...input,response:"declined"},9)).rejects.toThrow("operation_conflict");});
it("refuses stale schedule/participants and terminal meetings",async()=>{for(const snapshot of [{...saved,startsAt:"2026-10-08T10:00:00Z"},{...saved,participantUserIds:[9,11]},{...saved,status:"ended"}]){const f=fixture();f.setSnapshot(snapshot);await expect(f.service.execute(input,9)).rejects.toThrow();expect(f.save).not.toHaveBeenCalled();}});
it("keeps absent readback effectless and refuses current revocation on prior receipt",async()=>{const f=fixture();expect(await f.service.readback(input,9)).toEqual({receipt:null,replayed:false});expect(f.save).not.toHaveBeenCalled();await f.service.execute(input,9);f.authorize.mockRejectedValue(Error("revoked"));await expect(f.service.readback(input,9)).rejects.toThrow("revoked");});
it("ordinary participant reads own response; legacy decisions do not prove acceptance of current schedule",async()=>{const f=fixture();expect((await f.service.inspect(uuid(1),9)).responses).toEqual([{userId:9,response:"pending",recordedResponse:"pending",scheduleResponseVerified:false,recordedAt:null}]);f.authorize.mockResolvedValue({canManage:true});expect((await f.service.inspect(uuid(1),9)).responses[1]).toMatchObject({userId:10,response:"unknown",recordedResponse:"declined",scheduleResponseVerified:false});expect(f.save).not.toHaveBeenCalled();
 await f.service.execute(input,9);expect((await f.service.inspect(uuid(1),9)).responses[0]).toMatchObject({response:"accepted",scheduleResponseVerified:true});
 f.setSnapshot({...saved,startsAt:"2026-10-08T10:00:00Z"});expect((await f.service.inspect(uuid(1),9)).responses[0]).toMatchObject({response:"unknown",recordedResponse:"accepted",scheduleResponseVerified:false});});
it("rejects caller identities and unrelated recording/media consent",()=>{for(const raw of [{...input,userId:10},{...input,recordingConsentGranted:true},{...input,response:"pending"}])expect(calendarResponseInputSchema.safeParse(raw).success).toBe(false);});
