import {describe,it,expect,vi,beforeEach} from "vitest";
const state=vi.hoisted(()=>({saved:null as any,count:0,authorized:true,enabled:true}));
vi.mock("./native-operations",()=>({withLiveNativeTicketAssignment:async(_s:unknown,_id:number,apply:any)=>{if(!state.authorized)throw Error("assignment revoked");return apply({query:async(sql:string,values:any[])=>{if(sql.startsWith("SELECT native_operations_policy"))return {rows:[{native_operations_policy:{enabled:state.enabled}}]};if(sql.startsWith("SELECT tool_output"))return {rows:state.saved?[{tool_output:state.saved}]:[]};if(sql.startsWith("INSERT")){state.saved=JSON.parse(values[5]);state.count++;}return {rows:[]};}});}}));
vi.mock("../lib/objectStore",()=>({getObjectStore:()=>({getUploadDescriptor:()=>({uploadURL:"/first",objectPath:"/objects/uploads/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"})}),renewObjectUploadDescriptor:(objectPath:string)=>({objectPath,uploadURL:"/renewed"})}));
import {prepareNativeTicketPhotoUpload} from "./native-ticket-photo-upload";
const session={userId:9,vendorId:3,role:"field_employee" as const},input={operationId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",contentType:"image/jpeg",byteSize:100,checksumSha256:"a".repeat(64)};
beforeEach(()=>Object.assign(state,{saved:null,count:0,authorized:true,enabled:true}));
describe("native generic photo upload identity",()=>{
 it("renews the same file/path once and rejects content or actor substitution",async()=>{const first=await prepareNativeTicketPhotoUpload(session,20,input);const second=await prepareNativeTicketPhotoUpload(session,20,input);expect(second.objectPath).toBe(first.objectPath);expect(second.uploadURL).toBe("/renewed");expect(state.count).toBe(1);await expect(prepareNativeTicketPhotoUpload(session,20,{...input,byteSize:101})).rejects.toThrow("native.upload_content_conflict");await expect(prepareNativeTicketPhotoUpload({...session,userId:10},20,input)).rejects.toThrow("native.upload_content_conflict");});
 it("rechecks revoked assignment and company opt-out even on renewal",async()=>{await prepareNativeTicketPhotoUpload(session,20,input);state.authorized=false;await expect(prepareNativeTicketPhotoUpload(session,20,input)).rejects.toThrow("assignment revoked");state.authorized=true;state.enabled=false;await expect(prepareNativeTicketPhotoUpload(session,20,input)).rejects.toThrow("native.company_opted_out");expect(state.count).toBe(1);});
});
