import { ArrowRight, BarChart3, CalendarClock, MapPinned, MessageSquareText, ShieldCheck } from "lucide-react";
import { PngPillButton } from "@/components/png-pill-rollover";
import { MARKETING_MODULES, marketingCtaHref } from "@/lib/marketing-content";
import { VNDRLY_LOGO_SQUARE } from "@/lib/vndrly-brand-assets";
import PublicAskV from "@/components/public-askv";

const motifs = [MapPinned, MessageSquareText, CalendarClock, BarChart3];
export default function MarketingHome() {
  return <main className="min-h-screen bg-background text-foreground" data-testid="marketing-home">
    <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><nav aria-label="Public navigation" className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><a href="/" className="flex items-center gap-2 font-bold"><img src={VNDRLY_LOGO_SQUARE} alt="VNDRLY" className="h-9 w-9"/>VNDRLY</a><div className="flex items-center gap-3"><a href="#modules" className="hidden text-sm font-medium sm:inline">Explore modules</a><a href="/login" className="rounded-md px-3 py-2 text-sm font-semibold outline-none ring-offset-2 focus-visible:ring-2 focus-visible:ring-[var(--brand-primary)]">Sign in</a></div></nav></header>
    <section className="relative overflow-hidden border-b"><div className="absolute inset-0 opacity-10 [background-image:radial-gradient(circle_at_1px_1px,var(--brand-primary)_1px,transparent_0)] [background-size:24px_24px]"/><div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-20 lg:grid-cols-[1.15fr_.85fr] lg:py-28"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-[var(--brand-primary)]">Field operations, connected</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-tight sm:text-6xl">Run the field, the office, and every handoff from one operational system.</h1><p className="mt-6 max-w-2xl text-lg text-muted-foreground">VNDRLY connects sites, crews, vendors, tickets, access, collaboration, reporting, and mobile execution—so the work and its context move together.</p><div className="mt-8 flex flex-wrap gap-3"><a href={marketingCtaHref}><PngPillButton>Sign up today <ArrowRight className="ml-2 h-4 w-4"/></PngPillButton></a><a href="mailto:support@vndrly.ai?subject=VNDRLY%20demo%20request" className="inline-flex min-h-11 items-center rounded-full border px-5 font-semibold focus-visible:ring-2 focus-visible:ring-[var(--brand-primary)]">Request a demo</a></div></div><div aria-label="Abstract connected operations illustration" className="grid grid-cols-2 gap-4 self-center">{motifs.map((Icon, index) => <div key={index} className="aspect-square rounded-2xl border bg-card p-6 shadow-sm"><Icon className="h-10 w-10 text-[var(--brand-primary)]"/><div className="mt-8 h-2 rounded bg-muted"/><div className="mt-3 h-2 w-2/3 rounded bg-muted"/></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--brand-primary)]">The operational problem</p><h2 className="mt-2 text-3xl font-black">Calls, texts, spreadsheets, paper gate logs, schedules, and accounting handoffs rarely tell the same story.</h2><p className="mt-4 text-lg text-muted-foreground">When each handoff lives in a different tool, teams spend time reconstructing context and responsibility. VNDRLY keeps the job path connected from request through field work, review, and payment.</p></div><div className="mt-10 grid gap-8 md:grid-cols-3"><div><ShieldCheck className="h-6 w-6 text-[var(--brand-primary)]"/><h3 className="mt-3 text-xl font-bold">Context stays attached</h3><p className="mt-2 text-muted-foreground">Operational records, conversations, files, and decisions remain connected to the organizations and work they belong to.</p></div><div><CalendarClock className="h-6 w-6 text-[var(--brand-primary)]"/><h3 className="mt-3 text-xl font-bold">Fewer handoff gaps</h3><p className="mt-2 text-muted-foreground">Shared status, scheduling, and accountability help field and office teams act from the same picture.</p></div><div><MapPinned className="h-6 w-6 text-[var(--brand-primary)]"/><h3 className="mt-3 text-xl font-bold">Built for real operations</h3><p className="mt-2 text-muted-foreground">Role-aware web and mobile experiences support partners, vendors, admins, foremen, and field employees.</p></div></div></section>
    <section className="border-y bg-card"><div className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-3xl font-black">See your part of the operation.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Partners","Request, monitor, review, and approve work across sites."],["Vendor admins","Manage services, assignments, people, tickets, and billing context."],["Office teams","Coordinate schedules, documentation, notifications, and reporting."],["Foremen","See crews, schedules, safety context, communications, and field progress."],["Field employees","Use mobile workflows for assigned work, location phases, and completion."],["Gate admins","Manage authorized arrivals, visitors, site access, and gate history."]].map(([role,value]) => <div key={role} className="rounded-xl border bg-background p-5"><h3 className="font-bold">{role}</h3><p className="mt-2 text-sm text-muted-foreground">{value}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16"><h2 className="text-3xl font-black">One connected job path.</h2><ol aria-label="VNDRLY job workflow" className="mt-8 grid gap-3 md:grid-cols-5">{["Partner request","Vendor assignment","Crew field completion","Review & approval","Payment workflow"].map((step,index) => <li key={step} className="relative rounded-xl border bg-card p-5 motion-safe:animate-[pulse_3s_ease-in-out_infinite]" style={{ animationDelay: `${index * 180}ms` }}><span className="text-xs font-black text-[var(--brand-primary)]">0{index + 1}</span><p className="mt-2 font-bold">{step}</p></li>)}</ol></section>
    <section id="modules" className="border-y bg-muted/25"><div className="mx-auto max-w-7xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--brand-primary)]">Connected workflow</p><h2 className="mt-2 text-3xl font-black">A broad platform, joined by the work.</h2><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{MARKETING_MODULES.map((module) => <article key={module.title} className="flex flex-col rounded-xl border bg-card p-6"><h3 className="text-lg font-bold">{module.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">{module.description}</p><a href={module.ctaHref} className="mt-5 inline-flex min-h-11 items-center font-bold text-[var(--brand-primary)] underline-offset-4 hover:underline focus-visible:ring-2 focus-visible:ring-[var(--brand-primary)]" data-testid="module-signup-cta">Sign up today <ArrowRight className="ml-2 h-4 w-4"/></a></article>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 py-16 lg:grid-cols-2"><div><h2 className="text-3xl font-black">Connected instead of reconstructed.</h2><div className="mt-6 overflow-hidden rounded-xl border"><div className="grid grid-cols-2 bg-muted px-4 py-3 font-bold"><span>Disconnected tools</span><span>VNDRLY workflow</span></div>{[["Status split across calls and sheets","Shared ticket and lifecycle context"],["Paper or isolated entry logs","Gate and visitor history tied to sites"],["Files detached from decisions","Files, notes, tasks, and approvals in context"],["Accounting rebuilt after the fact","Operational records flow toward billing and reporting"]].map((row) => <div key={row[0]} className="grid grid-cols-2 gap-4 border-t px-4 py-4 text-sm"><span className="text-muted-foreground">{row[0]}</span><span>{row[1]}</span></div>)}</div></div><div><h2 className="text-3xl font-black">Trust is part of the workflow.</h2><ul className="mt-6 space-y-4 text-muted-foreground"><li><strong className="text-foreground">Role and organization permissions</strong> govern authenticated access.</li><li><strong className="text-foreground">GPS accountability</strong> supports field lifecycle visibility when authorized and consented.</li><li><strong className="text-foreground">Tenant isolation</strong> keeps organization-owned records within their authorized context.</li><li><strong className="text-foreground">Audit history and data controls</strong> support accountable changes, retention, and access decisions.</li></ul></div></section>
    <section className="border-y bg-card"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 lg:grid-cols-2"><div><h2 className="text-3xl font-black">What happens after signup?</h2><ol className="mt-6 space-y-4"><li><strong>1. Choose your role.</strong> Start the partner or vendor registration path.</li><li><strong>2. Provide organization details.</strong> Enter only the information needed for setup and review.</li><li><strong>3. Complete onboarding.</strong> Configure your organization, people, services, and operational context as applicable.</li><li><strong>4. Begin connected work.</strong> Use the modules available to your role and organization.</li></ol><a href={marketingCtaHref} className="mt-7 inline-flex min-h-11 items-center font-bold text-[var(--brand-primary)] underline">Sign up today <ArrowRight className="ml-2 h-4 w-4"/></a></div><div><h2 className="text-3xl font-black">Frequently asked questions</h2><div className="mt-4 divide-y">{[["Is VNDRLY only for field employees?","No. VNDRLY provides role-aware experiences for partner, vendor, office, field, foreman, gate, and platform administration work."],["Does public AskV see my account?","No. Public AskV only answers from curated public product information. Sign in for authenticated workflows."],["Are audio recording and Microsoft 365 always active?","No. These are optional capabilities and remain unavailable until they are configured and enabled."],["Can I request a demo here?","Yes. The demo link opens your email client so you control what is sent; the website does not silently collect a lead."]].map(([q,a]) => <details key={q} className="py-4"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-2 text-sm text-muted-foreground">{a}</p></details>)}</div></div></div></section>
    <section className="mx-auto max-w-4xl px-4 py-20 text-center"><h2 className="text-3xl font-black">Make the next handoff the easiest one.</h2><p className="mx-auto mt-3 max-w-2xl text-muted-foreground">Start with the VNDRLY role that fits your organization, or talk through the workflow with us.</p><div className="mt-7 flex justify-center gap-3"><a href={marketingCtaHref}><PngPillButton>Sign up today</PngPillButton></a><a href="mailto:support@vndrly.ai" className="inline-flex min-h-11 items-center px-4 font-semibold">Contact</a></div></section>
    <footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} VNDRLY</span><div className="flex flex-wrap gap-5"><a href="/legal/privacy">Privacy</a><a href="/legal/terms">Terms</a><a href="mailto:support@vndrly.ai">Support</a><a href="mailto:support@vndrly.ai">Contact</a></div></div></footer>
    <PublicAskV />
  </main>;
}
