import type { Response } from "express";

/**
 * `Loose<T>` widens primitive literal types — string-literal unions like
 * `"draft" | "approved"`, number-literal unions, and literal `true` / `false`
 * — back to their base primitive while preserving object/array structure.
 *
 * It exists so we can compare a Drizzle SELECT row type (which returns
 * plain `string` for an enum column and plain `number` for a numeric
 * column) against the `z.output<typeof Schema>` type of an OpenAPI
 * response schema (which narrows enums to literal unions). We do not
 * want the type bridge to fail on every enum mismatch — Drizzle simply
 * doesn't carry enum narrowness — but we DO want a missing column in the
 * SELECT projection to be a TypeScript error, which is what this type
 * preserves.
 *
 * `Date` is treated as a leaf (not recursed into), so date columns line
 * up with `z.coerce.date()` and don't get walked as a structural object.
 */
export type Loose<T> =
  T extends Date ? Date
    : T extends Array<infer U> ? Array<Loose<U>>
    : T extends ReadonlyArray<infer U> ? ReadonlyArray<Loose<U>>
    : T extends string ? string
    : T extends number ? number
    : T extends boolean ? boolean
    : T extends bigint ? bigint
    : T extends null ? null
    : T extends undefined ? undefined
    : T extends object ? { [K in keyof T]: Loose<T[K]> }
    : T;

/**
 * Schema-version-agnostic shape that captures the only two things this
 * helper needs: a runtime `parse()` and a way to extract the inferred
 * output type. Zod v3 stores it on `_output`; zod v4 puts it on
 * `_zod.output`. The route layer in this repo currently mixes both
 * (orval-generated schemas in `lib/api-zod/src/generated/api.ts` are
 * zod v3, the hand-written schemas in `lib/api-zod/src/custom.ts` are
 * zod v4) so the bridge has to accept either.
 */
export type AnyResponseSchema =
  | { parse: (data: unknown) => unknown; readonly _output: unknown }
  | { parse: (data: unknown) => unknown; readonly _zod: { readonly output: unknown } };

export type SchemaOutput<S> =
  S extends { readonly _output: infer O } ? O
    : S extends { readonly _zod: { readonly output: infer O } } ? O
    : never;

/**
 * Send a JSON body that is checked at compile time against a Zod
 * response schema.
 *
 * The `body` argument must structurally match the schema's inferred
 * output type (with primitive types widened by `Loose<T>` so Drizzle's
 * plain `string` for enum columns is accepted). When a route's
 * `db.select({ ... })` projection is missing a column the schema
 * declares as required, the `body` argument will not type-check —
 * turning what was previously a runtime 500 (caught only after deploy)
 * into a build-time error.
 *
 * `.parse()` is still invoked at runtime as a final safety net, both to
 * apply zod coercions (e.g. `z.coerce.date()`) and to reject any value
 * that slipped past the type system (e.g. raw db rows produced via
 * `sql<unknown>` casts).
 *
 * Use this helper for new code and for hot routes whose response shape
 * is generated by orval into `lib/api-zod`. See
 * `artifacts/api-server/src/routes/tickets.ts` (`/portal/:siteCode`,
 * `GET /tickets`, `GET /tickets/:id`) for reference call sites.
 */
export function sendResponse<S extends AnyResponseSchema>(
  res: Response,
  schema: S,
  body: Loose<SchemaOutput<NoInfer<S>>>,
): void {
  res.json(schema.parse(body));
}

/**
 * Like {@link sendResponse} but sets a non-200 status (typically 201 for
 * creation endpoints) before sending the JSON body.
 */
export function sendResponseStatus<S extends AnyResponseSchema>(
  res: Response,
  status: number,
  schema: S,
  body: Loose<SchemaOutput<NoInfer<S>>>,
): void {
  res.status(status).json(schema.parse(body));
}

/**
 * Compile-time only assertion that a value satisfies the loose-output
 * shape of a schema. Useful in places that already build a structured
 * object literal but do not call {@link sendResponse} (e.g. a helper
 * that returns the body to a caller). Returns the value unchanged.
 */
export function assertResponseShape<S extends AnyResponseSchema>(
  _schema: S,
  body: Loose<SchemaOutput<NoInfer<S>>>,
): Loose<SchemaOutput<NoInfer<S>>> {
  return body;
}
