import React from 'react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import en from '@/lib/locales/en.json';
const env=vi.hoisted(()=>({api:vi.fn(),generation:1,listeners:[] as (()=>void)[],user:{id:17,role:'vendor',vendorId:4}}));
vi.mock('@/lib/api',()=>({apiFetch:env.api}));
vi.mock('@/lib/auth',()=>({getUser:async()=>env.user,captureAuthScope:()=>({generation:env.generation}),isAuthScopeCurrent:(s:any)=>s.generation===env.generation,subscribeUser:(f:()=>void)=>{env.listeners.push(f);return()=>{}},subscribeToken:()=>()=>{}}));
vi.mock('@/hooks/useColors',()=>({useColors:()=>({text:'#fff',mutedForeground:'#aaa',border:'#444'})}));
vi.mock('@/components/TogglePillButton',()=>({default:({children,onPress,disabled,accessibilityLabel}:any)=><button disabled={disabled} onClick={onPress} aria-label={accessibilityLabel}>{children}</button>}));
vi.mock('react-native',()=>({View:({children}:any)=><div>{children}</div>,Text:({children}:any)=><span>{children}</span>,TextInput:({onChangeText,accessibilityLabel,value,editable}:any)=><input aria-label={accessibilityLabel} disabled={editable===false} value={value} onChange={e=>onChangeText(e.target.value)}/>}));
vi.mock('react-i18next',()=>({useTranslation:()=>({t:(key:string)=>key.split('.').reduce((v:any,k)=>v?.[k],en)??key})}));
vi.mock('@/lib/native-uuid',()=>({nativeUuid:()=>crypto.randomUUID()}));
import {InventoryRecovery} from './InventoryRecovery';
const assetId='11111111-1111-4111-8111-111111111111';
const detail={id:assetId,version:4,holderUserId:17,lastCustody:{holderDisplayName:'Recorded driver',holderUserId:17,recordedAt:'2026-10-07T12:00:00Z'},gpsTag:{status:'not_connected',location:null}};
const props={assetId,owner:{type:'vendor' as const,id:4},canManage:false,onRefresh:vi.fn()};
beforeEach(()=>{env.api.mockReset();env.generation=1;env.listeners=[];props.onRefresh.mockReset()});afterEach(cleanup);
async function open(){fireEvent.click(screen.getByRole('button',{name:'Inventory recovery and identifier review'}));await screen.findByText('Recorded driver');}
describe('native Inventory recovery',()=>{
 it('records own-holder loss with exact reviewed request and no physical loss claim',async()=>{
  env.api.mockImplementation(async(path:string,init:any)=>init?.method==='POST'?{assetId,...JSON.parse(init.body),version:5,status:'applied',holderUserId:17,reportedAt:'2026-10-07T12:00:00Z',physicalLossVerified:false}:detail);
  render(<InventoryRecovery {...props}/>);await open();fireEvent.click(screen.getByRole('button',{name:'Report missing'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Unable to locate recorded equipment'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByText('Canonical record saved.');
  const call=env.api.mock.calls.find(c=>c[1]?.method==='POST')!;expect(call[0]).toBe(`/api/implementation-a/assets/${assetId}/loss-report`);expect(JSON.parse(call[1].body)).toMatchObject({expectedVersion:4,condition:'missing',confirmed:true});expect(props.onRefresh).toHaveBeenCalledOnce();
 });
 it('retains exact UUID/version/body after unknown result and refuses substituted receipt',async()=>{
  let count=0;env.api.mockImplementation(async(_path:string,init:any)=>{if(init?.method==='POST'){if(++count===1)throw Error('network lost');return {assetId:'other',...JSON.parse(init.body),version:5,status:'applied',physicalLossVerified:false}}return detail});
  render(<InventoryRecovery {...props}/>);await open();fireEvent.click(screen.getByRole('button',{name:'Report stolen'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Reported stolen'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByRole('button',{name:'Retry exact request'});fireEvent.click(screen.getByRole('button',{name:'Retry exact request'}));await waitFor(()=>expect(count).toBe(2));const calls=env.api.mock.calls.filter(c=>c[1]?.method==='POST');expect(calls[0][1].body).toBe(calls[1][1].body);expect(props.onRefresh).not.toHaveBeenCalled();
 });
 it('clears current records and pending review after account invalidation',async()=>{
  env.api.mockResolvedValue(detail);render(<InventoryRecovery {...props}/>);await open();fireEvent.click(screen.getByRole('button',{name:'Report missing'}));env.generation++;env.listeners.forEach(f=>f());await waitFor(()=>expect(screen.queryByLabelText('Reason')).toBeNull());expect(screen.queryByText('Recorded driver')).toBeNull();
 });
 it('uses exact manager claim and saved claim receipt without exposing another owner',async()=>{
  env.api.mockImplementation(async(path:string,init:any)=>{if(init?.method==='POST'){const b=JSON.parse(init.body);return {id:b.claimId,assetId,operationId:b.operationId,version:1,status:'pending_review',alias:b.alias,ownershipTransferred:false,otherOwnerDisclosed:false}}return path.endsWith('/identifier-claims')?{claims:[],incoming:[],truncated:false,incomingTruncated:false}:detail;});
  render(<InventoryRecovery {...props} canManage/>);await open();fireEvent.click(screen.getByRole('button',{name:'Request identifier review'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Serial collision needs mediation'}});fireEvent.change(screen.getByLabelText('Identifier'),{target:{value:'SYNTHETIC-SERIAL-1'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByText('Canonical record saved.');const call=env.api.mock.calls.find(c=>c[1]?.method==='POST')!;expect(JSON.parse(call[1].body)).toMatchObject({expectedVersion:4,alias:{kind:'serial',value:'SYNTHETIC-SERIAL-1'},confirmed:true});expect(screen.queryByText('Platform identifier review queue')).toBeNull();
 });
 it('does not expose loss controls for another holder or claim controls without manager authority',async()=>{
  env.api.mockResolvedValue({...detail,holderUserId:19});render(<InventoryRecovery {...props}/>);await open();expect(screen.queryByRole('button',{name:'Report missing'})).toBeNull();expect(screen.queryByRole('button',{name:'Request identifier review'})).toBeNull();
 });
});
it('responds to own requested evidence using the exact claim revision and retries the immutable explanation',async()=>{
 const claimId='22222222-2222-4222-8222-222222222222',claim={id:claimId,assetId,version:2,status:'awaiting_evidence',requesterActions:['respond','withdraw'],alias:{kind:'serial',value:'Recorded serial'},operationId:crypto.randomUUID(),reason:'Initial',reviewReason:'Explain the registration',ownershipTransferred:false,otherOwnerDisclosed:false};
 let count=0;env.api.mockImplementation(async(path:string,init:any)=>{if(init?.method==='POST'){const body=JSON.parse(init.body);if(++count===1)throw Error('lost response');return {...claim,operationId:body.operationId,status:'pending_review',version:3,responseReason:body.reason,respondedAt:'2026-10-07T13:00:00Z',physicalEvidenceVerified:false};}return path.endsWith('/identifier-claims')?{claims:[claim],incoming:[{...claim,id:'33333333-3333-4333-8333-333333333333',assetId,requesterDisclosed:false}],truncated:false}:detail;});
 render(<InventoryRecovery {...props} canManage/>);await open();const buttons=await screen.findAllByRole('button',{name:'Respond to evidence request'});expect(buttons).toHaveLength(1);expect(screen.getByText('Mediator request: Explain the registration')).toBeTruthy();expect(screen.getAllByRole('button',{name:'Withdraw identifier claim'})).toHaveLength(1);
 fireEvent.click(buttons[0]);fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Actual requester explanation'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));expect(screen.getByText('Text only; no uploaded evidence or ownership verification is claimed.',{exact:false})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByRole('button',{name:'Retry exact request'});fireEvent.click(screen.getByRole('button',{name:'Retry exact request'}));await screen.findByText('Canonical record saved.');
 const calls=env.api.mock.calls.filter(c=>c[1]?.method==='POST');expect(calls).toHaveLength(2);expect(calls[0][0]).toBe(`/api/implementation-a/assets/${assetId}/identifier-claims/${claimId}/respond`);expect(calls[0][1].body).toBe(calls[1][1].body);expect(JSON.parse(calls[0][1].body)).toMatchObject({expectedVersion:2,reason:'Actual requester explanation',confirmed:true});
});
it('withdraws an open own claim without changing custody, and terminal claims offer no continuation',async()=>{
 const claimId='22222222-2222-4222-8222-222222222222',claim={id:claimId,assetId,version:5,status:'pending_review',requesterActions:['withdraw'],alias:{kind:'serial',value:'Recorded serial'},ownershipTransferred:false,otherOwnerDisclosed:false};
 env.api.mockImplementation(async(path:string,init:any)=>{if(init?.method==='POST'){const body=JSON.parse(init.body);return {...claim,operationId:body.operationId,status:'withdrawn',version:6,responseReason:body.reason,withdrawnAt:'2026-10-07T13:00:00Z',physicalEvidenceVerified:false};}return path.endsWith('/identifier-claims')?{claims:[claim,{...claim,id:'33333333-3333-4333-8333-333333333333',status:'withdrawn',requesterActions:[]}],incoming:[],truncated:false}:detail;});
 render(<InventoryRecovery {...props} canManage/>);await open();await screen.findByRole('button',{name:'Withdraw identifier claim'});expect(screen.queryByRole('button',{name:'Respond to evidence request'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Withdraw identifier claim'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'I withdraw this exact claim'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByText('Canonical record saved.');const call=env.api.mock.calls.find(c=>c[1]?.method==='POST')!;expect(call[0]).toBe(`/api/implementation-a/assets/${assetId}/identifier-claims/${claimId}/withdraw`);expect(JSON.parse(call[1].body)).toMatchObject({expectedVersion:5});
});
it('reloads the saved own claim before withdrawal and uses its current revision',async()=>{
 const claimId='22222222-2222-4222-8222-222222222222';let claim:any={id:claimId,assetId,version:2,status:'awaiting_evidence',requesterActions:['respond','withdraw'],alias:{kind:'serial',value:'Exact serial'},ownershipTransferred:false,otherOwnerDisclosed:false};
 env.api.mockImplementation(async(path:string,init:any)=>{if(init?.method==='POST'){const body=JSON.parse(init.body),respond=path.endsWith('/respond');claim={...claim,operationId:body.operationId,version:body.expectedVersion+1,status:respond?'pending_review':'withdrawn',requesterActions:respond?['withdraw']:[],responseReason:body.reason,physicalEvidenceVerified:false,[respond?'respondedAt':'withdrawnAt']:'2026-10-07T13:00:00Z'};return claim;}return path.endsWith('/identifier-claims')?{claims:[claim],incoming:[],truncated:false}:detail;});
 render(<InventoryRecovery {...props} canManage/>);await open();fireEvent.click(await screen.findByRole('button',{name:'Respond to evidence request'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Actual explanation'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByText('Canonical record saved.');await waitFor(()=>expect(screen.queryByRole('button',{name:'Respond to evidence request'})).toBeNull());
 fireEvent.click(screen.getByRole('button',{name:'Withdraw identifier claim'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Withdraw reviewed claim'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await waitFor(()=>expect(env.api.mock.calls.filter(c=>c[1]?.method==='POST')).toHaveLength(2));await waitFor(()=>expect(screen.queryByRole('button',{name:'Withdraw identifier claim'})).toBeNull());const calls=env.api.mock.calls.filter(c=>c[1]?.method==='POST');expect(JSON.parse(calls[1][1].body)).toMatchObject({expectedVersion:3});
});
it('retains verified save when refreshed records fail and disables stale continuation rather than offering a write retry',async()=>{
 const claimId='22222222-2222-4222-8222-222222222222',claim={id:claimId,assetId,version:2,status:'awaiting_evidence',requesterActions:['respond','withdraw'],alias:{kind:'serial',value:'Exact serial'},ownershipTransferred:false,otherOwnerDisclosed:false};let saved=false;
 env.api.mockImplementation(async(path:string,init:any)=>{if(init?.method==='POST'){saved=true;const body=JSON.parse(init.body);return {...claim,operationId:body.operationId,version:3,status:'pending_review',responseReason:body.reason,physicalEvidenceVerified:false,respondedAt:'2026-10-07T13:00:00Z'};}if(saved)throw Error('read unavailable');return path.endsWith('/identifier-claims')?{claims:[claim],incoming:[],truncated:false}:detail;});
 render(<InventoryRecovery {...props} canManage/>);await open();fireEvent.click(await screen.findByRole('button',{name:'Respond to evidence request'}));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'Actual explanation'}});fireEvent.click(screen.getByRole('button',{name:'Review exact request'}));fireEvent.click(screen.getByRole('button',{name:'Confirm reviewed request'}));await screen.findByText('Canonical record saved. Refresh the recovery panel before another action; current records are unavailable.');expect(screen.queryByRole('button',{name:'Retry exact request'})).toBeNull();expect(screen.queryByRole('button',{name:'Withdraw identifier claim'})).toBeNull();expect(screen.queryByRole('button',{name:'Respond to evidence request'})).toBeNull();expect(env.api.mock.calls.filter(c=>c[1]?.method==='POST')).toHaveLength(1);
});
