import { Router, type IRouter, type Request, type Response } from "express";
import { and, asc, desc, eq, gte, ilike, inArray, isNull, lte, or } from "drizzle-orm";
import { z } from "zod/v4";
import {
  db, workHubAcknowledgementsTable, workHubAnnouncementRecipientsTable, workHubAnnouncementsTable,
  workHubExternalEventsTable, workHubFilesTable, workHubMeetingArtifactsTable, workHubMeetingAttendanceTable,
  workHubMeetingChatTable, workHubMeetingConsentsTable, workHubMeetingOccurrencesTable, workHubMeetingParticipantsTable,
  workHubMeetingsTable, workHubSearchDocumentsTable, workHubShiftAssignmentsTable, workHubShiftRequestsTable,
  workHubShiftsTable, workHubTaskEventsTable, workHubTasksTable, workHubTranscriptSegmentsTable,
} from "@workspace/db";
import { workHubCommandEnvelopeSchema, type WorkHubOwner } from "@workspace/api-zod";
import { getSessionFromRequest, type SessionPayload } from "../lib/session";
import { sendApiError } from "../lib/apiError";
import { ObjectStorageService } from "../lib/objectStorage";
import { absoluteUploadUrl } from "../lib/uploadUrl";
import { executeWorkHubCommand } from "../work-hub/commands";
import { createWorkHubAccess, requireWorkHubCapability, WorkHubAccessError } from "../work-hub/context-access";
import { resolveChannelAccess } from "../work-hub/queries";
import { isWorkHubEnabled } from "../work-hub/feature-access";
import { normalizeRecurrenceRule, validateMeetingConsent } from "../work-hub/domain-rules";
import { validateVoiceNoteMetadata } from "../work-hub/file-policy";
import { notifyUsers } from "./notifications";

const router: IRouter = Router(); const storage = new ObjectStorageService();
type Actor = SessionPayload & { userId: number };
function actor(req: Request): Actor | null { const value = getSessionFromRequest(req); return value?.userId ? value as Actor : null; }
function clientSource(req: Request): "web" | "ios" { return req.header("x-vndrly-client") === "ios" ? "ios" : "web"; }
function ownAccess(session: Actor, owner: WorkHubOwner, capability: Parameters<typeof requireWorkHubCapability>[1]) { const access = createWorkHubAccess({ session, owner, context: { kind: "organization", id: owner.id }, participant: true }); requireWorkHubCapability(access, capability); }
function failure(res: Response, error: unknown): void { if (error instanceof WorkHubAccessError) { sendApiError(res, error.status, error.code, error.message); return; } if (error instanceof z.ZodError) { sendApiError(res, 400, "work_hub.invalid_operation", "Invalid Work Hub request", { issues: error.issues }); return; } if (error instanceof Error && error.message.includes("version_conflict")) { sendApiError(res, 409, "work_hub.version_conflict", "The item changed on another device"); return; } throw error; }
function ownerFilter(session: Actor) { return session.role === "admin" ? undefined : or(session.vendorId ? and(eq(workHubTasksTable.ownerOrgType, "vendor"), eq(workHubTasksTable.ownerOrgId, session.vendorId)) : undefined, session.partnerId ? and(eq(workHubTasksTable.ownerOrgType, "partner"), eq(workHubTasksTable.ownerOrgId, session.partnerId)) : undefined); }

router.use("/work-hub", async (_req, res, next) => { if (!(await isWorkHubEnabled())) { sendApiError(res, 404, "work_hub.not_found", "Not found"); return; } next(); });

router.get("/work-hub/home", async (req, res) => {
  const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required");
  const now = new Date();
  const [tasks, announcements, shifts, meetings] = await Promise.all([
    db.select().from(workHubTasksTable).where(and(ownerFilter(session), or(eq(workHubTasksTable.assigneeUserId, session.userId), eq(workHubTasksTable.createdById, session.userId)))).orderBy(asc(workHubTasksTable.dueAt)).limit(50),
    db.select({ announcement: workHubAnnouncementsTable, recipient: workHubAnnouncementRecipientsTable }).from(workHubAnnouncementRecipientsTable).innerJoin(workHubAnnouncementsTable, eq(workHubAnnouncementsTable.id, workHubAnnouncementRecipientsTable.announcementId)).where(and(eq(workHubAnnouncementRecipientsTable.userId, session.userId), isNull(workHubAnnouncementsTable.withdrawnAt))).orderBy(desc(workHubAnnouncementsTable.publishedAt)).limit(50),
    db.select({ shift: workHubShiftsTable, assignment: workHubShiftAssignmentsTable }).from(workHubShiftAssignmentsTable).innerJoin(workHubShiftsTable, eq(workHubShiftsTable.id, workHubShiftAssignmentsTable.shiftId)).where(and(eq(workHubShiftAssignmentsTable.userId, session.userId), gte(workHubShiftsTable.endsAt, now))).orderBy(asc(workHubShiftsTable.startsAt)).limit(50),
    db.select({ occurrence: workHubMeetingOccurrencesTable, meeting: workHubMeetingsTable, participant: workHubMeetingParticipantsTable }).from(workHubMeetingParticipantsTable).innerJoin(workHubMeetingOccurrencesTable, eq(workHubMeetingOccurrencesTable.id, workHubMeetingParticipantsTable.occurrenceId)).innerJoin(workHubMeetingsTable, eq(workHubMeetingsTable.id, workHubMeetingOccurrencesTable.meetingId)).where(and(eq(workHubMeetingParticipantsTable.userId, session.userId), gte(workHubMeetingOccurrencesTable.startsAt, new Date(now.getTime() - 86_400_000)))).orderBy(asc(workHubMeetingOccurrencesTable.startsAt)).limit(50),
  ]);
  return res.json({ generatedAt: now.toISOString(), tasks, announcements, shifts, meetings });
});

router.get("/work-hub/tasks", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); return res.json(await db.select().from(workHubTasksTable).where(and(ownerFilter(session), req.query.status ? eq(workHubTasksTable.status, String(req.query.status)) : undefined)).orderBy(asc(workHubTasksTable.dueAt), desc(workHubTasksTable.createdAt)).limit(100)); });
router.post("/work-hub/tasks", async (req, res) => {
  const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required");
  try { const envelope = workHubCommandEnvelopeSchema.parse(req.body); ownAccess(session, envelope.owner, "task.assign"); const payload = z.object({ title: z.string().trim().min(1).max(200), description: z.string().max(20_000).nullable().optional(), assigneeUserId: z.number().int().positive().nullable().optional(), dueAt: z.iso.datetime().nullable().optional(), priority: z.enum(["low", "normal", "high", "urgent"]).default("normal"), channelId: z.string().uuid().nullable().optional(), recurrence: z.unknown().nullable().optional() }).parse(envelope.payload); if (payload.channelId) await resolveChannelAccess(session, payload.channelId, "task.assign"); const recurrence = payload.recurrence ? normalizeRecurrenceRule(payload.recurrence as never) : null;
    const result = await executeWorkHubCommand({ userId: session.userId, source: clientSource(req) }, "task.create", envelope, async (tx) => { const [task] = await tx.insert(workHubTasksTable).values({ ownerOrgType: envelope.owner.type, ownerOrgId: envelope.owner.id, channelId: payload.channelId ?? null, title: payload.title, description: payload.description ?? null, assigneeUserId: payload.assigneeUserId ?? null, dueAt: payload.dueAt ? new Date(payload.dueAt) : null, priority: payload.priority, recurrence, createdById: session.userId }).returning(); await tx.insert(workHubTaskEventsTable).values({ taskId: task.id, actorUserId: session.userId, eventType: "created" }); return task; });
    if (payload.assigneeUserId && !result.replayed) await notifyUsers([payload.assigneeUserId], { type: "work_hub_task_assigned", category: "work_hub_tasks", title: "New Work Hub task", body: payload.title, link: `/work-hub/tasks/${result.resource.id}`, dedupeKey: `work-hub-task:${result.resource.id}:assigned` }); return res.status(result.replayed ? 200 : 201).json(result);
  } catch (error) { return failure(res, error); }
});
router.patch("/work-hub/tasks/:id", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); try { const envelope = workHubCommandEnvelopeSchema.parse(req.body); const payload = z.object({ status: z.enum(["open", "in_progress", "completed", "cancelled"]) }).parse(envelope.payload); const result = await executeWorkHubCommand({ userId: session.userId, source: clientSource(req) }, "task.update", envelope, async (tx) => { const [current] = await tx.select().from(workHubTasksTable).where(eq(workHubTasksTable.id, req.params.id)).limit(1); if (!current) throw new WorkHubAccessError("not_found"); if (current.ownerOrgType !== envelope.owner.type || current.ownerOrgId !== envelope.owner.id) throw new WorkHubAccessError("not_found"); if (current.assigneeUserId !== session.userId && current.createdById !== session.userId && session.role !== "admin" && session.membershipRole !== "admin") throw new WorkHubAccessError("forbidden"); if (current.version !== envelope.expectedVersion) throw new Error("work_hub.version_conflict"); const [updated] = await tx.update(workHubTasksTable).set({ status: payload.status, version: current.version + 1, updatedAt: new Date() }).where(eq(workHubTasksTable.id, current.id)).returning(); await tx.insert(workHubTaskEventsTable).values({ taskId: current.id, actorUserId: session.userId, eventType: `status.${payload.status}` }); return updated; }); return res.json(result); } catch (error) { return failure(res, error); } });

router.post("/work-hub/announcements", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); try { const envelope = workHubCommandEnvelopeSchema.parse(req.body); ownAccess(session, envelope.owner, "announcement.publish"); const payload = z.object({ title: z.string().trim().min(1).max(200), body: z.string().trim().min(1).max(50_000), recipientUserIds: z.array(z.number().int().positive()).min(1).max(5000), urgency: z.enum(["normal", "urgent"]).default("normal"), acknowledgementRequired: z.boolean().default(false), expiresAt: z.iso.datetime().nullable().optional() }).parse(envelope.payload); const recipients = [...new Set(payload.recipientUserIds)]; const result = await executeWorkHubCommand({ userId: session.userId, source: clientSource(req) }, "announcement.publish", envelope, async (tx) => { const [announcement] = await tx.insert(workHubAnnouncementsTable).values({ ownerOrgType: envelope.owner.type, ownerOrgId: envelope.owner.id, title: payload.title, body: payload.body, urgency: payload.urgency, acknowledgementRequired: payload.acknowledgementRequired, publishedById: session.userId, expiresAt: payload.expiresAt ? new Date(payload.expiresAt) : null }).returning(); await tx.insert(workHubAnnouncementRecipientsTable).values(recipients.map((userId) => ({ announcementId: announcement.id, userId }))); return announcement; }); if (!result.replayed) await notifyUsers(recipients, { type: payload.urgency === "urgent" ? "work_hub_announcement_urgent" : "work_hub_announcement", category: "system", title: payload.title, body: payload.body.slice(0, 180), link: `/work-hub/announcements/${result.resource.id}`, dedupeKey: `work-hub-announcement:${result.resource.id}` }); return res.status(result.replayed ? 200 : 201).json(result); } catch (error) { return failure(res, error); } });
router.post("/work-hub/announcements/:id/acknowledge", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const [recipient] = await db.update(workHubAnnouncementRecipientsTable).set({ acknowledgedAt: new Date(), viewedAt: new Date() }).where(and(eq(workHubAnnouncementRecipientsTable.announcementId, req.params.id), eq(workHubAnnouncementRecipientsTable.userId, session.userId))).returning(); if (!recipient) return sendApiError(res, 404, "work_hub.not_found", "Not found"); const [announcement] = await db.select().from(workHubAnnouncementsTable).where(eq(workHubAnnouncementsTable.id, req.params.id)); await db.insert(workHubAcknowledgementsTable).values({ ownerOrgType: announcement.ownerOrgType, ownerOrgId: announcement.ownerOrgId, subjectType: "announcement", subjectId: announcement.id, subjectVersion: announcement.version, userId: session.userId }).onConflictDoNothing(); return res.json(recipient); });

router.get("/work-hub/calendar", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const start = new Date(String(req.query.start)); const end = new Date(String(req.query.end)); if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || start >= end) return sendApiError(res, 400, "work_hub.invalid_operation", "Invalid calendar range"); const shiftOwner = session.role === "admin" ? undefined : or(session.vendorId ? and(eq(workHubShiftsTable.ownerOrgType, "vendor"), eq(workHubShiftsTable.ownerOrgId, session.vendorId)) : undefined, session.partnerId ? and(eq(workHubShiftsTable.ownerOrgType, "partner"), eq(workHubShiftsTable.ownerOrgId, session.partnerId)) : undefined); const [shifts, tasks, meetings] = await Promise.all([db.select().from(workHubShiftsTable).where(and(shiftOwner, lte(workHubShiftsTable.startsAt, end), gte(workHubShiftsTable.endsAt, start))), db.select().from(workHubTasksTable).where(and(ownerFilter(session), gte(workHubTasksTable.dueAt, start), lte(workHubTasksTable.dueAt, end))), db.select({ occurrence: workHubMeetingOccurrencesTable, meeting: workHubMeetingsTable }).from(workHubMeetingOccurrencesTable).innerJoin(workHubMeetingsTable, eq(workHubMeetingsTable.id, workHubMeetingOccurrencesTable.meetingId)).where(and(lte(workHubMeetingOccurrencesTable.startsAt, end), or(isNull(workHubMeetingOccurrencesTable.endsAt), gte(workHubMeetingOccurrencesTable.endsAt, start))))]); return res.json({ shifts: shifts.map((item) => ({ source: "vndrly", authority: "work_hub_shift", item })), tasks: tasks.map((item) => ({ source: "vndrly", authority: "work_hub_task", item })), meetings: meetings.map((item) => ({ source: "vndrly", authority: "work_hub_meeting", item })), external: [] }); });
router.post("/work-hub/shifts", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); try { const envelope = workHubCommandEnvelopeSchema.parse(req.body); ownAccess(session, envelope.owner, "shift.manage"); const payload = z.object({ title: z.string().trim().min(1).max(200), startsAt: z.iso.datetime(), endsAt: z.iso.datetime(), timezone: z.string().min(3).max(80), open: z.boolean().default(false), assigneeUserIds: z.array(z.number().int().positive()).max(500).default([]), qualificationCodes: z.array(z.string().max(80)).max(50).default([]), recurrence: z.unknown().nullable().optional() }).parse(envelope.payload); if (new Date(payload.startsAt) >= new Date(payload.endsAt)) throw new z.ZodError([]); const recurrence = payload.recurrence ? normalizeRecurrenceRule(payload.recurrence as never) : null; const result = await executeWorkHubCommand({ userId: session.userId, source: clientSource(req) }, "shift.create", envelope, async (tx) => { const [shift] = await tx.insert(workHubShiftsTable).values({ ownerOrgType: envelope.owner.type, ownerOrgId: envelope.owner.id, title: payload.title, startsAt: new Date(payload.startsAt), endsAt: new Date(payload.endsAt), timezone: payload.timezone, open: payload.open, qualificationCodes: payload.qualificationCodes, recurrence, createdById: session.userId }).returning(); if (payload.assigneeUserIds.length) await tx.insert(workHubShiftAssignmentsTable).values([...new Set(payload.assigneeUserIds)].map((userId) => ({ shiftId: shift.id, userId, assignedById: session.userId }))).onConflictDoNothing(); return shift; }); if (!result.replayed) await notifyUsers(payload.assigneeUserIds, { type: "work_hub_shift_assigned", category: "crew", title: "Shift assigned", body: payload.title, link: `/work-hub/calendar?shift=${result.resource.id}`, dedupeKey: `work-hub-shift:${result.resource.id}` }); return res.status(result.replayed ? 200 : 201).json(result); } catch (error) { return failure(res, error); } });
router.post("/work-hub/shifts/:id/claim", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const [shift] = await db.select().from(workHubShiftsTable).where(eq(workHubShiftsTable.id, req.params.id)); if (!shift?.open) return sendApiError(res, 409, "work_hub.invalid_operation", "Shift is not open"); const [assignment] = await db.insert(workHubShiftAssignmentsTable).values({ shiftId: shift.id, userId: session.userId, status: "claimed", assignedById: session.userId }).onConflictDoNothing().returning(); if (!assignment) return sendApiError(res, 409, "work_hub.invalid_operation", "Shift was already claimed by this user"); await db.insert(workHubShiftRequestsTable).values({ shiftId: shift.id, requestType: "claim", requestedById: session.userId, status: "approved", decidedById: session.userId, decidedAt: new Date() }); return res.status(201).json(assignment); });

router.post("/work-hub/meetings", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); try { const envelope = workHubCommandEnvelopeSchema.parse(req.body); ownAccess(session, envelope.owner, "meeting.host"); const payload = z.object({ title: z.string().trim().min(1).max(200), agenda: z.string().max(50_000).nullable().optional(), startsAt: z.iso.datetime(), endsAt: z.iso.datetime().nullable().optional(), timezone: z.string().min(3).max(80), recordingAllowed: z.boolean().default(false), participantUserIds: z.array(z.number().int().positive()).max(500).default([]), recurrence: z.unknown().nullable().optional() }).parse(envelope.payload); const recurrence = payload.recurrence ? normalizeRecurrenceRule(payload.recurrence as never) : null; const participants = [...new Set([session.userId, ...payload.participantUserIds])]; const result = await executeWorkHubCommand({ userId: session.userId, source: clientSource(req) }, "meeting.create", envelope, async (tx) => { const [meeting] = await tx.insert(workHubMeetingsTable).values({ ownerOrgType: envelope.owner.type, ownerOrgId: envelope.owner.id, title: payload.title, agenda: payload.agenda ?? null, timezone: payload.timezone, recurrence, recordingAllowed: payload.recordingAllowed, createdById: session.userId }).returning(); const [occurrence] = await tx.insert(workHubMeetingOccurrencesTable).values({ meetingId: meeting.id, startsAt: new Date(payload.startsAt), endsAt: payload.endsAt ? new Date(payload.endsAt) : null }).returning(); await tx.insert(workHubMeetingParticipantsTable).values(participants.map((userId) => ({ occurrenceId: occurrence.id, userId, role: userId === session.userId ? "host" : "participant" }))); return { meeting, occurrence }; }); if (!result.replayed) await notifyUsers(participants.filter((id) => id !== session.userId), { type: "work_hub_meeting_invite", category: "system", title: "Meeting invitation", body: payload.title, link: `/work-hub/meetings/${result.resource.occurrence.id}`, dedupeKey: `work-hub-meeting:${result.resource.occurrence.id}:invite` }); return res.status(result.replayed ? 200 : 201).json(result); } catch (error) { return failure(res, error); } });
router.post("/work-hub/meetings/:occurrenceId/consent", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const payload = z.object({ policyVersion: z.number().int().positive(), response: z.enum(["accepted", "declined"]) }).parse(req.body); const [participant] = await db.select().from(workHubMeetingParticipantsTable).where(and(eq(workHubMeetingParticipantsTable.occurrenceId, req.params.occurrenceId), eq(workHubMeetingParticipantsTable.userId, session.userId))); if (!participant) return sendApiError(res, 404, "work_hub.not_found", "Not found"); const [consent] = await db.insert(workHubMeetingConsentsTable).values({ occurrenceId: req.params.occurrenceId, userId: session.userId, ...payload }).onConflictDoUpdate({ target: [workHubMeetingConsentsTable.occurrenceId, workHubMeetingConsentsTable.userId, workHubMeetingConsentsTable.policyVersion], set: { response: payload.response, respondedAt: new Date() } }).returning(); return res.json(consent); });
router.post("/work-hub/meetings/:occurrenceId/join", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const [participant] = await db.select().from(workHubMeetingParticipantsTable).where(and(eq(workHubMeetingParticipantsTable.occurrenceId, req.params.occurrenceId), eq(workHubMeetingParticipantsTable.userId, session.userId))); if (!participant) return sendApiError(res, 404, "work_hub.not_found", "Not found"); if (!process.env.WORK_HUB_AUDIO_PROVIDER) return sendApiError(res, 503, "work_hub.provider_unavailable", "Audio meetings are configured but awaiting provider activation", { safeDisabled: true }); return sendApiError(res, 503, "work_hub.provider_unavailable", "Configured audio adapter is unavailable", { safeDisabled: true }); });
router.post("/work-hub/meetings/:occurrenceId/chat", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const body = z.string().trim().min(1).max(10_000).parse(req.body?.body); const [participant] = await db.select().from(workHubMeetingParticipantsTable).where(and(eq(workHubMeetingParticipantsTable.occurrenceId, req.params.occurrenceId), eq(workHubMeetingParticipantsTable.userId, session.userId))); if (!participant) return sendApiError(res, 404, "work_hub.not_found", "Not found"); const [message] = await db.insert(workHubMeetingChatTable).values({ occurrenceId: req.params.occurrenceId, userId: session.userId, body }).returning(); return res.status(201).json(message); });
router.get("/work-hub/meetings/:occurrenceId/catch-up", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const [participant] = await db.select().from(workHubMeetingParticipantsTable).where(and(eq(workHubMeetingParticipantsTable.occurrenceId, req.params.occurrenceId), eq(workHubMeetingParticipantsTable.userId, session.userId))); if (!participant && session.role !== "admin") return sendApiError(res, 404, "work_hub.not_found", "Not found"); const [occurrence] = await db.select({ occurrence: workHubMeetingOccurrencesTable, meeting: workHubMeetingsTable }).from(workHubMeetingOccurrencesTable).innerJoin(workHubMeetingsTable, eq(workHubMeetingsTable.id, workHubMeetingOccurrencesTable.meetingId)).where(eq(workHubMeetingOccurrencesTable.id, req.params.occurrenceId)); const artifacts = await db.select().from(workHubMeetingArtifactsTable).where(eq(workHubMeetingArtifactsTable.occurrenceId, req.params.occurrenceId)); const artifactIds = artifacts.map((item) => item.id); const [attendance, chat, transcript] = await Promise.all([db.select().from(workHubMeetingAttendanceTable).where(eq(workHubMeetingAttendanceTable.occurrenceId, req.params.occurrenceId)), db.select().from(workHubMeetingChatTable).where(eq(workHubMeetingChatTable.occurrenceId, req.params.occurrenceId)).orderBy(asc(workHubMeetingChatTable.createdAt)), artifactIds.length ? db.select().from(workHubTranscriptSegmentsTable).where(inArray(workHubTranscriptSegmentsTable.artifactId, artifactIds)).orderBy(asc(workHubTranscriptSegmentsTable.startsAtMs)) : Promise.resolve([])]); return res.json({ ...occurrence, attendance, chat, artifacts, transcript, recap: null, suggestedTasks: [] }); });

router.post("/work-hub/files/reserve", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); try { const envelope = workHubCommandEnvelopeSchema.parse(req.body); const payload = z.object({ channelId: z.string().uuid(), fileName: z.string().trim().min(1).max(255), contentType: z.string().trim().min(1).max(120), byteSize: z.number().int().positive().max(25 * 1024 * 1024), checksumSha256: z.string().regex(/^[a-f0-9]{64}$/i), voiceMetadata: z.unknown().nullable().optional() }).parse(envelope.payload); await resolveChannelAccess(session, payload.channelId, "channel.write"); const mediaMetadata = payload.voiceMetadata ? validateVoiceNoteMetadata(payload.voiceMetadata) : null; const descriptor = storage.getUploadDescriptor(); const result = await executeWorkHubCommand({ userId: session.userId, source: clientSource(req) }, "file.reserve", envelope, async (tx) => { const [file] = await tx.insert(workHubFilesTable).values({ ownerOrgType: envelope.owner.type, ownerOrgId: envelope.owner.id, channelId: payload.channelId, uploadedById: session.userId, storageKey: descriptor.objectPath, fileName: payload.fileName, contentType: payload.contentType, byteSize: payload.byteSize, checksumSha256: payload.checksumSha256.toLowerCase(), mediaMetadata, expiresAt: new Date(Date.now() + 24 * 60 * 60_000) }).returning(); return { file, uploadURL: absoluteUploadUrl(req, descriptor.uploadURL) }; }); return res.status(result.replayed ? 200 : 201).json(result); } catch (error) { return failure(res, error); } });
router.post("/work-hub/files/:id/finalize", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const payload = z.object({ objectURL: z.string().min(1) }).parse(req.body); const [file] = await db.select().from(workHubFilesTable).where(eq(workHubFilesTable.id, req.params.id)); if (!file) return sendApiError(res, 404, "work_hub.not_found", "Not found"); if (!file.channelId) return sendApiError(res, 409, "work_hub.invalid_operation", "File context missing"); await resolveChannelAccess(session, file.channelId, "channel.write"); const objectPath = await storage.trySetObjectEntityAclPolicy(payload.objectURL, { owner: String(session.userId), visibility: "private" }); if (objectPath !== file.storageKey) return sendApiError(res, 409, "work_hub.invalid_operation", "Upload reservation mismatch"); const [updated] = await db.update(workHubFilesTable).set({ state: "finalized", finalizedAt: new Date(), expiresAt: null }).where(eq(workHubFilesTable.id, file.id)).returning(); return res.json(updated); });

router.get("/work-hub/search", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const q = z.string().trim().min(2).max(200).parse(req.query.q); const ownership = session.role === "admin" ? undefined : or(session.vendorId ? and(eq(workHubSearchDocumentsTable.ownerOrgType, "vendor"), eq(workHubSearchDocumentsTable.ownerOrgId, session.vendorId)) : undefined, session.partnerId ? and(eq(workHubSearchDocumentsTable.ownerOrgType, "partner"), eq(workHubSearchDocumentsTable.ownerOrgId, session.partnerId)) : undefined); const results = await db.select({ id: workHubSearchDocumentsTable.id, subjectType: workHubSearchDocumentsTable.subjectType, subjectId: workHubSearchDocumentsTable.subjectId, title: workHubSearchDocumentsTable.title, contextKind: workHubSearchDocumentsTable.contextKind, contextId: workHubSearchDocumentsTable.contextId, updatedAt: workHubSearchDocumentsTable.updatedAt }).from(workHubSearchDocumentsTable).where(and(ownership, ilike(workHubSearchDocumentsTable.searchableText, `%${q.replace(/[%_]/g, "\\$&")}%`))).orderBy(desc(workHubSearchDocumentsTable.updatedAt)).limit(50); return res.json(results); });
router.get("/work-hub/connectors/microsoft-365", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const configured = Boolean(process.env.MICROSOFT_365_CLIENT_ID && process.env.MICROSOFT_365_CLIENT_SECRET); return res.json({ enabled: false, configured, capability: "calendar.read", mode: "read_only", authoritativeSource: "vndrly", status: configured ? "awaiting_admin_connection" : "external_registration_required" }); });
router.post("/work-hub/connectors/microsoft-365/connect", async (req, res) => { const session = actor(req); if (!session) return sendApiError(res, 401, "auth.unauthenticated", "Authentication required"); const owner = z.object({ type: z.enum(["vendor", "partner"]), id: z.number().int().positive() }).parse(req.body?.owner); ownAccess(session, owner, "connector.manage"); return sendApiError(res, 503, "work_hub.provider_unavailable", "Microsoft 365 registration is required before connection", { capability: "calendar.read", safeDisabled: true }); });

export default router;
