import React,{useEffect,useRef,useState} from "react";
import {Image,Text,TextInput,View} from "react-native";
import {FleetEvidenceSchema,type FleetEvidence as Evidence,type FleetRun} from "@workspace/api-zod";
import {apiFetch,getApiBase} from "@/lib/api";
import {captureAuthScope,isAuthScopeCurrent,getToken,subscribeToken,subscribeUser} from "@/lib/auth";
import {captureFleetEvidence,clearFleetEvidencePending,readFleetEvidencePending,submitFleetEvidencePending} from "@/lib/fleet-evidence-device-native";
import type {FleetEvidencePending} from "@/lib/fleet-evidence-device";
import type {FleetVerifiedAccount} from "@/lib/fleet-phone-location";
import {useFleetCopy} from "@/lib/fleet-copy";
import TogglePillButton from "@/components/TogglePillButton";

export default function FleetEvidence({run,account,disabled,onChanged}:{run:FleetRun;account:FleetVerifiedAccount|undefined;disabled:boolean;onChanged:()=>void}) {
 const copy=useFleetCopy(),[records,setRecords]=useState<Evidence[]>([]),[pending,setPending]=useState<FleetEvidencePending|null>(null),[otherPending,setOtherPending]=useState(false);
 const [kind,setKind]=useState<Evidence["kind"]>("photo"),[notes,setNotes]=useState(""),[stopId,setStopId]=useState<string|undefined>(),[loadId,setLoadId]=useState<string|undefined>();
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false),[preview,setPreview]=useState<{id:string;token:string}|null>(null);
 const alive=useRef(true),blocked=useRef(disabled);blocked.current=disabled;
 const owns=!!account&&run.driverUserId===account.userId&&run.companyId===account.companyId&&["acknowledged","in_progress"].includes(run.status);
 const matches=(value:FleetEvidencePending)=>!!account&&value.runId===run.id&&value.account.userId===account.userId&&value.account.companyId===account.companyId&&value.account.membershipId===account.membershipId&&value.account.sessionVersion===account.sessionVersion;
 async function restore(){const scope=captureAuthScope();const value=await readFleetEvidencePending();if(alive.current&&isAuthScopeCurrent(scope)){setPending(value&&matches(value)?value:null);setOtherPending(!!value&&!matches(value));}}
 useEffect(()=>{alive.current=true;void restore().catch(e=>{if(alive.current)setError(e.message);});const clear=()=>{setPreview(null);setRecords([]);setPending(null);setOtherPending(false);};const user=subscribeUser(clear),token=subscribeToken(clear);return()=>{alive.current=false;user();token();};},[]);
 useEffect(()=>{if(disabled)setPreview(null);},[disabled]);
 async function read(){if(disabled||busy)return;setBusy(true);setError("");const scope=captureAuthScope();try{const result=await apiFetch<{runId:string;evidence:unknown[]}>(`/api/fleet/runs/${run.id}/evidence`,{},scope);if(result.runId!==run.id)throw new Error("Evidence readback scope could not be verified.");const parsed=result.evidence.map(value=>FleetEvidenceSchema.parse(value));if(parsed.some(value=>value.runId!==run.id||value.companyId!==run.companyId))throw new Error("Evidence readback scope could not be verified.");if(alive.current&&isAuthScopeCurrent(scope)&&!blocked.current)setRecords(parsed);}catch(e){if(alive.current){setRecords([]);setPreview(null);setError(e instanceof Error?e.message:"Evidence read is unavailable.");}}finally{if(alive.current)setBusy(false);}}
 async function capture(source:"camera"|"library") {if(!owns||!account||disabled||busy||pending||otherPending)return;setBusy(true);setError("");setSaved(false);const scope=captureAuthScope();try{const value=await captureFleetEvidence(account,run,{kind,notes,...(stopId?{stopId}:{}),...(loadId?{loadId}:{})},source);if(alive.current&&isAuthScopeCurrent(scope))setPending(value);}catch(e){if(alive.current)setError(e instanceof Error?e.message:"Device capture is unavailable.");}finally{if(alive.current)setBusy(false);}}
 async function submit(){if(!pending||disabled||busy)return;setBusy(true);setError("");const scope=captureAuthScope();try{const result=await submitFleetEvidencePending();if(alive.current&&isAuthScopeCurrent(scope)){setPending(null);setSaved(true);setRecords(current=>[...current.filter(value=>value.evidenceId!==result.evidenceId),result]);onChanged();}}catch(e){if(alive.current){setError(e instanceof Error?e.message:"Evidence save outcome needs verification.");await restore();}}finally{if(alive.current)setBusy(false);}}
 async function open(value:Evidence){if(disabled||busy)return;const scope=captureAuthScope(),token=await getToken();if(alive.current&&isAuthScopeCurrent(scope)&&token&&!blocked.current)setPreview({id:value.evidenceId,token});}
 return <View style={{gap:8}}><Text>{copy("Fleet device evidence")}</Text><Text>{copy("Private uploaded images are bound to this run only after the server verifies and saves the association. They do not prove physical arrival, load quantity or signature identity. Capture while safely stopped.")}</Text>
  <TogglePillButton disabled={disabled||busy} onPress={()=>void read()}>{copy("Read saved Fleet evidence")}</TogglePillButton>
  {records.map(value=><View key={value.evidenceId}><Text>{copy(value.kind)} · {value.size} {copy("bytes")} · {value.recordedAt}</Text><Text>{value.notes}</Text><Text>{copy("SHA256")}: {value.sha256}</Text>{value.capturedAt&&<Text>{copy("Device capture time")}: {value.capturedAt}</Text>}<Text>{copy("Source: device upload. Physical proof and signature identity are not verified.")}</Text>{value.contentType.startsWith("image/")?<TogglePillButton disabled={disabled||busy} onPress={()=>void open(value)}>{copy("View authorized saved image")}</TogglePillButton>:<Text>{copy("PDF preview is unavailable on this screen.")}</Text>}{preview?.id===value.evidenceId&&<Image accessibilityLabel={copy("Authorized Fleet evidence image")} style={{width:"100%",height:240}} resizeMode="contain" source={{uri:`${getApiBase().replace(/\/$/,"")}/api/fleet/runs/${run.id}/evidence/${value.evidenceId}/file`,headers:{Authorization:`Bearer ${preview.token}`},cache:"reload"}} onError={()=>{setPreview(null);setError("The saved image could not be read under current permissions.");}}/>}</View>)}
  {saved&&<Text>{copy("Fleet evidence association saved and verified.")}</Text>}
  {!!error&&<Text accessibilityRole="alert">{copy(error)}</Text>}
  {owns&&!pending&&!otherPending&&<>{(["photo","scale","receipt","signature"] as const).map(value=><TogglePillButton key={value} disabled={disabled||busy} solid={kind===value} onPress={()=>setKind(value)}>{copy(value)}</TogglePillButton>)}<TextInput accessibilityLabel={copy("Evidence notes")} editable={!disabled&&!busy} value={notes} onChangeText={setNotes}/>
   <TogglePillButton disabled={disabled||busy} onPress={()=>{setStopId(undefined);setLoadId(undefined);}}>{copy("Whole run evidence")}</TogglePillButton>
   {run.stops.map(stop=><TogglePillButton key={stop.id} disabled={disabled||busy} solid={stopId===stop.id} onPress={()=>{setStopId(stop.id);setLoadId(undefined);}}>{stop.sequence+1}. {copy(stop.kind)} · {run.labels?.sites.find(site=>site.siteId===stop.siteId)?.name??`site ${stop.siteId}`}</TogglePillButton>)}
   {run.loads.map(load=><TogglePillButton key={load.id} disabled={disabled||busy} solid={loadId===load.id} onPress={()=>{setLoadId(load.id);setStopId(undefined);}}>{load.commodity} · {load.manifestReference}</TogglePillButton>)}
   <TogglePillButton disabled={disabled||busy||!notes.trim()} onPress={()=>void capture("camera")}>{copy("Capture Fleet image")}</TogglePillButton><TogglePillButton disabled={disabled||busy||!notes.trim()} onPress={()=>void capture("library")}>{copy("Choose Fleet image")}</TogglePillButton></>}
  {pending&&<><Text>{copy("Captured upload is pending, not saved Fleet evidence.")}</Text><Text>{copy(pending.input.kind)} · {pending.asset.size} {copy("bytes")} · {pending.input.notes}</Text><Text>{copy(pending.finalized?"Private upload finalized; Fleet association pending":pending.uploaded?"Private bytes uploaded; finalization pending":"Private upload pending")}</Text><TogglePillButton disabled={disabled||busy} onPress={()=>void submit()}>{copy("Verify and retry exact Fleet evidence upload")}</TogglePillButton></>}
  {otherPending&&<Text>{copy("Another run has an unresolved device upload. Resolve or discard it before new capture.")}</Text>}
  {(pending||otherPending)&&<TogglePillButton disabled={busy} onPress={()=>{void clearFleetEvidencePending().then(()=>{if(alive.current){setPending(null);setOtherPending(false);}}).catch(e=>{if(alive.current)setError(e.message);});}}>{copy("Discard pending device upload")}</TogglePillButton>}
 </View>;
}
