import React,{useEffect,useRef,useState} from "react";
import {Text,TextInput,View} from "react-native";
import * as Crypto from "expo-crypto";
import {FleetRunSchema,FleetCargoTransferSchema,FleetCargoTransferInputSchema,FleetCargoTransferActionSchema,type FleetRun,type FleetCargoTransfer} from "@workspace/api-zod";
import {apiFetch} from "@/lib/api";
import {captureAuthScope,isAuthScopeCurrent} from "@/lib/auth";
import {useFleetCopy} from "@/lib/fleet-copy";
import TogglePillButton from "@/components/TogglePillButton";
type Proposal=ReturnType<typeof FleetCargoTransferInputSchema.parse>;
type Action=ReturnType<typeof FleetCargoTransferActionSchema.parse>;
type Pending={kind:"propose";body:Proposal}|{kind:"action";id:string;body:Action};
export default function FleetCargo({run,canDispatch,disabled,onChanged}:{run:FleetRun;canDispatch:boolean;disabled:boolean;onChanged:()=>void}) {
 const copy=useFleetCopy(),[records,setRecords]=useState<FleetCargoTransfer[]>([]),[targetId,setTargetId]=useState(""),[target,setTarget]=useState<FleetRun|null>(null);
 const [sourceLoadId,setSourceLoadId]=useState(""),[deliveryId,setDeliveryId]=useState(""),[reason,setReason]=useState(""),[notes,setNotes]=useState("");
 const [pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const locked=disabled||busy||!!pending;
 const readRun=async(id:string,scope:ReturnType<typeof captureAuthScope>)=>{const value=FleetRunSchema.parse(await apiFetch(`/api/fleet/runs/${id}`,{},scope));if(value.id!==id||value.companyId!==run.companyId)throw new Error("Cargo run scope could not be verified.");return value;};
 async function list(scope:ReturnType<typeof captureAuthScope>){const data=await apiFetch<{runId:string;transfers:unknown[]}>(`/api/fleet/runs/${run.id}/cargo-transfers`,{},scope);if(data.runId!==run.id)throw new Error("Cargo transfer scope could not be verified.");const values=data.transfers.map(v=>FleetCargoTransferSchema.parse(v));if(values.some(v=>v.companyId!==run.companyId||![v.sourceRunId,v.targetRunId].includes(run.id)))throw new Error("Cargo transfer scope could not be verified.");return values;}
 async function read(){if(disabled||busy)return;setBusy(true);setError("");const scope=captureAuthScope();try{const values=await list(scope);if(alive.current&&isAuthScopeCurrent(scope))setRecords(values);}catch(e){if(alive.current){setRecords([]);setError(e instanceof Error?e.message:"Cargo read unavailable.");}}finally{if(alive.current)setBusy(false);}}
 async function chooseTarget(){if(locked||!canDispatch)return;setBusy(true);setError("");setTarget(null);const scope=captureAuthScope();try{if(!FleetRunSchema.shape.id.safeParse(targetId.trim()).success)throw new Error("Enter the exact authorized recipient run ID.");const value=await readRun(targetId.trim(),scope);if(value.id===run.id||value.status!=="in_progress"||value.phase!=="paused")throw new Error("Recipient must be a distinct paused active run.");if(alive.current&&isAuthScopeCurrent(scope)){setTarget(value);setDeliveryId("");}}catch(e){if(alive.current)setError(e instanceof Error?e.message:"Recipient read unavailable.");}finally{if(alive.current)setBusy(false);}}
 function matches(value:FleetCargoTransfer,input:Proposal){return value.companyId===run.companyId&&value.sourceRunId===input.sourceRunId&&value.targetRunId===input.targetRunId&&value.sourceLoadId===input.sourceLoadId&&value.targetLoadId===input.targetLoadId&&value.siteId===input.siteId&&value.targetDeliveryStopId===input.targetDeliveryStopId&&value.quantity===input.quantity&&value.reason===input.reason;}
 async function send(exact:Pending,retry=false,started=false){if(disabled||(busy&&!started))return;setPending(exact);setBusy(true);setError("");setSaved(false);const scope=captureAuthScope();try{
  let result:FleetCargoTransfer;
  if(exact.kind==="propose"){
   const prior=retry?(await list(scope)).find(v=>v.events.some(e=>e.operationId===exact.body.operationId)):undefined;
   result=prior??FleetCargoTransferSchema.parse(await apiFetch("/api/fleet/cargo-transfers",{method:"POST",body:JSON.stringify(exact.body)},scope));
   if(!matches(result,exact.body))throw new Error("Cargo proposal outcome needs verification.");
  }else{
   const current=retry?FleetCargoTransferSchema.parse(await apiFetch(`/api/fleet/cargo-transfers/${exact.id}`,{},scope)):null;
   result=current?.events.some(e=>e.operationId===exact.body.operationId)?current:FleetCargoTransferSchema.parse(await apiFetch(`/api/fleet/cargo-transfers/${exact.id}/actions`,{method:"POST",body:JSON.stringify(exact.body)},scope));
   if(result.id!==exact.id||result.companyId!==run.companyId||![result.sourceRunId,result.targetRunId].includes(run.id))throw new Error("Cargo action outcome needs verification.");
  }
  if(!result.events.some(e=>e.operationId===exact.body.operationId))throw new Error("Cargo operation outcome needs verification.");
  if(alive.current&&isAuthScopeCurrent(scope)){setRecords(values=>[...values.filter(v=>v.id!==result.id),result]);setPending(null);setSaved(true);onChanged();}
 }catch(e){if(alive.current&&isAuthScopeCurrent(scope)){setError(e instanceof Error?e.message:"Cargo outcome needs verification.");const status=(e as {status?:number}).status;if(status&&status<500){setPending(null);setTarget(null);setRecords([]);}}}finally{if(alive.current)setBusy(false);}}
 function propose(){if(locked||!canDispatch||!target)return;const load=run.loads.find(v=>v.id===sourceLoadId&&!v.deliveredAt&&!v.transferOut);const targetStop=target.stops.find(v=>v.id===target.currentStopId);const sourceStop=run.stops.find(v=>v.id===run.currentStopId);if(!load||run.status!=="in_progress"||run.phase!=="paused"||targetStop?.kind!=="pickup"||sourceStop?.siteId!==targetStop.siteId){setError("Both runs must be paused at the same site with an undelivered source load.");return;}
  const input=FleetCargoTransferInputSchema.safeParse({operationId:Crypto.randomUUID(),sourceRunId:run.id,targetRunId:target.id,sourceExpectedVersion:run.version,targetExpectedVersion:target.version,sourceLoadId:load.id,targetLoadId:Crypto.randomUUID(),siteId:sourceStop.siteId,targetDeliveryStopId:deliveryId,quantity:load.quantity,reason});if(!input.success){setError("Select a later recipient delivery stop and explain the full-load transfer.");return;}void send({kind:"propose",body:input.data});}
 async function action(record:FleetCargoTransfer,value:Action["action"]){if(locked||!record.allowedActions.includes(value))return;setBusy(true);setError("");const scope=captureAuthScope();try{const current=FleetCargoTransferSchema.parse(await apiFetch(`/api/fleet/cargo-transfers/${record.id}`,{},scope));if(current.id!==record.id||current.companyId!==run.companyId||![current.sourceRunId,current.targetRunId].includes(run.id)||!current.allowedActions.includes(value))throw new Error("Current cargo action permission is required.");const sourceVersion=value==="cancel"?(await readRun(current.sourceRunId,scope)).version:current.sourceRunVersion;const targetVersion=value==="cancel"?(await readRun(current.targetRunId,scope)).version:current.targetRunVersion;const exact=FleetCargoTransferActionSchema.parse({operationId:Crypto.randomUUID(),expectedVersion:current.version,sourceExpectedVersion:sourceVersion,targetExpectedVersion:targetVersion,action:value,notes});if(!alive.current||!isAuthScopeCurrent(scope))return;void send({kind:"action",id:record.id,body:exact},false,true);}catch(e){if(alive.current)setError(e instanceof Error?e.message:"Cargo action unavailable.");setBusy(false);}}
 return <View style={{gap:8}}><Text>{copy("Fleet cargo handoff")}</Text><Text>{copy("Online only. Both drivers acknowledge their own side; permitted dispatch completes the recorded transfer. User reports do not verify physical handoff or change Inventory custody.")}</Text>
 <TogglePillButton disabled={disabled||busy} onPress={()=>void read()}>{copy("Read run cargo transfers")}</TogglePillButton>
 {records.map(record=><View key={record.id}><Text>{record.commodity} · {record.quantity} {record.unit} · {copy(record.status)}</Text><Text>{record.reason}</Text><Text>{copy("Original manifest")}: {record.originalCapture.manifestReference} · {record.originalCapture.recordedAt}</Text><Text>{copy("Source driver acknowledgement")}: {record.sourceAcknowledgedBy??copy("pending")}</Text><Text>{copy("Recipient driver acknowledgement")}: {record.targetAcknowledgedBy??copy("pending")}</Text>{record.allowedActions.map(value=><TogglePillButton key={value} disabled={locked||!notes.trim()} onPress={()=>void action(record,value)}>{copy(value)}</TogglePillButton>)}</View>)}
 {records.some(v=>v.allowedActions.length>0)&&<TextInput accessibilityLabel={copy("Cargo action notes")} editable={!locked} value={notes} onChangeText={setNotes}/>}
 {canDispatch&&run.status==="in_progress"&&run.phase==="paused"&&<><TextInput accessibilityLabel={copy("Recipient run ID")} editable={!locked} value={targetId} onChangeText={value=>{setTargetId(value);setTarget(null);}}/><TogglePillButton disabled={locked} onPress={()=>void chooseTarget()}>{copy("Read authorized recipient run")}</TogglePillButton>
 {run.loads.filter(load=>!load.deliveredAt&&!load.transferOut).map(load=><TogglePillButton key={load.id} disabled={locked} solid={sourceLoadId===load.id} onPress={()=>setSourceLoadId(load.id)}>{load.commodity} · {load.quantity} {load.unit} · {load.manifestReference}</TogglePillButton>)}
 {target&&<><Text>{target.title} · {copy("version")} {target.version}</Text>{target.stops.filter(stop=>stop.kind==="delivery"&&stop.sequence>(target.stops.find(v=>v.id===target.currentStopId)?.sequence??Infinity)).map(stop=><TogglePillButton key={stop.id} disabled={locked} solid={deliveryId===stop.id} onPress={()=>setDeliveryId(stop.id)}>{stop.sequence+1}. {copy(stop.kind)} · {target.labels?.sites.find(v=>v.siteId===stop.siteId)?.name??stop.siteId}</TogglePillButton>)}</>}
 <TextInput accessibilityLabel={copy("Cargo transfer reason")} editable={!locked} value={reason} onChangeText={setReason}/><TogglePillButton disabled={locked||!target||!sourceLoadId||!deliveryId||!reason.trim()} onPress={propose}>{copy("Propose full-load cargo handoff")}</TogglePillButton></>}
 {pending&&<><Text>{copy("Cargo operation outcome is unresolved. Do not repeat with new IDs or queue it offline.")}</Text><TogglePillButton disabled={disabled||busy} onPress={()=>void send(pending,true)}>{copy("Verify and retry exact cargo operation")}</TogglePillButton></>}{saved&&<Text>{copy("Cargo operation saved and verified; physical handoff remains unverified.")}</Text>}{!!error&&<Text accessibilityRole="alert">{copy(error)}</Text>}
 </View>;
}
