import React,{useEffect,useRef,useState} from "react";
import {Text,TextInput,View} from "react-native";
import * as Crypto from "expo-crypto";
import {FleetRunSchema,FleetReplacementSchema,FleetReplacementInputSchema,FleetReplacementActionSchema,type FleetReplacement as Record,type FleetRun,type FleetResources} from "@workspace/api-zod";
import {apiFetch} from "@/lib/api";
import {captureAuthScope,isAuthScopeCurrent} from "@/lib/auth";
import {useFleetCopy} from "@/lib/fleet-copy";
import TogglePillButton from "@/components/TogglePillButton";
type Proposal=ReturnType<typeof FleetReplacementInputSchema.parse>;
type Action=ReturnType<typeof FleetReplacementActionSchema.parse>;
type Pending={kind:"propose";body:Proposal}|{kind:"action";id:string;body:Action};
export default function FleetReplacement({run,canDispatch,equipment,disabled,onChanged}:{run:FleetRun;canDispatch:boolean;equipment:FleetResources["equipment"];disabled:boolean;onChanged:()=>void}) {
 const copy=useFleetCopy(),[records,setRecords]=useState<Record[]>([]),[vehicle,setVehicle]=useState(""),[trailer,setTrailer]=useState<string|null>(run.trailerAssetId),[reason,setReason]=useState(""),[notes,setNotes]=useState("");
 const [pending,setPending]=useState<Pending|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);const locked=disabled||busy||!!pending;
 async function list(scope:ReturnType<typeof captureAuthScope>){const value=await apiFetch<{runId:string;replacements:unknown[]}>(`/api/fleet/runs/${run.id}/replacements`,{},scope);if(value.runId!==run.id)throw new Error("Replacement scope could not be verified.");const values=value.replacements.map(v=>FleetReplacementSchema.parse(v));if(values.some(v=>v.runId!==run.id||v.companyId!==run.companyId))throw new Error("Replacement scope could not be verified.");return values;}
 async function read(){if(disabled||busy)return;setBusy(true);setError("");const scope=captureAuthScope();try{const values=await list(scope);if(alive.current&&isAuthScopeCurrent(scope))setRecords(values);}catch(e){if(alive.current){setRecords([]);setError(e instanceof Error?e.message:"Replacement read unavailable.");}}finally{if(alive.current)setBusy(false);}}
 async function send(exact:Pending,retry=false,started=false){if(disabled||(busy&&!started))return;setPending(exact);setBusy(true);setError("");setSaved(false);const scope=captureAuthScope();try{
  const known=retry?(await list(scope)).find(v=>v.events.some(e=>e.operationId===exact.body.operationId)):undefined;
  const path=exact.kind==="propose"?`/api/fleet/runs/${run.id}/replacements`:`/api/fleet/runs/${run.id}/replacements/${exact.id}/actions`;
  const result=known??FleetReplacementSchema.parse(await apiFetch(path,{method:"POST",body:JSON.stringify(exact.body)},scope));
  if(result.runId!==run.id||result.companyId!==run.companyId||!result.events.some(e=>e.operationId===exact.body.operationId)|| (exact.kind==="action"&&result.id!==exact.id)|| (exact.kind==="propose"&&(result.vehicleAssetId!==exact.body.vehicleAssetId||result.trailerAssetId!==exact.body.trailerAssetId||result.reason!==exact.body.reason)))throw new Error("Replacement outcome needs verification.");
  if(alive.current&&isAuthScopeCurrent(scope)){setPending(null);setSaved(true);setRecords(values=>[...values.filter(v=>v.id!==result.id),result]);onChanged();}
 }catch(e){if(alive.current&&isAuthScopeCurrent(scope)){setError(e instanceof Error?e.message:"Replacement outcome needs verification.");const status=(e as {status?:number}).status;if(status&&status<500){setPending(null);setRecords([]);}}}finally{if(alive.current)setBusy(false);}}
 function propose(){if(locked||!canDispatch||run.status!=="in_progress"||run.phase!=="paused")return;const parsed=FleetReplacementInputSchema.safeParse({operationId:Crypto.randomUUID(),expectedVersion:run.version,vehicleAssetId:vehicle,trailerAssetId:trailer,reason});if(!parsed.success){setError("Choose replacement equipment and explain the exchange.");return;}void send({kind:"propose",body:parsed.data});}
 async function action(record:Record,value:Action["action"]){if(locked||!record.allowedActions.includes(value))return;setBusy(true);setError("");const scope=captureAuthScope();try{const current=(await list(scope)).find(v=>v.id===record.id);if(!current?.allowedActions.includes(value))throw new Error("Current replacement action permission is required.");let version=current.runVersion;if(value==="cancel"){const fresh=FleetRunSchema.parse(await apiFetch(`/api/fleet/runs/${run.id}`,{},scope));if(fresh.id!==run.id||fresh.companyId!==run.companyId)throw new Error("Replacement scope could not be verified.");version=fresh.version;}const parsed=FleetReplacementActionSchema.parse({operationId:Crypto.randomUUID(),expectedVersion:current.version,runExpectedVersion:version,action:value,notes});if(alive.current&&isAuthScopeCurrent(scope))void send({kind:"action",id:record.id,body:parsed},false,true);}catch(e){if(alive.current)setError(e instanceof Error?e.message:"Explain the replacement action.");setBusy(false);}}
 return <View style={{gap:8}}><Text>{copy("Fleet equipment replacement")}</Text><Text>{copy("Online only. Inventory must already record the assigned driver's custody. Only the assigned driver accepts; the run remains paused until a fresh replacement inspection and distance meter are reported. This does not verify a physical exchange or change Inventory custody.")}</Text>
 <TogglePillButton disabled={disabled||busy} onPress={()=>void read()}>{copy("Read run replacement proposals")}</TogglePillButton>
 {run.activeReplacement&&<Text>{copy("Replacement accepted: fresh inspection and distance meter required before resume.")}</Text>}
 {records.map(record=><View key={record.id}><Text>{copy(record.status)} · {record.vehicleAssetId} · {record.trailerAssetId??copy("No trailer")}</Text><Text>{record.reason}</Text>{record.allowedActions.map(value=><TogglePillButton key={value} disabled={locked||!notes.trim()} onPress={()=>action(record,value)}>{copy(value==="accept"?"Accept assigned equipment replacement":"Cancel equipment replacement proposal")}</TogglePillButton>)}</View>)}
 {records.some(v=>v.allowedActions.length>0)&&<TextInput accessibilityLabel={copy("Replacement action notes")} editable={!locked} value={notes} onChangeText={setNotes}/>}
 {canDispatch&&run.status==="in_progress"&&run.phase==="paused"&&<>{equipment.filter(v=>v.dispatchable).map(asset=><View key={asset.id}><Text>{asset.name} · {copy(asset.category)}</Text>{["truck","vehicle"].includes(asset.category)&&<TogglePillButton disabled={locked} solid={vehicle===asset.id} onPress={()=>setVehicle(asset.id)}>{copy("Replacement truck")}: {asset.name}</TogglePillButton>}{asset.category==="trailer"&&<TogglePillButton disabled={locked} solid={trailer===asset.id} onPress={()=>setTrailer(asset.id)}>{copy("Replacement trailer")}: {asset.name}</TogglePillButton>}</View>)}<TogglePillButton disabled={locked} solid={trailer===null} onPress={()=>setTrailer(null)}>{copy("No replacement trailer")}</TogglePillButton><TextInput accessibilityLabel={copy("Replacement reason")} editable={!locked} value={reason} onChangeText={setReason}/><TogglePillButton disabled={locked||!vehicle||!reason.trim()} onPress={propose}>{copy("Propose equipment replacement")}</TogglePillButton></>}
 {pending&&<><Text>{copy("Replacement outcome unresolved. Reuse the exact operation; do not queue it offline.")}</Text><TogglePillButton disabled={disabled||busy} onPress={()=>void send(pending,true)}>{copy("Verify and retry exact replacement operation")}</TogglePillButton></>}{saved&&<Text>{copy("Replacement operation saved and verified; physical exchange remains unverified.")}</Text>}{!!error&&<Text accessibilityRole="alert">{copy(error)}</Text>}
 </View>;
}
