// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/add-contact-modal/LogoCenteredTop.tsx": () => import("../components/mockups/add-contact-modal/LogoCenteredTop.tsx"),
  "./components/mockups/add-contact-modal/Pill.tsx": () => import("../components/mockups/add-contact-modal/Pill.tsx"),
  "./components/mockups/askv-orb/Badge.tsx": () => import("../components/mockups/askv-orb/Badge.tsx"),
  "./components/mockups/askv-orb/Halo.tsx": () => import("../components/mockups/askv-orb/Halo.tsx"),
  "./components/mockups/askv-orb/Orbit.tsx": () => import("../components/mockups/askv-orb/Orbit.tsx"),
  "./components/mockups/askv-orb/Rings.tsx": () => import("../components/mockups/askv-orb/Rings.tsx"),
  "./components/mockups/askv-orb/Sparkles.tsx": () => import("../components/mockups/askv-orb/Sparkles.tsx"),
  "./components/mockups/field-portal/Home.tsx": () => import("../components/mockups/field-portal/Home.tsx"),
  "./components/mockups/field-portal/Login.tsx": () => import("../components/mockups/field-portal/Login.tsx"),
  "./components/mockups/field-portal/NewTicket.tsx": () => import("../components/mockups/field-portal/NewTicket.tsx"),
  "./components/mockups/field-portal/VendorFieldEmployeeLogins.tsx": () => import("../components/mockups/field-portal/VendorFieldEmployeeLogins.tsx"),
  "./components/mockups/hotlist-buttons/Default.tsx": () => import("../components/mockups/hotlist-buttons/Default.tsx"),
  "./components/mockups/ipad-vendor-partner/PartnerSites.tsx": () => import("../components/mockups/ipad-vendor-partner/PartnerSites.tsx"),
  "./components/mockups/ipad-vendor-partner/VendorCrewMap.tsx": () => import("../components/mockups/ipad-vendor-partner/VendorCrewMap.tsx"),
  "./components/mockups/ipad-vendor-partner/VendorDashboard.tsx": () => import("../components/mockups/ipad-vendor-partner/VendorDashboard.tsx"),
  "./components/mockups/ipad-vendor-partner/VendorTickets.tsx": () => import("../components/mockups/ipad-vendor-partner/VendorTickets.tsx"),
  "./components/mockups/post-job-button/Default.tsx": () => import("../components/mockups/post-job-button/Default.tsx"),
  "./components/mockups/sidebar-nav/Default.tsx": () => import("../components/mockups/sidebar-nav/Default.tsx"),
  "./components/mockups/sphere-back-button/Default.tsx": () => import("../components/mockups/sphere-back-button/Default.tsx"),
  "./components/mockups/ticket-stepper/Default.tsx": () => import("../components/mockups/ticket-stepper/Default.tsx"),
  "./components/mockups/toggle-pill-2/Winchester.tsx": () => import("../components/mockups/toggle-pill-2/Winchester.tsx"),
  "./components/mockups/vndrly-mobile-dark/IndustrialNavy.tsx": () => import("../components/mockups/vndrly-mobile-dark/IndustrialNavy.tsx"),
  "./components/mockups/vndrly-mobile-dark/OledBlack.tsx": () => import("../components/mockups/vndrly-mobile-dark/OledBlack.tsx"),
  "./components/mockups/vndrly-mobile-dark/SlateCharcoal.tsx": () => import("../components/mockups/vndrly-mobile-dark/SlateCharcoal.tsx")
};
