const colors = {
  light: {
    text: "#1a1d23",
    tint: "#1a1d23",
    background: "#ffffff",
    foreground: "#1a1d23",
    card: "#fafafa",
    cardForeground: "#1a1d23",
    primary: "#1a1d23",
    primaryForeground: "#ffffff",
    secondary: "#f4f4f5",
    secondaryForeground: "#1a1d23",
    muted: "#f4f4f5",
    mutedForeground: "#6b7280",
    accent: "#f4f4f5",
    accentForeground: "#1a1d23",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e7eb",
    input: "#e5e7eb",
  },
  dark: {
    text: "#ececec",
    tint: "#ececec",
    background: "#3a3d42",
    foreground: "#ffffff",
    card: "#1c1c1e",
    cardForeground: "#ececec",
    primary: "#ececec",
    primaryForeground: "#1a1d23",
    secondary: "#2c2c2c",
    secondaryForeground: "#ececec",
    muted: "#2c2c2c",
    mutedForeground: "#a3a3a3",
    accent: "#2c2c2c",
    accentForeground: "#ececec",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3a3a3a",
    input: "#3a3a3a",
  },
  radius: 10,
};

export default colors;
