import * as SecureStore from "expo-secure-store";
import * as ImagePicker from "expo-image-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as Crypto from "expo-crypto";
import {z} from "zod/v4";
import {FleetEvidenceInputSchema,type FleetEvidence,type FleetOverview,type FleetRun} from "@workspace/api-zod";
import {apiFetch,getApiBase} from "./api";
import {captureAuthScope,isAuthScopeCurrent,subscribeToken,subscribeUser,type AuthScope} from "./auth";
import {fleetOfflineByteLength} from "./fleet-offline";
import {progressFleetEvidenceUpload,type FleetEvidencePending} from "./fleet-evidence-device";
import type {FleetVerifiedAccount} from "./fleet-phone-location";
export function fleetPrivateUploadUrl(raw:string,objectPath:string,base:string){const url=new URL(raw,base);const origin=new URL(base).origin,id=objectPath.split("/").at(-1);if(url.origin!==origin||url.pathname!==`/api/storage/upload/${id}`||!["http:","https:"].includes(url.protocol))throw new Error("Private upload destination could not be verified.");return url.href;}
const KEY="vndrly.fleet-evidence.pending",CHUNK=400,MAX_CHUNKS=41,MAX_BYTES=16*1024;
const options={keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY};
const schema=z.object({account:z.object({userId:z.number().int().positive(),companyId:z.number().int().positive(),membershipId:z.number().int().positive(),sessionVersion:z.number().int().nonnegative()}).strict(),runId:z.uuid(),vehicleAssetId:z.uuid(),trailerAssetId:z.uuid().nullable(),asset:z.object({uri:z.string().max(1000),contentType:z.enum(["image/jpeg","image/png","image/webp"]),size:z.number().int().positive().max(10*1024*1024),sha256:z.string().regex(/^[0-9a-f]{64}$/)}).strict(),input:FleetEvidenceInputSchema.omit({objectPath:true}),upload:z.object({uploadURL:z.string().min(1).max(3000),objectPath:FleetEvidenceInputSchema.shape.objectPath}).strict().nullable(),uploaded:z.boolean(),finalized:z.boolean()}).strict();
let generation=0,serial:Promise<unknown>=Promise.resolve();
function exclusive<T>(work:()=>Promise<T>):Promise<T>{const result=serial.then(work,work);serial=result.catch(()=>undefined);return result;}
function meta(raw:string|null){const value=JSON.parse(raw??'{"slot":1,"count":0}');if(![0,1].includes(value.slot)||!Number.isInteger(value.count)||value.count<0||value.count>MAX_CHUNKS)throw new Error("Evidence pending storage is invalid.");return value as {slot:0|1;count:number};}
function localUri(value:FleetEvidencePending){if(!FileSystem.cacheDirectory)throw new Error("Private device cache is unavailable.");return `${FileSystem.cacheDirectory}fleet-evidence-${value.input.evidenceId}.${value.asset.contentType==="image/png"?"png":value.asset.contentType==="image/webp"?"webp":"jpg"}`;}
async function read(){const raw=await SecureStore.getItemAsync(`${KEY}.meta`,options);if(!raw)return null;const m=meta(raw),parts=await Promise.all(Array.from({length:m.count},(_,i)=>SecureStore.getItemAsync(`${KEY}.${m.slot}.${i}`,options)));if(parts.some(part=>part===null))throw new Error("Evidence pending storage is incomplete.");const text=parts.join("");if(fleetOfflineByteLength(text)>MAX_BYTES)throw new Error("Evidence pending storage is oversized.");const value=schema.parse(JSON.parse(text));if(value.asset.uri!==localUri(value))throw new Error("Evidence device cache scope is invalid.");return value;}
async function store(value:FleetEvidencePending,current:()=>boolean){const raw=JSON.stringify(schema.parse(value));if(fleetOfflineByteLength(raw)>MAX_BYTES)throw new Error("Evidence pending metadata exceeds device capacity.");const previous=meta(await SecureStore.getItemAsync(`${KEY}.meta`,options)),slot=previous.slot===0?1:0,count=Math.ceil(raw.length/CHUNK);if(count>MAX_CHUNKS)throw new Error("Evidence pending metadata exceeds device capacity.");for(let i=0;i<count;i++){if(!current())throw new Error("Evidence account context changed.");await SecureStore.setItemAsync(`${KEY}.${slot}.${i}`,raw.slice(i*CHUNK,(i+1)*CHUNK),options);}if(!current())throw new Error("Evidence account context changed.");await SecureStore.setItemAsync(`${KEY}.meta`,JSON.stringify({slot,count}),options);for(let i=0;i<previous.count;i++)await SecureStore.deleteItemAsync(`${KEY}.${previous.slot}.${i}`,options);}
async function remove(){let pending:FleetEvidencePending|null=null;try{pending=await read();}catch{/* Invalid metadata cannot authorize arbitrary file deletion. */}for(const slot of [0,1])for(let i=0;i<MAX_CHUNKS;i++)await SecureStore.deleteItemAsync(`${KEY}.${slot}.${i}`,options);await SecureStore.deleteItemAsync(`${KEY}.meta`,options);if(pending && pending.asset.uri===localUri(pending))await FileSystem.deleteAsync(pending.asset.uri,{idempotent:true});}
export function clearFleetEvidencePending(){generation++;return exclusive(remove);}
export function readFleetEvidencePending(){return exclusive(read);}
async function authority(runId:string,scope:AuthScope){const overview=await apiFetch<FleetOverview>("/api/fleet/overview",{},scope);if(!overview.accountScope||!overview.capabilities.canDrive)throw new Error("Current own-driver Fleet evidence authority is required.");const run=await apiFetch<FleetRun>(`/api/fleet/runs/${runId}`,{},scope);return {account:overview.accountScope,run};}
async function hash(uri:string){const {File}=await import("expo-file-system");const file=new File(uri);if(file.size<=0||file.size>10*1024*1024)throw new Error("Choose a supported image no larger than 10 MB.");const bytes=await file.bytes(),digest=await Crypto.digest(Crypto.CryptoDigestAlgorithm.SHA256,bytes);return {size:bytes.byteLength,sha256:[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,"0")).join("")};}
export async function captureFleetEvidence(account:FleetVerifiedAccount,run:FleetRun,input:{kind:FleetEvidencePending["input"]["kind"];notes:string;stopId?:string;loadId?:string},source:"camera"|"library") {
 const request=generation,scope=captureAuthScope(),current=()=>request===generation&&isAuthScopeCurrent(scope);
 return exclusive(async()=>{
  if(await read())throw new Error("A device evidence upload is unresolved. Verify or discard it before capturing another image.");
  const fresh=await authority(run.id,scope),a=fresh.account;
  if(!current()||a.userId!==account.userId||a.companyId!==account.companyId||a.membershipId!==account.membershipId||a.sessionVersion!==account.sessionVersion||fresh.run.id!==run.id||fresh.run.companyId!==account.companyId||fresh.run.driverUserId!==account.userId||fresh.run.vehicleAssetId!==run.vehicleAssetId||fresh.run.trailerAssetId!==run.trailerAssetId||!["acknowledged","in_progress"].includes(fresh.run.status))throw new Error("Current own-driver Fleet evidence authority is required.");
  const permission=source==="camera"?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(permission.status!=="granted"||!current())throw new Error("Image permission or account verification is unavailable.");
  const image=source==="camera"?await ImagePicker.launchCameraAsync({quality:0.6,allowsEditing:false}):await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:0.6,allowsEditing:false});
  if(!current())throw new Error("Evidence account context changed.");if(image.canceled||!image.assets?.[0])return null;
  const asset=image.assets[0],contentType=asset.mimeType??"image/jpeg";if(!["image/jpeg","image/png","image/webp"].includes(contentType))throw new Error("Choose a JPEG, PNG or WebP image no larger than 10 MB.");
  const id=Crypto.randomUUID(),pending:FleetEvidencePending={account,runId:run.id,vehicleAssetId:run.vehicleAssetId,trailerAssetId:run.trailerAssetId,asset:{uri:"",contentType:contentType as FleetEvidencePending["asset"]["contentType"],size:1,sha256:"0".repeat(64)},input:{...input,operationId:Crypto.randomUUID(),evidenceId:id,expectedVersion:fresh.run.version,...(source==="camera"?{capturedAt:new Date().toISOString()}:{})},upload:null,uploaded:false,finalized:false};pending.asset.uri=localUri(pending);
  FleetEvidenceInputSchema.omit({objectPath:true}).parse(pending.input);
  try{await FileSystem.copyAsync({from:asset.uri,to:pending.asset.uri});if(!current())throw new Error("Evidence account context changed.");const actual=await hash(pending.asset.uri);pending.asset={...pending.asset,...actual};if(!current())throw new Error("Evidence account context changed.");await store(pending,current);return pending;}
  catch(error){await FileSystem.deleteAsync(pending.asset.uri,{idempotent:true});throw error;}
 });
}
export async function submitFleetEvidencePending():Promise<FleetEvidence>{
 const request=generation,scope=captureAuthScope(),current=()=>request===generation&&isAuthScopeCurrent(scope);
 return exclusive(async()=>{
  const pending=await read();if(!pending)throw new Error("No captured evidence is pending.");
  const result=await progressFleetEvidenceUpload(pending,{contextCurrent:current,readCurrent:()=>authority(pending.runId,scope),readEvidence:()=>apiFetch(`/api/fleet/runs/${pending.runId}/evidence`,{},scope),persist:value=>store(value,current),reserve:(name,size,contentType)=>apiFetch("/api/storage/uploads/request-url",{method:"POST",body:JSON.stringify({name,size,contentType})},scope),put:async value=>{const actual=await hash(value.asset.uri);if(actual.size!==value.asset.size||actual.sha256!==value.asset.sha256)throw new Error("Captured image bytes changed. This upload was refused.");if(!current())throw new Error("Evidence account context changed.");const blob=await fetch(value.asset.uri).then(response=>response.blob());if(!current())throw new Error("Evidence account context changed.");const url=fleetPrivateUploadUrl(value.upload!.uploadURL,value.upload!.objectPath,getApiBase());const response=await fetch(url,{method:"PUT",headers:{"content-type":value.asset.contentType},body:blob});if(!response.ok)throw new Error("Private evidence upload is unverified. Retry the exact captured image.");},finalize:uploadURL=>apiFetch("/api/storage/uploads/finalize",{method:"POST",body:JSON.stringify({objectURL:uploadURL,visibility:"private"})},scope),associate:input=>apiFetch(`/api/fleet/runs/${pending.runId}/evidence`,{method:"POST",body:JSON.stringify(input)},scope)});
  if(!current())throw new Error("Evidence account context changed.");await remove();return result;
 });
}
let observed=captureAuthScope();function changed(){if(!isAuthScopeCurrent(observed)){observed=captureAuthScope();void clearFleetEvidencePending().catch(()=>undefined);}}subscribeToken(changed);subscribeUser(changed);
