import {FleetEvidenceInputSchema,FleetEvidenceSchema,type FleetEvidence,type FleetRun} from "@workspace/api-zod";
import type {z} from "zod/v4";
import type {FleetVerifiedAccount} from "./fleet-phone-location";
export type FleetEvidencePending={account:FleetVerifiedAccount;runId:string;vehicleAssetId:string;trailerAssetId:string|null;asset:{uri:string;contentType:"image/jpeg"|"image/png"|"image/webp";size:number;sha256:string};input:Omit<z.infer<typeof FleetEvidenceInputSchema>,"objectPath">;upload:{uploadURL:string;objectPath:string}|null;uploaded:boolean;finalized:boolean};
type Dependencies={contextCurrent():boolean;readCurrent():Promise<{account:FleetVerifiedAccount;run:FleetRun}>;readEvidence():Promise<{runId:string;evidence:FleetEvidence[]}>;persist(value:FleetEvidencePending):Promise<void>;reserve(name:string,size:number,contentType:string):Promise<{uploadURL:string;objectPath:string}>;put(pending:FleetEvidencePending):Promise<void>;finalize(uploadURL:string):Promise<void>;associate(input:z.infer<typeof FleetEvidenceInputSchema>):Promise<unknown>;};
/** Private upload stages and Fleet association are separate; neither preparation nor PUT means saved Fleet evidence. */
export async function progressFleetEvidenceUpload(initial:FleetEvidencePending,deps:Dependencies):Promise<FleetEvidence> {
 let value=initial;
 const check=()=>{if(!deps.contextCurrent())throw Object.assign(new Error("Evidence account context changed. No new association was made."),{status:403});};
 async function authorize(){check();const current=await deps.readCurrent();check();const a=current.account,b=value.account,r=current.run;if(a.userId!==b.userId||a.companyId!==b.companyId||a.membershipId!==b.membershipId||a.sessionVersion!==b.sessionVersion||r.id!==value.runId||r.companyId!==b.companyId||r.driverUserId!==b.userId||r.vehicleAssetId!==value.vehicleAssetId||r.trailerAssetId!==value.trailerAssetId)throw Object.assign(new Error("Evidence account or equipment assignment changed."),{status:403});return r;}
 const current=await authorize();
 const list=await deps.readEvidence();check();if(list.runId!==value.runId)throw new Error("Evidence readback scope could not be verified.");
 const saved=list.evidence.find(item=>item.operationId===value.input.operationId);
 if(saved){const parsed=FleetEvidenceSchema.parse(saved);if(parsed.runId!==value.runId||parsed.companyId!==value.account.companyId||parsed.recordedByUserId!==value.account.userId||parsed.evidenceId!==value.input.evidenceId||parsed.sha256!==value.asset.sha256||parsed.size!==value.asset.size||parsed.contentType!==value.asset.contentType||parsed.capturedAt!==(value.input.capturedAt??null)||parsed.kind!==value.input.kind||parsed.notes!==value.input.notes||parsed.stopId!==(value.input.stopId??null)||parsed.loadId!==(value.input.loadId??null))throw new Error("Evidence readback does not match the exact pending upload.");return parsed;}
 if(!["acknowledged","in_progress"].includes(current.status)||current.version!==value.input.expectedVersion)throw Object.assign(new Error("The run changed. This evidence remains unassociated; no version was silently rebased."),{status:409});
 if(value.asset.size<=0||value.asset.size>10*1024*1024||!/^image\/(jpeg|png|webp)$/.test(value.asset.contentType)||!/^[0-9a-f]{64}$/.test(value.asset.sha256))throw new Error("Choose a supported image no larger than 10 MB.");
 if(!value.upload){const upload=await deps.reserve(`${value.input.evidenceId}.${value.asset.contentType==="image/png"?"png":value.asset.contentType==="image/webp"?"webp":"jpg"}`,value.asset.size,value.asset.contentType);check();FleetEvidenceInputSchema.parse({...value.input,objectPath:upload.objectPath});value={...value,upload};await deps.persist(value);check();}
 if(!value.uploaded){await authorize();await deps.put(value);check();value={...value,uploaded:true};await deps.persist(value);check();}
 if(!value.finalized){await authorize();await deps.finalize(value.upload!.uploadURL);check();value={...value,finalized:true};await deps.persist(value);check();}
 const fresh=await authorize();if(fresh.version!==value.input.expectedVersion||!["acknowledged","in_progress"].includes(fresh.status))throw Object.assign(new Error("The run changed. This evidence remains unassociated; no version was silently rebased."),{status:409});
 const result=FleetEvidenceSchema.parse(await deps.associate(FleetEvidenceInputSchema.parse({...value.input,objectPath:value.upload!.objectPath})));check();
 if(result.runId!==value.runId||result.companyId!==value.account.companyId||result.recordedByUserId!==value.account.userId||result.evidenceId!==value.input.evidenceId||result.operationId!==value.input.operationId||result.sha256!==value.asset.sha256||result.size!==value.asset.size||result.contentType!==value.asset.contentType||result.capturedAt!==(value.input.capturedAt??null)||result.stopId!==(value.input.stopId??null)||result.loadId!==(value.input.loadId??null)||result.kind!==value.input.kind||result.notes!==value.input.notes||result.runVersion!==value.input.expectedVersion+1)throw new Error("Evidence save outcome needs verification.");return result;
}
