import { boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import { workHubChannelsTable } from "./workHubChannels";

const ownership = { ownerOrgType: text("owner_org_type").notNull(), ownerOrgId: integer("owner_org_id").notNull() };
export const workHubTasksTable = pgTable("work_hub_tasks", {
  id: uuid("id").primaryKey().defaultRandom(), ...ownership, channelId: uuid("channel_id").references(() => workHubChannelsTable.id, { onDelete: "cascade" }),
  title: text("title").notNull(), description: text("description"), status: text("status").notNull().default("open"), priority: text("priority").notNull().default("normal"),
  assigneeUserId: integer("assignee_user_id").references(() => usersTable.id), createdById: integer("created_by_id").notNull().references(() => usersTable.id), dueAt: timestamp("due_at", { withTimezone: true }),
  recurrence: jsonb("recurrence").$type<Record<string, unknown>>(), version: integer("version").notNull().default(1), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ assigneeIdx: index("work_hub_tasks_assignee_idx").on(t.assigneeUserId, t.status, t.dueAt), ownerIdx: index("work_hub_tasks_owner_idx").on(t.ownerOrgType, t.ownerOrgId, t.updatedAt) }));
export const workHubTaskEventsTable = pgTable("work_hub_task_events", { id: uuid("id").primaryKey().defaultRandom(), taskId: uuid("task_id").notNull().references(() => workHubTasksTable.id, { onDelete: "cascade" }), actorUserId: integer("actor_user_id").references(() => usersTable.id), eventType: text("event_type").notNull(), detail: jsonb("detail").$type<Record<string, unknown>>(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const workHubChecklistTemplatesTable = pgTable("work_hub_checklist_templates", { id: uuid("id").primaryKey().defaultRandom(), ...ownership, name: text("name").notNull(), currentVersion: integer("current_version").notNull().default(1), definition: jsonb("definition").$type<unknown[]>().notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const workHubChecklistInstancesTable = pgTable("work_hub_checklist_instances", { id: uuid("id").primaryKey().defaultRandom(), templateId: uuid("template_id").notNull().references(() => workHubChecklistTemplatesTable.id), templateVersion: integer("template_version").notNull(), channelId: uuid("channel_id").references(() => workHubChannelsTable.id), assigneeUserId: integer("assignee_user_id").references(() => usersTable.id), snapshot: jsonb("snapshot").$type<unknown[]>().notNull(), responses: jsonb("responses").$type<Record<string, unknown>>().notNull().default({}), dueAt: timestamp("due_at", { withTimezone: true }), status: text("status").notNull().default("open"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const workHubFormTemplatesTable = pgTable("work_hub_form_templates", { id: uuid("id").primaryKey().defaultRandom(), ...ownership, name: text("name").notNull(), currentVersion: integer("current_version").notNull().default(1), definition: jsonb("definition").$type<unknown[]>().notNull(), recurrence: jsonb("recurrence").$type<Record<string, unknown>>(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const workHubFormInstancesTable = pgTable("work_hub_form_instances", { id: uuid("id").primaryKey().defaultRandom(), templateId: uuid("template_id").notNull().references(() => workHubFormTemplatesTable.id), templateVersion: integer("template_version").notNull(), channelId: uuid("channel_id").references(() => workHubChannelsTable.id), assigneeUserId: integer("assignee_user_id").references(() => usersTable.id), definitionSnapshot: jsonb("definition_snapshot").$type<unknown[]>().notNull(), dueAt: timestamp("due_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const workHubFormSubmissionsTable = pgTable("work_hub_form_submissions", { id: uuid("id").primaryKey().defaultRandom(), instanceId: uuid("instance_id").notNull().references(() => workHubFormInstancesTable.id), priorSubmissionId: uuid("prior_submission_id"), version: integer("version").notNull(), submittedById: integer("submitted_by_id").notNull().references(() => usersTable.id), values: jsonb("values").$type<Record<string, unknown>>().notNull(), submittedAt: timestamp("submitted_at", { withTimezone: true }).notNull().defaultNow() }, (t) => ({ versionUnique: uniqueIndex("work_hub_form_submission_version_unique").on(t.instanceId, t.version) }));
export const workHubAcknowledgementsTable = pgTable("work_hub_acknowledgements", { id: uuid("id").primaryKey().defaultRandom(), ...ownership, subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), subjectVersion: integer("subject_version").notNull(), userId: integer("user_id").notNull().references(() => usersTable.id), acknowledgementText: text("acknowledgement_text"), acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }).notNull().defaultNow() }, (t) => ({ uniqueAck: uniqueIndex("work_hub_acknowledgements_unique").on(t.subjectType, t.subjectId, t.subjectVersion, t.userId) }));
export const workHubApprovalRequestsTable = pgTable("work_hub_approval_requests", { id: uuid("id").primaryKey().defaultRandom(), ...ownership, channelId: uuid("channel_id").references(() => workHubChannelsTable.id), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), subjectVersion: integer("subject_version").notNull(), mode: text("mode").notNull().default("ordered"), status: text("status").notNull().default("pending"), requestedById: integer("requested_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const workHubApprovalStepsTable = pgTable("work_hub_approval_steps", { id: uuid("id").primaryKey().defaultRandom(), requestId: uuid("request_id").notNull().references(() => workHubApprovalRequestsTable.id, { onDelete: "cascade" }), stepOrder: integer("step_order").notNull(), approverUserId: integer("approver_user_id").notNull().references(() => usersTable.id), decision: text("decision"), comment: text("comment"), decidedAt: timestamp("decided_at", { withTimezone: true }) }, (t) => ({ uniqueStep: uniqueIndex("work_hub_approval_step_unique").on(t.requestId, t.stepOrder, t.approverUserId) }));
export const workHubAnnouncementsTable = pgTable("work_hub_announcements", { id: uuid("id").primaryKey().defaultRandom(), ...ownership, channelId: uuid("channel_id").references(() => workHubChannelsTable.id), title: text("title").notNull(), body: text("body").notNull(), urgency: text("urgency").notNull().default("normal"), acknowledgementRequired: boolean("acknowledgement_required").notNull().default(false), version: integer("version").notNull().default(1), publishedById: integer("published_by_id").notNull().references(() => usersTable.id), publishedAt: timestamp("published_at", { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp("expires_at", { withTimezone: true }), withdrawnAt: timestamp("withdrawn_at", { withTimezone: true }) });
export const workHubAnnouncementRecipientsTable = pgTable("work_hub_announcement_recipients", { id: uuid("id").primaryKey().defaultRandom(), announcementId: uuid("announcement_id").notNull().references(() => workHubAnnouncementsTable.id, { onDelete: "cascade" }), userId: integer("user_id").notNull().references(() => usersTable.id), viewedAt: timestamp("viewed_at", { withTimezone: true }), acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }) }, (t) => ({ uniqueRecipient: uniqueIndex("work_hub_announcement_recipient_unique").on(t.announcementId, t.userId) }));
