/** Fleet-specific copy kept together while the workspace evolves. */
const en = {
  workspace: "Fleet Ops",
  desk: "Fleet Desk",
  dispatch: "Dispatch",
  runs: "Runs",
  myDay: "My Day",
  myRun: "My Run",
  map: "Live Map",
  equipment: "Inventory",
  workHub: "Work Hub",
  fieldOps: "Field Ops",
  subtitle: "Authorized dispatch, assigned runs and recorded locations",
  refresh: "Refresh",
  loading: "Loading your authorized Fleet workspace…",
  denied:
    "Fleet access is unavailable for this company. Ask your company administrator to check your Fleet grants.",
  unavailable: "Fleet records could not be loaded. Refresh to try again.",
  fleet: "Fleet",
  site: "Site",
  status: "Status",
  all: "All",
  search: "Search run title",
  updated: "Updated",
  active: "Active runs",
  unassigned: "Unassigned runs",
  attention: "Needs attention",
  selected: "Selected run",
  noRuns: "No authorized runs match these filters.",
  noSelection: "Select a run from the map or list.",
  noLocations:
    "No authorized recorded positions are available. Run records remain available below.",
  mapHint:
    "Locations are observations, not proof of loading or delivery. Recorded times and freshness remain visible.",
  stops: "Ordered stops",
  loads: "Loads and manifests",
  events: "Saved activity",
  noLoads: "No load records saved.",
  noEvents: "No activity saved.",
  noStops: "No stops saved.",
  version: "Version",
  driver: "Driver",
  vehicle: "Vehicle",
  trailer: "Trailer",
  unlinked: "Not linked",
  ticket: "Linked ticket",
  phase: "Phase",
  source: "Source",
  observed: "Recorded",
  availableActions: "Permitted actions",
  saved: "Saved. The current server record is shown.",
  blocked:
    "The record changed or this action is blocked. Refresh and review the current run before retrying.",
  create: "Create run",
  title: "Run title",
  pickup: "Pickup site",
  delivery: "Delivery site",
  driverId: "Driver user ID",
  vehicleId: "Vehicle inventory ID",
  reason: "Reason",
  cancel: "Cancel",
  submit: "Save exact change",
  action: "Action",
  reviewChange:
    "Review this exact change before saving. Dispatch and driver acknowledgement are separate events.",
  acknowledge: "Acknowledge assignment",
  reassign: "Reassign",
  cancelRun: "Cancel run",
  dispatchRun: "Dispatch run",
  noActions: "No actions are currently permitted on this run.",
  unavailableTracking:
    "Vehicle tracking is not connected. No hardware positions, load phases or driving activity are inferred.",
  assigned: "Assigned work",
  noAssigned: "No runs are currently assigned to you.",
  readiness:
    "Readiness and eligibility are checked by the server when dispatch is saved.",
} as const;
const es: Record<keyof typeof en, string> = {
  workspace: "Operaciones de flota",
  desk: "Centro de flota",
  dispatch: "Despacho",
  runs: "Recorridos",
  myDay: "Mi día",
  myRun: "Mi recorrido",
  map: "Mapa en vivo",
  equipment: "Inventario",
  workHub: "Centro de trabajo",
  fieldOps: "Operaciones de campo",
  subtitle:
    "Despacho autorizado, recorridos asignados y ubicaciones registradas",
  refresh: "Actualizar",
  loading: "Cargando su espacio de flota autorizado…",
  denied:
    "No tiene acceso a la flota de esta empresa. Pida al administrador que revise sus permisos.",
  unavailable:
    "No se pudieron cargar los registros de flota. Actualice para volver a intentar.",
  fleet: "Flota",
  site: "Sitio",
  status: "Estado",
  all: "Todos",
  search: "Buscar título del recorrido",
  updated: "Actualizado",
  active: "Recorridos activos",
  unassigned: "Sin asignar",
  attention: "Necesita atención",
  selected: "Recorrido seleccionado",
  noRuns: "No hay recorridos autorizados que coincidan con estos filtros.",
  noSelection: "Seleccione un recorrido del mapa o la lista.",
  noLocations:
    "No hay posiciones registradas autorizadas. Los recorridos siguen disponibles abajo.",
  mapHint:
    "Las ubicaciones son observaciones, no pruebas de carga o entrega. Se muestra la hora y vigencia.",
  stops: "Paradas ordenadas",
  loads: "Cargas y manifiestos",
  events: "Actividad guardada",
  noLoads: "No hay cargas guardadas.",
  noEvents: "No hay actividad guardada.",
  noStops: "No hay paradas guardadas.",
  version: "Versión",
  driver: "Conductor",
  vehicle: "Vehículo",
  trailer: "Remolque",
  unlinked: "Sin vincular",
  ticket: "Ticket vinculado",
  phase: "Fase",
  source: "Fuente",
  observed: "Registrado",
  availableActions: "Acciones permitidas",
  saved: "Guardado. Se muestra el registro actual del servidor.",
  blocked:
    "El registro cambió o la acción está bloqueada. Actualice y revise el recorrido antes de reintentar.",
  create: "Crear recorrido",
  title: "Título del recorrido",
  pickup: "Sitio de recogida",
  delivery: "Sitio de entrega",
  driverId: "ID de usuario del conductor",
  vehicleId: "ID del vehículo en inventario",
  reason: "Motivo",
  cancel: "Cancelar",
  submit: "Guardar cambio exacto",
  action: "Acción",
  reviewChange:
    "Revise este cambio exacto antes de guardarlo. El despacho y la confirmación del conductor son eventos separados.",
  acknowledge: "Confirmar asignación",
  reassign: "Reasignar",
  cancelRun: "Cancelar recorrido",
  dispatchRun: "Despachar recorrido",
  noActions: "No hay acciones permitidas para este recorrido.",
  unavailableTracking:
    "El rastreo de vehículos no está conectado. No se infieren posiciones, fases de carga ni conducción.",
  assigned: "Trabajo asignado",
  noAssigned: "No tiene recorridos asignados.",
  readiness:
    "El servidor comprueba la disponibilidad y elegibilidad al guardar el despacho.",
};
export const fleetCopy = (language: string) =>
  language.startsWith("es") ? es : en;
