/** Fleet-specific copy kept together while the workspace evolves. */
const en = {
  etaTitle: "Phone-sourced driving estimate",
  etaBasis:
    "Uses a current driver-phone observation and Mapbox driving route to the next stop. It is not truck-safe routing or proof of arrival. Read on demand; estimates may change.",
  etaRead: "Read current driving estimate",
  etaUnavailable: "A current authorized driving estimate is unavailable.",
  etaInactive: "This run is not active.",
  etaPaused: "This run is paused.",
  etaNoLocation:
    "No current sufficiently accurate authorized phone observation is available.",
  etaNoStop: "No next stop is available.",
  etaNoDestination: "The authorized destination has no usable coordinates.",
  etaChanged:
    "The assignment, source or stop changed while estimating. Read again.",
  etaMinutes: "minutes",
  etaMiles: "miles",
  etaEstimated: "Estimated at",
  etaPhone: "Phone observation recorded",
  etaAccuracy: "Reported accuracy",
  etaProvider: "Provider",
  etaTraffic: "Traffic-aware",
  etaConfidence: "Route confidence",
  etaYes: "Yes",
  etaNo: "No",
  support: "Explicit Fleet support access",
  supportScope:
    "Read-only access expires automatically and is limited to granted fleets and sites. No coordinates or mutation controls are available.",
  supportChoose: "Select a company with a current support grant",
  supportReason: "Support reason",
  supportExpires: "Access expires",
  supportAdminId: "Exact platform administrator user ID",
  supportAdd: "Add reviewed support grant",
  supportRemove: "Remove support grant",
  supportFinance: "Permit fuel records in read-only support",
  supportExpiry: "Expiry (within seven days)",
  supportGrantScope:
    "Select exact fleets and sites. The server validates the administrator and scope before saving.",
  drivers: "Drivers",
  openInventory: "Open canonical Inventory",
  availableReview: "Available for eligibility review",
  dispatchUnavailable: "Unavailable for dispatch",
  noTrailer: "No trailer assigned",
  driverDirectoryScope:
    "Directory is available to dispatch authority. Drivers see their own assigned runs.",
  readinessTitle: "Recorded readiness",
  readinessReported:
    "Inspection and meter entries are user reports. Certifications, holds and assignment eligibility are rechecked by the server; these entries do not prove regulatory clearance.",
  inspection: "Latest reported inspection",
  initialMeter: "Initial reported meter reading",
  actions: "Current permitted actions",
  costs: "Fuel and costs",
  costsUnavailable:
    "Recorded fuel quantities are available in Reports only with finance authority. Prices, rates, cost totals, detention and accounting exports have no connected source.",
  siteActivity: "Fleet activity at your sites",
  selectActivitySite: "Select an authorized site",
  activityWindow:
    "Select runs by creation date. Records on those runs may have been reported later.",
  activityPrivacy:
    "Recorded site activity only. Driver locations, other stops, fuel and costs are unavailable.",
  activityEmpty: "No recorded Fleet activity in this window.",
  activityUnavailable:
    "Authorized site activity is unavailable. Refresh to retry.",
  activityStart: "Start date and time",
  activityEnd: "End date and time",
  activityApply: "Load recorded activity",
  activityAccepted: "Accepted by server",
  activityCaptured: "Reported event time",
  activityDelivered: "Delivery reported",
  gateObservations: "Gate observations and run links",
  gateBasis:
    "Candidates share this run’s equipment, authorized site and time window. A candidate does not prove a stop arrival or create Gate admission.",
  gateAmbiguous:
    "Multiple possible visits require explicit selection. No visit is automatically matched.",
  gateUnavailable:
    "Authorized Gate observations are unavailable. Refresh to retry.",
  noGateObservations: "No authorized Gate visit candidates returned.",
  gateVisit: "Existing Gate visit",
  gateCheckIn: "Gate check-in recorded",
  gateCheckOut: "Gate check-out recorded",
  observedArrival: "Source-reported arrival",
  observedDeparture: "Source-reported departure",
  unknownSource: "Source not reported",
  notRecorded: "Not recorded",
  gateStop: "Select the exact same-site run stop",
  reviewGateLink: "Review exact visit link",
  saveGateLink: "Save reviewed visit link",
  gateLinkSaved:
    "Existing visit linked to this run stop. No Gate admission or physical arrival was created.",
  gateLinkFailed:
    "Link outcome was not confirmed. Refresh and retry the same reviewed operation to recover its saved outcome.",
  savedGateLinks: "Saved visit links",
  noGateLinks: "No visit links saved.",
  alreadyLinked: "Already linked to this run",
  selectGateVisit: "Select an existing visit candidate",
  reports: "Fleet reports and saved filters",
  reportExplanation:
    "Dates select runs by server-recorded creation time; totals include every recorded entry on those runs, including later entries. User reports do not prove physical delivery, fuel purchase or telemetry.",
  reportSource: "Recorded Fleet events",
  reportUnavailable:
    "Report could not be loaded for the selected scope. Refresh or review the filters.",
  applyFilters: "Apply reviewed filters",
  startsAt: "Start time (local time, optional)",
  endsAt: "End time (local time, optional)",
  savedViews: "Your saved filters",
  viewName: "Saved filter name",
  reviewSaveView: "Review filter save",
  reviewArchiveView: "Review filter archive",
  saveView: "Save reviewed filter change",
  newView: "New saved filter",
  viewSaved:
    "Personal filter saved. It does not change Fleet authority or physical screen placement.",
  viewFailed:
    "Filter outcome was not confirmed. Retry the same reviewed request to recover the saved outcome.",
  noViews: "No personal filters saved.",
  completedRuns: "Completed runs",
  submittedRuns: "Submitted for review",
  inspectionExceptions: "Reported inspection exceptions",
  recordedQuantity: "Recorded quantity",
  deliveredQuantity: "Reported delivered quantity",
  distance: "Reported distance",
  fuel: "Reported fuel",
  fuelRestricted:
    "Fuel totals are unavailable without separate Fleet financial read authority.",
  noTotals: "No recorded totals for these filters.",
  unavailableMetrics: "Unavailable metrics",
  archive: "Archive personal filter",
  filterInvalid:
    "Choose valid authorized filters; the end time must follow the start.",
  closeService: "Close reviewed service record",
  loadMoreMaintenance: "Load more authorized maintenance records",
  maintenance: "Maintenance and defects",
  maintenanceExplanation:
    "Reports and repair entries are attributed user reports. Safety release is a separate authorized action; these records do not certify physical repair.",
  maintenanceUnavailable:
    "Maintenance records are unavailable. Refresh to retry.",
  maintenanceEmpty: "No authorized maintenance records returned.",
  reportMaintenance: "Report a defect or plan service",
  maintenanceTitle: "Report title",
  notes: "Actual observations and notes",
  dueAt: "Service due date (optional)",
  kind: "Record type",
  defect: "Defect report",
  scheduled_service: "Scheduled service",
  reviewMaintenance: "Review exact report",
  saveMaintenance: "Save reviewed report",
  maintenanceSaved:
    "Report saved. Refresh shows its current authorized outcome.",
  maintenanceBlocked:
    "The outcome was not confirmed. Refresh the record and retry this same reviewed request to recover its saved outcome.",
  selectMaintenance:
    "Select a maintenance record to review its history and permitted actions.",
  hold: "Inventory safety hold",
  triage: "Begin service review",
  record_repair: "Record reported repair",
  release: "Release safety hold after repair review",
  cancelMaintenance: "Cancel maintenance record",
  saveMaintenanceAction: "Save reviewed maintenance action",
  reported: "Reported",
  in_service: "In service",
  repair_recorded: "Repair recorded",
  released: "Released",
  cancelled: "Cancelled",
  equipmentSelection: "Authorized equipment",
  ownRun: "Your assigned run",
  noMaintenanceActions: "No maintenance actions currently permitted.",
  reviewReport: "Review the exact equipment, report and notes before saving.",
  safetyRelease:
    "Authority to release a Fleet safety hold after documented repair and review",
  financeRead: "Authority to read Fleet financial costs",
  loadedRuns:
    "Loaded authorized runs (filters and counts apply to loaded records)",
  loadMore: "Load more authorized runs",
  review: "Operational Review",
  setup: "Fleet setup",
  settings: "Workspace settings",
  preferenceUnavailable:
    "Workspace preference is unavailable. Refresh to load its current version.",
  preferenceHeading: "Your Fleet workspace",
  preferenceExplanation:
    "Choose your default home in this company. This setting does not grant access or change assignments.",
  defaultHome: "Default home",
  standardHome: "Standard company home",
  preferredFleet: "Preferred fleet",
  allFleets: "All authorized fleets",
  savePreference: "Save reviewed preference",
  preferenceSaved: "Workspace preference saved.",
  preferenceFailed:
    "Preference was not confirmed. Refresh and review its current version before retrying.",
  setupLoading: "Loading Fleet configuration…",
  setupDenied:
    "Fleet setup requires company administrator permission. Refresh to retry.",
  refreshConfiguration: "Refresh configuration",
  setupExplanation:
    "Company administrators explicitly enable Fleet and assign fleets, sites and roles. Review all changes before saving.",
  enableFleet: "Enable Fleet Ops",
  fleetsSites: "Fleets and authorized sites",
  assignedEquipment: "Assigned inventory equipment",
  certifications: "Required certifications (one per line)",
  newFleet: "New fleet name",
  addFleet: "Add fleet",
  memberGrants: "Explicit member grants",
  member: "Company member",
  chooseMember: "Choose company member",
  addGrant: "Add member grant",
  removeGrant: "Remove grant",
  fleet_manager: "Fleet manager",
  dispatcher: "Dispatcher",
  separateAuthorities:
    "Safety-release and financial access are separate explicit authorities. A role, certification or reported repair does not grant either permission.",
  saveConfiguration: "Save reviewed configuration",
  setupSaved: "Fleet configuration saved.",
  setupFailed:
    "Configuration could not be saved. Refresh and review company sites, memberships and current version before retrying.",
  workspace: "Fleet Ops",
  desk: "Fleet Desk",
  dispatch: "Dispatch",
  runs: "Runs",
  myDay: "My Day",
  myRun: "My Run",
  map: "Recorded Map",
  equipment: "Inventory",
  workHub: "Work Hub",
  fieldOps: "Field Ops",
  subtitle: "Authorized dispatch, assigned runs and recorded locations",
  refresh: "Refresh",
  loading: "Loading your authorized Fleet workspace…",
  denied:
    "Fleet access is unavailable for this company. Ask your company administrator to check your Fleet grants.",
  unavailable: "Fleet records could not be loaded. Refresh to try again.",
  fleet: "Fleet",
  site: "Site",
  status: "Status",
  all: "All",
  search: "Search run title",
  updated: "Updated",
  active: "Active runs",
  unassigned: "Unassigned runs",
  attention: "Needs attention",
  selected: "Selected run",
  noRuns: "No authorized runs match these filters.",
  noSelection: "Select a run from the map or list.",
  noLocations:
    "No authorized recorded positions are available. Run records remain available below.",
  mapHint:
    "Locations are observations, not proof of loading or delivery. Recorded times and freshness remain visible.",
  stops: "Ordered stops",
  loads: "Loads and manifests",
  events: "Saved activity",
  noLoads: "No load records saved.",
  noEvents: "No activity saved.",
  noStops: "No stops saved.",
  version: "Version",
  driver: "Driver",
  vehicle: "Vehicle",
  trailer: "Trailer",
  unlinked: "Not linked",
  ticket: "Linked ticket",
  phase: "Phase",
  source: "Source",
  observed: "Recorded",
  availableActions: "Permitted actions",
  saved: "Saved. The current server record is shown.",
  blocked:
    "The record changed or this action is blocked. Refresh and review the current run before retrying.",
  create: "Create run",
  title: "Run title",
  pickup: "Pickup site",
  delivery: "Delivery site",
  driverId: "Driver user ID",
  vehicleId: "Vehicle inventory ID",
  reason: "Reason",
  cancel: "Cancel",
  submit: "Save exact change",
  action: "Action",
  reviewChange:
    "Review this exact change before saving. Dispatch and driver acknowledgement are separate events.",
  acknowledge: "Acknowledge assignment",
  reassign: "Reassign",
  cancelRun: "Cancel run",
  dispatchRun: "Dispatch run",
  noActions: "No actions are currently permitted on this run.",
  unavailableTracking:
    "Vehicle tracking is not connected. No hardware positions, load phases or driving activity are inferred.",
  assigned: "Assigned work",
  noAssigned: "No runs are currently assigned to you.",
  readiness:
    "Readiness and eligibility are checked by the server when dispatch is saved.",
} as const;
const es: Record<keyof typeof en, string> = {
  etaTitle: "Estimación de conducción desde el teléfono",
  etaBasis:
    "Usa una observación actual del teléfono del conductor y una ruta de Mapbox hacia la siguiente parada. No es una ruta segura para camiones ni prueba de llegada. Consulte cuando lo necesite; puede cambiar.",
  etaRead: "Consultar estimación actual",
  etaUnavailable: "No hay una estimación de conducción autorizada actual.",
  etaInactive: "Este recorrido no está activo.",
  etaPaused: "Este recorrido está en pausa.",
  etaNoLocation:
    "No hay una observación autorizada actual del teléfono con suficiente precisión.",
  etaNoStop: "No hay siguiente parada.",
  etaNoDestination: "El destino autorizado no tiene coordenadas utilizables.",
  etaChanged:
    "La asignación, fuente o parada cambió durante la estimación. Consulte otra vez.",
  etaMinutes: "minutos",
  etaMiles: "millas",
  etaEstimated: "Estimado a las",
  etaPhone: "Observación del teléfono registrada",
  etaAccuracy: "Precisión reportada",
  etaProvider: "Proveedor",
  etaTraffic: "Considera tráfico",
  etaConfidence: "Confianza de la ruta",
  etaYes: "Sí",
  etaNo: "No",
  support: "Acceso explícito de soporte de flota",
  supportScope:
    "El acceso de solo lectura caduca automáticamente y se limita a flotas y sitios autorizados. No incluye coordenadas ni controles de cambios.",
  supportChoose: "Seleccione una empresa con permiso de soporte vigente",
  supportReason: "Motivo del soporte",
  supportExpires: "El acceso caduca",
  supportAdminId: "ID exacto del administrador de la plataforma",
  supportAdd: "Agregar permiso de soporte revisado",
  supportRemove: "Eliminar permiso de soporte",
  supportFinance:
    "Permitir registros de combustible en soporte de solo lectura",
  supportExpiry: "Caducidad (dentro de siete días)",
  supportGrantScope:
    "Seleccione flotas y sitios exactos. El servidor valida el administrador y el alcance antes de guardar.",
  drivers: "Conductores",
  openInventory: "Abrir Inventario canónico",
  availableReview: "Disponible para revisar elegibilidad",
  dispatchUnavailable: "No disponible para despacho",
  noTrailer: "Sin remolque asignado",
  driverDirectoryScope:
    "El directorio requiere autoridad de despacho. Los conductores ven sus propios recorridos asignados.",
  readinessTitle: "Preparación registrada",
  readinessReported:
    "Las inspecciones y lecturas son reportes del usuario. El servidor comprueba certificaciones, retenciones y elegibilidad; estos registros no prueban autorización normativa.",
  inspection: "Última inspección reportada",
  initialMeter: "Lectura inicial reportada",
  actions: "Acciones actualmente permitidas",
  costs: "Combustible y costos",
  costsUnavailable:
    "Las cantidades de combustible registradas están en Informes con autoridad financiera. Precios, tarifas, costos totales, detención y exportaciones contables no tienen una fuente conectada.",
  siteActivity: "Actividad de flota en sus sitios",
  selectActivitySite: "Seleccione un sitio autorizado",
  activityWindow:
    "Seleccione recorridos por fecha de creación. Los registros de esos recorridos pueden haberse reportado después.",
  activityPrivacy:
    "Solo actividad registrada del sitio. No se muestran ubicaciones de conductores, otras paradas, combustible ni costos.",
  activityEmpty: "No hay actividad de flota registrada en este periodo.",
  activityUnavailable:
    "La actividad autorizada no está disponible. Actualice para reintentar.",
  activityStart: "Fecha y hora inicial",
  activityEnd: "Fecha y hora final",
  activityApply: "Cargar actividad registrada",
  activityAccepted: "Aceptado por el servidor",
  activityCaptured: "Hora reportada del evento",
  activityDelivered: "Entrega reportada",
  gateObservations: "Observaciones de acceso y vínculos del recorrido",
  gateBasis:
    "Los candidatos coinciden en equipo, sitio autorizado y período del recorrido. Un candidato no prueba llegada a una parada ni crea una admisión.",
  gateAmbiguous:
    "Hay varias visitas posibles; seleccione de forma explícita. Ninguna se vincula automáticamente.",
  gateUnavailable:
    "Las observaciones de acceso autorizadas no están disponibles. Actualice para reintentar.",
  noGateObservations: "No hay visitas de acceso autorizadas candidatas.",
  gateVisit: "Visita de acceso existente",
  gateCheckIn: "Entrada registrada en acceso",
  gateCheckOut: "Salida registrada en acceso",
  observedArrival: "Llegada reportada por la fuente",
  observedDeparture: "Salida reportada por la fuente",
  unknownSource: "Fuente no reportada",
  notRecorded: "Sin registrar",
  gateStop: "Seleccione la parada exacta del mismo sitio",
  reviewGateLink: "Revisar vínculo exacto de visita",
  saveGateLink: "Guardar vínculo de visita revisado",
  gateLinkSaved:
    "Visita existente vinculada a la parada. No se creó admisión ni llegada física.",
  gateLinkFailed:
    "No se confirmó el vínculo. Actualice y reintente la misma operación revisada para recuperar el resultado guardado.",
  savedGateLinks: "Vínculos de visitas guardados",
  noGateLinks: "No hay vínculos de visitas guardados.",
  alreadyLinked: "Ya vinculada a este recorrido",
  selectGateVisit: "Seleccione una visita existente candidata",
  reports: "Reportes de flota y filtros guardados",
  reportExplanation:
    "Las fechas seleccionan recorridos por su creación registrada en el servidor; los totales incluyen todos sus registros, incluso los posteriores. Los reportes de usuarios no prueban entrega física, compra de combustible ni telemetría.",
  reportSource: "Eventos de flota registrados",
  reportUnavailable:
    "No se pudo cargar el reporte para este alcance. Actualice o revise los filtros.",
  applyFilters: "Aplicar filtros revisados",
  startsAt: "Hora inicial (hora local, opcional)",
  endsAt: "Hora final (hora local, opcional)",
  savedViews: "Sus filtros guardados",
  viewName: "Nombre del filtro guardado",
  reviewSaveView: "Revisar guardado del filtro",
  reviewArchiveView: "Revisar archivo del filtro",
  saveView: "Guardar cambio de filtro revisado",
  newView: "Nuevo filtro guardado",
  viewSaved:
    "Filtro personal guardado. No cambia permisos de flota ni la visualización en pantallas físicas.",
  viewFailed:
    "No se confirmó el resultado del filtro. Reintente la misma solicitud revisada para recuperar el resultado guardado.",
  noViews: "No hay filtros personales guardados.",
  completedRuns: "Recorridos completados",
  submittedRuns: "Enviados a revisión",
  inspectionExceptions: "Excepciones de inspección reportadas",
  recordedQuantity: "Cantidad registrada",
  deliveredQuantity: "Cantidad entregada reportada",
  distance: "Distancia reportada",
  fuel: "Combustible reportado",
  fuelRestricted:
    "Los totales de combustible requieren autoridad financiera independiente de flota.",
  noTotals: "No hay totales registrados para estos filtros.",
  unavailableMetrics: "Métricas no disponibles",
  archive: "Archivar filtro personal",
  filterInvalid:
    "Elija filtros autorizados válidos; la hora final debe ser posterior a la inicial.",
  closeService: "Cerrar registro de servicio revisado",
  loadMoreMaintenance: "Cargar más registros de mantenimiento autorizados",
  maintenance: "Mantenimiento y defectos",
  maintenanceExplanation:
    "Los reportes y reparaciones son declaraciones de usuarios identificados. La liberación de seguridad requiere una acción autorizada independiente; estos registros no certifican la reparación física.",
  maintenanceUnavailable:
    "Los registros de mantenimiento no están disponibles. Actualice para reintentar.",
  maintenanceEmpty: "No hay registros de mantenimiento autorizados.",
  reportMaintenance: "Reportar defecto o planificar servicio",
  maintenanceTitle: "Título del reporte",
  notes: "Observaciones reales y notas",
  dueAt: "Fecha de servicio (opcional)",
  kind: "Tipo de registro",
  defect: "Reporte de defecto",
  scheduled_service: "Servicio programado",
  reviewMaintenance: "Revisar reporte exacto",
  saveMaintenance: "Guardar reporte revisado",
  maintenanceSaved:
    "Reporte guardado. Actualice para ver el resultado autorizado actual.",
  maintenanceBlocked:
    "No se confirmó el resultado. Actualice el registro y reintente la misma solicitud revisada para recuperar el resultado guardado.",
  selectMaintenance:
    "Seleccione un registro para revisar su historial y acciones permitidas.",
  hold: "Retención de seguridad en inventario",
  triage: "Iniciar revisión de servicio",
  record_repair: "Registrar reparación reportada",
  release: "Liberar retención tras revisar la reparación",
  cancelMaintenance: "Cancelar registro de mantenimiento",
  saveMaintenanceAction: "Guardar acción de mantenimiento revisada",
  reported: "Reportado",
  in_service: "En servicio",
  repair_recorded: "Reparación registrada",
  released: "Liberado",
  cancelled: "Cancelado",
  equipmentSelection: "Equipo autorizado",
  ownRun: "Su recorrido asignado",
  noMaintenanceActions: "No hay acciones de mantenimiento permitidas.",
  reviewReport: "Revise el equipo, reporte y notas exactos antes de guardar.",
  safetyRelease:
    "Autoridad para liberar una retención de seguridad tras reparación y revisión documentadas",
  financeRead: "Autoridad para consultar costos financieros de flota",
  loadedRuns:
    "Recorridos autorizados cargados (filtros y conteos se aplican a registros cargados)",
  loadMore: "Cargar más recorridos autorizados",
  review: "Revisión operativa",
  setup: "Configuración de flota",
  settings: "Preferencias del espacio",
  preferenceUnavailable:
    "La preferencia no está disponible. Actualice para cargar su versión actual.",
  preferenceHeading: "Su espacio de flota",
  preferenceExplanation:
    "Elija su inicio predeterminado en esta empresa. Esta preferencia no concede acceso ni cambia asignaciones.",
  defaultHome: "Inicio predeterminado",
  standardHome: "Inicio habitual de la empresa",
  preferredFleet: "Flota preferida",
  allFleets: "Todas las flotas autorizadas",
  savePreference: "Guardar preferencia revisada",
  preferenceSaved: "Preferencia guardada.",
  preferenceFailed:
    "No se confirmó la preferencia. Actualice y revise la versión actual antes de reintentar.",
  setupLoading: "Cargando configuración de flota…",
  setupDenied:
    "La configuración requiere permiso de administrador de la empresa. Actualice para reintentar.",
  refreshConfiguration: "Actualizar configuración",
  setupExplanation:
    "Los administradores habilitan la flota y asignan flotas, sitios y funciones de forma explícita. Revise los cambios antes de guardar.",
  enableFleet: "Habilitar operaciones de flota",
  fleetsSites: "Flotas y sitios autorizados",
  assignedEquipment: "Equipo de inventario asignado",
  certifications: "Certificaciones requeridas (una por línea)",
  newFleet: "Nombre de nueva flota",
  addFleet: "Agregar flota",
  memberGrants: "Permisos explícitos de miembros",
  member: "Miembro de la empresa",
  chooseMember: "Elegir miembro de la empresa",
  addGrant: "Agregar permisos de miembro",
  removeGrant: "Eliminar permisos",
  fleet_manager: "Administrador de flota",
  dispatcher: "Despachador",
  separateAuthorities:
    "La liberación de seguridad y el acceso financiero son autoridades explícitas independientes. Una función, certificación o reparación reportada no concede estos permisos.",
  saveConfiguration: "Guardar configuración revisada",
  setupSaved: "Configuración de flota guardada.",
  setupFailed:
    "No se pudo guardar la configuración. Actualice y revise los sitios, miembros y versión actual antes de reintentar.",
  workspace: "Operaciones de flota",
  desk: "Centro de flota",
  dispatch: "Despacho",
  runs: "Recorridos",
  myDay: "Mi día",
  myRun: "Mi recorrido",
  map: "Mapa registrado",
  equipment: "Inventario",
  workHub: "Centro de trabajo",
  fieldOps: "Operaciones de campo",
  subtitle:
    "Despacho autorizado, recorridos asignados y ubicaciones registradas",
  refresh: "Actualizar",
  loading: "Cargando su espacio de flota autorizado…",
  denied:
    "No tiene acceso a la flota de esta empresa. Pida al administrador que revise sus permisos.",
  unavailable:
    "No se pudieron cargar los registros de flota. Actualice para volver a intentar.",
  fleet: "Flota",
  site: "Sitio",
  status: "Estado",
  all: "Todos",
  search: "Buscar título del recorrido",
  updated: "Actualizado",
  active: "Recorridos activos",
  unassigned: "Sin asignar",
  attention: "Necesita atención",
  selected: "Recorrido seleccionado",
  noRuns: "No hay recorridos autorizados que coincidan con estos filtros.",
  noSelection: "Seleccione un recorrido del mapa o la lista.",
  noLocations:
    "No hay posiciones registradas autorizadas. Los recorridos siguen disponibles abajo.",
  mapHint:
    "Las ubicaciones son observaciones, no pruebas de carga o entrega. Se muestra la hora y vigencia.",
  stops: "Paradas ordenadas",
  loads: "Cargas y manifiestos",
  events: "Actividad guardada",
  noLoads: "No hay cargas guardadas.",
  noEvents: "No hay actividad guardada.",
  noStops: "No hay paradas guardadas.",
  version: "Versión",
  driver: "Conductor",
  vehicle: "Vehículo",
  trailer: "Remolque",
  unlinked: "Sin vincular",
  ticket: "Ticket vinculado",
  phase: "Fase",
  source: "Fuente",
  observed: "Registrado",
  availableActions: "Acciones permitidas",
  saved: "Guardado. Se muestra el registro actual del servidor.",
  blocked:
    "El registro cambió o la acción está bloqueada. Actualice y revise el recorrido antes de reintentar.",
  create: "Crear recorrido",
  title: "Título del recorrido",
  pickup: "Sitio de recogida",
  delivery: "Sitio de entrega",
  driverId: "ID de usuario del conductor",
  vehicleId: "ID del vehículo en inventario",
  reason: "Motivo",
  cancel: "Cancelar",
  submit: "Guardar cambio exacto",
  action: "Acción",
  reviewChange:
    "Revise este cambio exacto antes de guardarlo. El despacho y la confirmación del conductor son eventos separados.",
  acknowledge: "Confirmar asignación",
  reassign: "Reasignar",
  cancelRun: "Cancelar recorrido",
  dispatchRun: "Despachar recorrido",
  noActions: "No hay acciones permitidas para este recorrido.",
  unavailableTracking:
    "El rastreo de vehículos no está conectado. No se infieren posiciones, fases de carga ni conducción.",
  assigned: "Trabajo asignado",
  noAssigned: "No tiene recorridos asignados.",
  readiness:
    "El servidor comprueba la disponibilidad y elegibilidad al guardar el despacho.",
};
export const fleetCopy = (language: string) =>
  language.startsWith("es") ? es : en;
