import { FormEvent, useState } from "react";
import { AppModalHeader, APP_MODAL_HEADER_ICON_CLASSNAME } from "@/components/app-modal-header";
import { VNDRLY_LOGO_SQUARE } from "@/lib/vndrly-brand-assets";
import { DEFAULT_BRAND, brandStyleVars } from "@/hooks/use-brand";
import { Bot, X } from "lucide-react";
import { PngPillButton } from "@/components/png-pill-rollover";

type Answer = { text: string; href: string; label: string };
export default function PublicAskV() { const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [answer, setAnswer] = useState<Answer | null>(null); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/public/askv", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, locale: document.documentElement.lang === "es" ? "es" : "en" }) }); const body = await response.json(); setAnswer(response.ok ? body : { text: body.message ?? "Ask V is unavailable right now.", href: "mailto:support@vndrly.ai", label: "Contact Support" }); } catch { setAnswer({ text: "Ask V is unavailable right now. You can still explore VNDRLY or contact Support.", href: "mailto:support@vndrly.ai", label: "Contact Support" }); } finally { setBusy(false); } }
  return <><button type="button" onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-30 flex min-h-12 items-center gap-2 rounded-full border border-[var(--vndrly-amber)] bg-slate-950 px-5 font-bold text-white shadow-[0_14px_40px_rgba(245,158,11,.25)] outline-none transition hover:-translate-y-0.5 focus-visible:ring-2 focus-visible:ring-[var(--vndrly-amber)]" aria-haspopup="dialog" aria-label="Ask V — Product Guide"><Bot className="h-5 w-5 text-[var(--vndrly-amber)]"/>Ask V <span className="hidden text-xs font-medium text-slate-300 sm:inline">Product Guide</span></button>{open && <section role="dialog" aria-modal="false" aria-labelledby="public-askv-title" className="fixed bottom-20 right-4 z-40 w-[calc(100vw-2rem)] max-w-sm max-h-[calc(100dvh-7rem)] overflow-y-auto rounded-2xl border-2 border-[var(--vndrly-amber)] bg-[#3a3d42] shadow-2xl" style={brandStyleVars(DEFAULT_BRAND)}><AppModalHeader
          logo={{ src: VNDRLY_LOGO_SQUARE, alt: "VNDRLY", fallbackName: "VNDRLY" }}
          title={<h2 id="public-askv-title" className="font-bold">Ask V — Product Guide</h2>}
          description="Public product information only"
          closeControl={<button type="button" onClick={() => setOpen(false)} aria-label="Close Ask V Product Guide" className={APP_MODAL_HEADER_ICON_CLASSNAME}><X className="h-4 w-4" /></button>}
        /><div className="p-5 bg-[#d1d5db] text-gray-900"><p className="mt-4 text-sm text-muted-foreground">Ask about VNDRLY products, roles, signup, onboarding, demos, or sales. This guide cannot access accounts or perform operational actions.</p><form onSubmit={submit} className="mt-4"><label htmlFor="public-askv-question" className="text-sm font-semibold">Your question</label><textarea id="public-askv-question" maxLength={800} required value={message} onChange={(event) => setMessage(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border-2 border-[var(--vndrly-amber)] bg-background p-3 outline-none focus-visible:ring-2 focus-visible:ring-[var(--vndrly-amber)]"/><PngPillButton color="amber" type="submit" disabled={busy || !message.trim()} className="mt-3">{busy ? "Checking…" : "Ask V"}</PngPillButton></form>{answer && <div aria-live="polite" className="mt-4 rounded-lg bg-muted p-3 text-sm"><p>{answer.text}</p><a className="mt-2 inline-block font-bold text-[var(--vndrly-amber)] underline" href={answer.href}>{answer.label}</a></div>}</div></section>}</>;
}
