import {render,screen,fireEvent,waitFor} from '@testing-library/react';import {it,expect,vi} from 'vitest';
const api=vi.hoisted(()=>({request:vi.fn()}));vi.mock('./client',()=>({implementationARequest:api.request}));vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:'en'}})}));vi.mock('@/components/png-pill-rollover',()=>({PngPillButton:(p:React.ButtonHTMLAttributes<HTMLButtonElement>)=><button {...p}/>}));
import {InventoryHoldRelease} from './asset-hold-release';
const id='11111111-1111-4111-8111-111111111111',holdId='22222222-2222-4222-8222-222222222222';
it('retries the identical reviewed hold/body/version after an unknown response and retains unrelated hold',async()=>{api.request.mockReset().mockRejectedValueOnce(Error('Lost')).mockImplementationOnce(async(_path:string,init:RequestInit)=>{const body=JSON.parse(String(init.body));return{assetId:id,holdId,operationId:body.operationId,version:5,status:'applied',physicalRepairVerified:false};});const onSaved=vi.fn();const view=render(<InventoryHoldRelease assetId={id} version={4} holds={[{id:holdId,reason:'Review radio',placedAt:'2026-10-07T00:00:00Z',source:'inventory',canRelease:true},{id:'other',reason:'Fleet safety hold',placedAt:'2026-10-07T00:00:00Z',source:'fleet_maintenance',canRelease:false}]} onSaved={onSaved}/>);fireEvent.click(screen.getByRole('button',{name:'Release selected Inventory hold: Review radio'}));fireEvent.change(screen.getByLabelText('Reason for administrative release'),{target:{value:'Reviewed administrative hold'}});fireEvent.click(screen.getByText('Review exact hold release'));fireEvent.click(screen.getByText('Confirm reviewed release'));await screen.findByText(/Release outcome is unverified/);view.rerender(<InventoryHoldRelease assetId={id} version={8} holds={[]} onSaved={onSaved}/>);fireEvent.click(screen.getByText('Retry exact reviewed release'));await waitFor(()=>expect(onSaved).toHaveBeenCalled());expect(api.request.mock.calls[1]).toEqual(api.request.mock.calls[0]);expect(JSON.parse(api.request.mock.calls[1][1].body)).toMatchObject({expectedVersion:4,reason:'Reviewed administrative hold'});expect(api.request.mock.calls[0][0]).toBe('/assets/'+id+'/holds/'+holdId+'/release');});
it('does not offer release for Fleet maintenance holds or ungranted Inventory holds',()=>{render(<InventoryHoldRelease assetId={id} version={4} holds={[{id:holdId,reason:'Fleet',placedAt:'2026-10-07T00:00:00Z',source:'fleet_maintenance',canRelease:true},{id:'other',reason:'Inventory',placedAt:'2026-10-07T00:00:00Z',source:'inventory',canRelease:false}]} onSaved={vi.fn()}/>);expect(screen.queryByRole('button',{name:/Release selected/})).toBeNull();});

it('invalidates retained unknown intent when asset or account identity changes',async()=>{api.request.mockReset().mockRejectedValue(Error('Lost'));const holds=[{id:holdId,reason:'Review radio',placedAt:'2026-10-07T00:00:00Z',source:'inventory' as const,canRelease:true}];const view=render(<InventoryHoldRelease assetId={id} actorIdentity="account-one" version={4} holds={holds} onSaved={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Release selected Inventory hold: Review radio'}));fireEvent.change(screen.getByLabelText('Reason for administrative release'),{target:{value:'Reviewed'}});fireEvent.click(screen.getByText('Review exact hold release'));fireEvent.click(screen.getByText('Confirm reviewed release'));await screen.findByText(/Release outcome is unverified/);view.rerender(<InventoryHoldRelease assetId="another-asset" actorIdentity="account-two" version={9} holds={holds} onSaved={vi.fn()}/>);expect(screen.queryByText('Retry exact reviewed release')).toBeNull();expect(api.request).toHaveBeenCalledTimes(1);});

it('ignores a rejected in-flight response after identity changes',async()=>{let reject!:(error:Error)=>void;api.request.mockReset().mockImplementation(()=>new Promise((_resolve,fail)=>{reject=fail;}));const holds=[{id:holdId,reason:'Review radio',placedAt:'2026-10-07T00:00:00Z',source:'inventory' as const,canRelease:true}];const view=render(<InventoryHoldRelease assetId={id} actorIdentity="one" version={4} holds={holds} onSaved={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Release selected Inventory hold: Review radio'}));fireEvent.change(screen.getByLabelText('Reason for administrative release'),{target:{value:'Reviewed'}});fireEvent.click(screen.getByText('Review exact hold release'));fireEvent.click(screen.getByText('Confirm reviewed release'));view.rerender(<InventoryHoldRelease assetId="new-asset" actorIdentity="two" version={7} holds={holds} onSaved={vi.fn()}/>);reject(Error('Lost'));await waitFor(()=>expect((screen.getByRole('button',{name:'Release selected Inventory hold: Review radio'}) as HTMLButtonElement).disabled).toBe(false));expect(screen.queryByRole('status')).toBeNull();});
